import {getToken,ZERO_ADDRESS} from '../chains/registry.js';
import {resolveChain} from '../agent/intent.js';
const ADDRESS=/^0x[a-fA-F0-9]{40}$/;
export function parseAsset(value,chainId){const t=getToken(chainId,value);if(t)return{address:t.address,decimals:t.decimals,symbol:t.symbol};if(ADDRESS.test(value))return{address:value,decimals:18,symbol:value.slice(0,8)};throw new Error(`Unknown asset ${value}; use a verified token address`)}
export function parseRouteIntent(text,currentChain,account){const s=String(text||'');const bridge=/(?:bridge|move)/i.test(s);const m=s.match(/(?:swap|exchange|trade|bridge|move)\s+([\d.]+)\s*([A-Za-z0-9_-]+)\s+(?:for|to|into|onto)\s+([A-Za-z0-9 _-]+?)(?:\s+(?:on|to)\s+([A-Za-z0-9 _-]+))?$/i);if(!m)throw new Error(bridge?'Use: Bridge 100 USDC to Base':'Use: Swap 25 USDC for ETH');let toChain=currentChain;let toAsset=m[3].trim();if(bridge){const resolved=resolveChain(m[4]||m[3]);if(resolved){toChain=resolved;toAsset=m[2]}else throw new Error('Destination chain not recognized. Use a chain name or chain ID.')}const from=parseAsset(m[2],currentChain);const to=parseAsset(toAsset,toChain);return{bridge,fromChain:currentChain,toChain,fromToken:from.address||ZERO_ADDRESS,toToken:to.address||ZERO_ADDRESS,fromAmount:m[1],fromDecimals:from.decimals,toDecimals:to.decimals,fromSymbol:from.symbol,toSymbol:to.symbol,fromAddress:account,toAddress:account}}
export function parseSwapIntent(text,chainId,account){const p=parseRouteIntent(text,chainId,account);if(p.bridge)throw new Error('This is a bridge intent; use Bridge execution');if(p.fromChain!==p.toChain)throw new Error('Swap must use one chain');return p}
export async function quoteRoute(input){const params=new URLSearchParams();for(const [k,v] of Object.entries(input)){if(v!==undefined&&v!==null&&v!=='')params.set(k,String(v))}const r=await fetch(`/api/quote?${params}`);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'No verified route available');if(!data.transactionRequest?.to)throw new Error('Route provider returned no executable transaction');return data}
export function routeTx(quote,account){const t=quote.transactionRequest;if(!ADDRESS.test(t.to))throw new Error('Route returned an invalid transaction target');return{from:account,to:t.to,data:t.data||'0x',value:t.value||'0x0'}}
export function routeSummary(q){return{tool:q.toolDetails?.name||q.tool||'Route provider',from:q.action?.fromAmount,to:q.action?.toAmount,slippage:q.action?.slippage,gas:q.estimate?.gasCosts?.[0]?.amount,steps:(q.includedSteps||[]).map(x=>x.toolDetails?.name||x.tool||x.type).filter(Boolean)}}
export function routeSafety(q){const a=q.action||{};return{minimumReceived:a.toAmountMin||a.toAmount||null,expectedReceived:a.toAmount||null,slippage:a.slippage||null,steps:(q.includedSteps||[]).length,tool:routeSummary(q).tool}}
export async function buildCrossChainRoute({fromChain,toChain,fromToken,toToken,amount,account,recipient=account}){if(!fromChain||!toChain||fromChain===toChain)throw new Error('Cross-chain route needs two different chain IDs');if(!/^\d+$/.test(String(amount)))throw new Error('Amount must be base units');return quoteRoute({fromChain,toChain,fromToken,toToken,fromAmount:amount,fromAddress:account,toAddress:recipient})}