import admin from 'firebase-admin';
import fs from 'node:fs';
import { authenticate } from '../access.js';
import { closedCandles, validateCandles, EXECUTION_TIMEFRAMES } from './data.js';
import { STRATEGIES } from './strategies.js';
import { analyzeOne, fetchPrice, fetchTf } from './index.js';

const ENGINE_VERSION='market-engine-v6',SCAN_LIMIT=18,SCAN_BATCH=3,MAX_GENERATED=10,SCAN_WINDOW_MS=24*60*60*1000,SCAN_DOC='usage';
function getAdmin(){if(admin.apps.length)return admin;const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON,path=process.env.GOOGLE_APPLICATION_CREDENTIALS;if(raw){admin.initializeApp({credential:admin.credential.cert(JSON.parse(raw.trim().replace(/^['"]|['"]$/g,'')))});return admin}if(path&&fs.existsSync(path)){admin.initializeApp({credential:admin.credential.cert(JSON.parse(fs.readFileSync(path,'utf8')))});return admin}throw Object.assign(new Error('Firebase Admin credentials are missing.'),{code:'FIREBASE_ADMIN_CREDENTIALS_MISSING'})}
function toMs(v){if(!v)return 0;if(typeof v.toMillis==='function')return v.toMillis();if(typeof v.toDate==='function')return v.toDate().getTime();if(typeof v==='number')return v;const n=Date.parse(v);return Number.isFinite(n)?n:0}
function json(res,status,payload){res.statusCode=status;res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0');res.end(JSON.stringify(payload))}
async function topSymbols(){const u=new URL('https://api.bybit.com/v5/market/tickers');u.searchParams.set('category','linear');const r=await fetch(u);if(!r.ok)throw new Error('Bybit market scanner unavailable');const b=await r.json();if(b.retCode!==0)throw new Error(b.retMsg||'Bybit market scanner unavailable');return(b.result?.list||[]).filter(x=>/USDT$/.test(x.symbol)&&Number(x.lastPrice)>0&&Number(x.turnover24h)>0).sort((a,b)=>Number(b.turnover24h)-Number(a.turnover24h)).slice(0,SCAN_LIMIT).map(x=>({symbol:x.symbol,turnover24h:Number(x.turnover24h)}))}
async function candlesFor(symbol){const [a,b,c,d,e,f]=await Promise.all([fetchTf('perpetual',symbol,'15m'),fetchTf('perpetual',symbol,'30m'),fetchTf('perpetual',symbol,'1H'),fetchTf('perpetual',symbol,'2H'),fetchTf('perpetual',symbol,'4H'),fetchTf('perpetual',symbol,'1D')]);return{'15m':closedCandles(a,'15m'),'30m':closedCandles(b,'30m'),'1H':closedCandles(c,'1H'),'2H':closedCandles(d,'2H'),'4H':closedCandles(e,'4H'),'1D':closedCandles(f,'1D')}}
function candidateScore(result){if(!result?.trade||!result?.grade)return-1;if(result.direction==='BULLISH'&&!(result.trade.stop<result.trade.entry&&result.trade.target>result.trade.entry))return-1;if(result.direction==='BEARISH'&&!(result.trade.stop>result.trade.entry&&result.trade.target<result.trade.entry))return-1;if(!['A+','A'].includes(result.grade.grade)||Number(result.grade.score)<72)return-1;const rr=Number(result.trade.rr)||0;return result.grade.score*100+Math.min(Math.max(rr,0),6)*8}
function toSetup(market,strategy,result,price){const score=candidateScore(result);if(score<0)return null;const trade=result.trade,bias=result.direction==='BULLISH'?'LONG':'SHORT';return{id:market.symbol+'-'+strategy+'-'+result.tf,symbol:market.symbol.replace(/USDT$/,'/USDT'),providerSymbol:market.symbol,strategy:STRATEGIES[strategy]?.name||strategy,strategyKey:strategy,bias,timeframe:result.tf,grade:result.grade.grade,score:result.grade.score,confidence:result.grade.score,entry:trade.entry,orderType:trade.orderType||'MARKET',marketEntry:trade.marketEntry??price.last,entryReason:trade.entryReason||null,stopLoss:trade.stop,takeProfit:trade.target,rr:Number(trade.rr.toFixed(2)),regime:result.regime,evidence:result.evidence||[],strategyDetails:result[strategy==='TOP_DOWN'?'topDown':strategy==='PULLBACK'?'pullback':strategy==='BREAKOUT'?'breakoutRetest':strategy==='SMC'?'smc':strategy==='MSNR'?'msnr':'crt']||null,layers:result.layers||[],structureDirection:result.structure?.direction||result.direction,liquidity:result.liquidity?.recentSweep?.length||0,source:'Bybit linear perpetuals',rankScore:score}}
async function scanSymbol(market){try{const price=await fetchPrice('perpetual',market.symbol),all=await candlesFor(market.symbol);if(!Object.entries(all).every(([tf,c])=>validateCandles(c,tf).valid))return[];const candidates=[];for(const [strategy] of Object.entries(STRATEGIES))for(const tf of EXECUTION_TIMEFRAMES)try{const result=await analyzeOne('perpetual',market.symbol,strategy,tf,all,price.last),setup=toSetup(market,strategy,result,price);if(setup)candidates.push(setup)}catch{}return candidates.sort((a,b)=>b.rankScore-a.rankScore)}catch{return[]}}
async function scanTopQuality(excludeIds=[]){const markets=await topSymbols(),scanned=await Promise.all(markets.map(scanSymbol)),flat=scanned.flat().filter(x=>!excludeIds.includes(x.id)),bestBySymbol=new Map;for(const setup of flat){const old=bestBySymbol.get(setup.symbol);if(!old||setup.rankScore>old.rankScore)bestBySymbol.set(setup.symbol,setup)}return{generatedAt:new Date().toISOString(),scanUniverse:markets.length,setups:[...bestBySymbol.values()].sort((a,b)=>b.rankScore-a.rankScore).slice(0,SCAN_BATCH),source:'Bybit linear perpetuals'}}
async function recordScannerSignals(uid,setups){if(!Array.isArray(setups)||!setups.length)return;const db=getAdmin().firestore(),collection=db.collection('users').doc(uid).collection('signals'),now=new Date().toISOString();for(const setup of setups){const id=String(setup.id||'').replace(/[^A-Z0-9_-]/gi,'-').slice(0,140);if(!id)continue;const ref=collection.doc('scanner-'+id),existing=await ref.get();if(existing.exists)continue;const orderType=String(setup.orderType||'MARKET').toUpperCase();const direction=setup.bias;const signal={signalId:'SC-'+id,userId:uid,market:'perpetual',symbol:setup.providerSymbol||String(setup.symbol||'').replace('/',''),timeframe:setup.timeframe,strategy:String(setup.strategyKey||setup.strategy||'').toUpperCase(),engineVersion:ENGINE_VERSION,direction,orderType,confidence:Number.isFinite(Number(setup.confidence))?Number(setup.confidence):null,entry:Number(setup.entry),limitEntry:orderType==='LIMIT'?Number(setup.entry):null,stopLoss:Number(setup.stopLoss),takeProfit1:Number(setup.takeProfit),takeProfit2:null,riskReward:'1:'+Number(setup.rr||0).toFixed(2),currentPrice:Number(setup.marketEntry),status:orderType==='LIMIT'?'limit_pending':'watching',result:null,pnlPercent:null,exitPrice:null,closedAt:null,generatedAt:admin.firestore.FieldValue.serverTimestamp(),createdAt:admin.firestore.FieldValue.serverTimestamp(),source:'quality-scanner',scannerSetupId:id,scannerGeneratedAt:now};await ref.set(signal)}}async function deleteScannerSetup(uid,setupId){
  const id=String(setupId||'').trim();
  if(!id)throw Object.assign(new Error('A scanner setup id is required.'),{code:'SCANNER_SETUP_ID_REQUIRED'});
  const db=getAdmin().firestore(),ref=db.collection('users').doc(uid).collection('scanner').doc(SCAN_DOC);
  const signalId='scanner-'+id.replace(/[^A-Z0-9_-]/gi,'-').slice(0,140);
  return db.runTransaction(async tx=>{
    const snap=await tx.get(ref);
    if(!snap.exists)return{removed:false,reason:'NOT_FOUND'};
    const state=snap.data()||{},setups=Array.isArray(state.setups)?state.setups:[],next=setups.filter(x=>String(x?.id||'')!==id);
    const removed=next.length!==setups.length;
    if(removed){
      tx.set(ref,{...state,setups:next,generatedCount:next.length,updatedAt:new Date().toISOString()},{merge:false});
    }
    const signalRef=db.collection('users').doc(uid).collection('signals').doc(signalId);
    const signalSnap=await tx.get(signalRef);
    if(signalSnap.exists)tx.delete(signalRef);
    return{removed,deletedSignal:signalSnap.exists};
  });
}
function emptyState(now=Date.now()){return{engineVersion:ENGINE_VERSION,windowStartedAt:new Date(now).toISOString(),resetAt:new Date(now+SCAN_WINDOW_MS).toISOString(),generatedCount:0,scanCount:0,setups:[],scanState:'idle',lastScanAt:null,scanUniverse:0,source:'Bybit linear perpetuals'}}
function publicState(state,now=Date.now()){const resetAt=toMs(state.resetAt),count=Number(state.generatedCount)||0;return{ok:true,setups:Array.isArray(state.setups)?state.setups:[],generatedCount:count,maxGenerated:MAX_GENERATED,scanBatch:SCAN_BATCH,scanCount:Number(state.scanCount)||0,remainingSlots:Math.max(0,MAX_GENERATED-count),resetAt:state.resetAt||new Date(now+SCAN_WINDOW_MS).toISOString(),windowStartedAt:state.windowStartedAt||null,remainingMs:Math.max(0,resetAt-now),scanUniverse:Number(state.scanUniverse)||0,source:state.source||'Bybit linear perpetuals',status:count>=MAX_GENERATED?'LIMIT_REACHED':'READY'}}
async function readState(uid){const ref=getAdmin().firestore().collection('users').doc(uid).collection('scanner').doc(SCAN_DOC),snap=await ref.get();if(!snap.exists)return publicState(emptyState());const state=snap.data()||{},resetAt=toMs(state.resetAt);if(state.engineVersion!==ENGINE_VERSION){const fresh=emptyState();await ref.set(fresh);return publicState(fresh)}if(resetAt&&Date.now()>=resetAt){const fresh=emptyState();await ref.set(fresh);return publicState(fresh)}return publicState(state)}
async function reserveScan(uid){const db=getAdmin().firestore(),ref=db.collection('users').doc(uid).collection('scanner').doc(SCAN_DOC),now=Date.now();return db.runTransaction(async tx=>{const snap=await tx.get(ref);let state=snap.exists?snap.data()||{}:emptyState(now);if(state.engineVersion!==ENGINE_VERSION||!toMs(state.resetAt)||now>=toMs(state.resetAt))state=emptyState(now);const count=Number(state.generatedCount)||0;if(count>=MAX_GENERATED)return{allowed:false,code:'SCAN_LIMIT_REACHED',state};if(state.scanState==='running'&&now-toMs(state.scanStartedAt)<15*60*1000)return{allowed:false,code:'SCAN_IN_PROGRESS',state};state={...state,scanState:'running',scanStartedAt:new Date(now).toISOString(),updatedAt:new Date(now).toISOString()};tx.set(ref,state,{merge:false});return{allowed:true,state,ref}})}
async function runUserScan(uid){const reservation=await reserveScan(uid);if(!reservation.allowed){if(reservation.code==='SCAN_LIMIT_REACHED')return{...publicState(reservation.state),code:reservation.code,error:'You have generated the maximum 10 scanner setups for this 24-hour window.'};return{...publicState(reservation.state),code:reservation.code,error:'A scanner run is already in progress. Please wait for it to finish.'}}const db=getAdmin().firestore(),ref=reservation.ref;try{const existing=Array.isArray(reservation.state.setups)?reservation.state.setups:[],remaining=MAX_GENERATED-existing.length,result=await scanTopQuality(existing.map(x=>x.id)),additions=result.setups.slice(0,Math.min(SCAN_BATCH,remaining));await recordScannerSignals(uid,additions);const combined=[...existing,...additions].slice(0,MAX_GENERATED),now=Date.now(),next={...reservation.state,setups:combined,generatedCount:combined.length,scanCount:(Number(reservation.state.scanCount)||0)+1,lastScanAt:new Date(now).toISOString(),scanState:'idle',scanUniverse:result.scanUniverse,source:result.source,updatedAt:new Date(now).toISOString()};await ref.set(next,{merge:false});return{...publicState(next,now),generatedNow:additions.length,notice:additions.length?'Scanner added '+additions.length+' top-quality setup'+(additions.length===1?'':'s')+'.':'No new setup cleared the quality threshold on this scan. No inferior trade was added.'}}catch(error){await ref.set({...reservation.state,scanState:'idle',lastError:String(error?.message||error),lastErrorAt:new Date().toISOString(),updatedAt:new Date().toISOString()},{merge:false});throw error}}
export default async function handler(req,res){try{const auth=await authenticate(req);if(req.method==='GET')return json(res,200,await readState(auth.uid));
    if(req.method==='POST')return json(res,200,await runUserScan(auth.uid));
    if(req.method==='DELETE'){
      const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});
      const result=await deleteScannerSetup(auth.uid,body.setupId||body.id);
      return json(res,200,{ok:true,...result});
    }
    return json(res,405,{ok:false,error:'Method not allowed'})}catch(e){const status=e?.code==='AUTH_REQUIRED'||e?.code==='AUTH_INVALID'?401:500;return json(res,status,{ok:false,error:e?.message||'Scanner request failed',code:e?.code||'SCANNER_ERROR'})}}


export { topSymbols, candlesFor, scanSymbol };
