import {getToken,ZERO_ADDRESS} from '../chains/registry.js';

const CHAINS={robinhood:4663,robinhoodTestnet:46630,ethereum:1,base:8453,arbitrum:42161,optimism:10,polygon:137,bsc:56};
const aliases=Object.fromEntries(Object.entries(CHAINS).map(([k,v])=>[k,k]));
export function resolveChain(value){const s=String(value||'').trim().toLowerCase();if(/^\d+$/.test(s))return Number(s);if(aliases[s])return CHAINS[aliases[s]];const hit=Object.keys(CHAINS).find(k=>s.includes(k)||({robinhood:'robinhood',testnet:'robinhoodTestnet',ethereum:'ethereum',eth:'ethereum',base:'base',arbitrum:'arbitrum',arb:'arbitrum',optimism:'optimism',op:'optimism',polygon:'polygon',matic:'polygon',bsc:'bsc','bnb':'bsc'}[k]===s));return hit?CHAINS[hit]:null}
export function parseSend(text){const m=String(text||'').match(/(?:send|transfer)\s+([\d.]+)\s*([A-Za-z0-9_-]+)?\s*(?:to)\s*(0x[a-fA-F0-9]{40})/i);return{amount:m?.[1]||'',asset:m?.[2]||'ETH',address:m?.[3]||''}}
export function parseBridge(text){const s=String(text||'');const m=s.match(/(?:bridge|move|send)\s+([\d.]+)\s*([A-Za-z0-9_-]+)\s+(?:to|onto|from\s+\S+\s+to)\s+([A-Za-z0-9 _-]+?)(?:\s+from\s+([A-Za-z0-9 _-]+))?$/i);if(!m)throw new Error('Use: Bridge 100 USDC to Base');const destination=String(m[3]).trim();const source=String(m[4]||'').trim();const toChain=resolveChain(destination);const fromChain=resolveChain(source);return{amount:m[1],asset:m[2],destination,source,toChain,fromChain}}
export function parseDefi(text){const s=String(text||'').trim();const action=(s.match(/\b(supply|deposit|withdraw|borrow|repay|stake|unstake|claim|lend)\b/i)||[])[1]?.toLowerCase();const m=s.match(/(?:supply|deposit|withdraw|borrow|repay|stake|unstake|lend)\s+([\d.]+)\s*([A-Za-z0-9_-]+)/i);return{action:action||'',amount:m?.[1]||'',asset:m?.[2]||''}}
export function classify(text){const s=String(text||'').toLowerCase();if(/portfolio|balance|holdings/.test(s))return'portfolio';if(/faucet|test eth|testnet gas/.test(s))return'faucet';if(/gas|fee|cost/.test(s))return'gas';if(/bridge|cross.?chain|move .* to (base|ethereum|arbitrum|optimism|polygon|bsc|robinhood)/.test(s))return'bridge';if(/swap|exchange|trade/.test(s))return'swap';if(/supply|deposit|withdraw|borrow|repay|stake|unstake|lend|claim rewards/.test(s))return'defi';if(/nft|erc.?721|erc.?1155|token id/.test(s))return'nft';if(/batch|multiple calls/.test(s))return'batch';if(/approve|allowance/.test(s))return'contract';if(/contract|calldata|call 0x/.test(s))return'contract';if(/send|transfer/.test(s))return'send';return'contract'}
export function tokenFor(chainId,symbol){return getToken(chainId,symbol)||null}
export {ZERO_ADDRESS};