const BASE='https://api.twelvedata.com';
const TF={'1m':'1min','5m':'5min','15m':'15min','30m':'30min','1H':'1h','4H':'4h','1D':'1day','1W':'1week'};
const CACHE=new Map();
const TTL={'1m':15000,'5m':30000,'15m':45000,'30m':60000,'1H':120000,'4H':180000,'1D':300000,'1W':600000,quote:5000,instruments:3600000};
const FOREX=['AUDCAD','AUDCHF','AUDJPY','AUDNZD','AUDUSD','CADCHF','CADJPY','CHFJPY','EURAUD','EURCAD','EURCHF','EURGBP','EURJPY','EURNZD','EURUSD','GBPAUD','GBPCAD','GBPCHF','GBPJPY','GBPNZD','GBPUSD','NZDCAD','NZDCHF','NZDJPY','NZDUSD','USDCAD','USDCHF','USDJPY','USDNOK','USDSEK','USDZAR','USDSGD','EURPLN','EURSEK','EURNOK','EURTRY','GBPPLN','GBPSEK','GBPNOK','NOKSEK','NZDSGD','SGDJPY','CHFSGD','CADSGD','AUDSGD','AUDNOK','AUDSEK','CADNOK','CADSEK','CHFPLN','CHFZAR','EURSGD','GBPZAR','NZDZAR','USDHKD','USDMXN','USDTRY','USDTHB','USDHUF','USDCNH'];
const COMMODITIES=[['XAUUSD','Gold / US Dollar','XAU/USD'],['XAGUSD','Silver / US Dollar','XAG/USD'],['XPTUSD','Platinum / US Dollar','XPT/USD'],['XPDUSD','Palladium / US Dollar','XPD/USD'],['USOIL','WTI Crude Oil','WTI/USD'],['UKOIL','Brent Crude Oil','BRENT/USD'],['NATGAS','Natural Gas','NATGAS/USD'],['COPPER','Copper','HG1'],['CORN','Corn','CORN/USD'],['WHEAT','Wheat','WHEAT/USD'],['SOYBEAN','Soybeans','SOYBEAN/USD'],['COFFEE','Coffee','COFFEE/USD'],['SUGAR','Sugar #11','SUGAR/USD'],['COTTON','Cotton','COTTON/USD'],['COCOA','Cocoa','COCOA/USD']];
const INDICES=[['US500','S&P 500','SPX'],['US100','Nasdaq 100','NDX'],['US30','Dow Jones 30','DJI'],['US2000','Russell 2000','RUT'],['UK100','FTSE 100','FTSE'],['GER40','DAX 40','DAX'],['FRA40','CAC 40','CAC'],['JP225','Nikkei 225','N225'],['HK50','Hang Seng','HSI'],['EU50','Euro Stoxx 50','STOXX50E'],['AUS200','ASX 200','ASX'],['VIX','VIX','VIX'],['DXY','US Dollar Index','DXY']];
function apiKey(){const k=process.env.TWELVE_DATA_API_KEY||process.env.TWELVE_DATA_KEY;if(!k)throw Object.assign(new Error('Twelve Data API key is not configured.'),{code:'TWELVE_DATA_NOT_CONFIGURED'});return k}
function cacheGet(k){const x=CACHE.get(k);if(!x||Date.now()-x.time>x.ttl)return null;return x.value}
function cacheSet(k,value,ttl){CACHE.set(k,{time:Date.now(),ttl,value});return value}
async function request(endpoint,params,ttl,keyName){const cacheKey=keyName||endpoint+'?'+new URLSearchParams(params);const hit=cacheGet(cacheKey);if(hit)return hit;const u=new URL(BASE+endpoint);for(const [k,v] of Object.entries({...params,apikey:apiKey()}))u.searchParams.set(k,v);const r=await fetch(u,{headers:{Accept:'application/json'},cache:'no-store'});const body=await r.json().catch(()=>null);if(!r.ok||body?.status==='error'||body?.code)throw new Error(body?.message||body?.error||'Twelve Data request failed');return cacheSet(cacheKey,body,ttl)}
function providerSymbol(symbol,market){if(market==='forex'){const s=String(symbol).replace('/','').toUpperCase();return s.slice(0,3)+'/'+s.slice(3,6)}const row=(market==='commodities'?COMMODITIES:INDICES).find(x=>x[0]===symbol);return row?.[2]||symbol}
function instruments(market){if(market==='forex')return FOREX.map(symbol=>({symbol,name:symbol,type:'FOREX',providerSymbol:providerSymbol(symbol,market)}));const rows=market==='commodities'?COMMODITIES:INDICES;return rows.map(([symbol,name,providerSymbol])=>({symbol,name,type:market==='commodities'?'COMMODITY':'INDEX',providerSymbol}))}
export function twelveDataInstruments(market){return cacheSet('instruments:'+market,instruments(market),TTL.instruments)}
function normalize(values){return (values||[]).map(v=>[Date.parse(String(v.datetime).replace(' ','T')+'Z'),+v.open,+v.high,+v.low,+v.close,+(v.volume||0)]).filter(x=>Number.isFinite(x[0])&&x.slice(1,5).every(Number.isFinite)).sort((a,b)=>a[0]-b[0])}
export async function twelveDataCandles(symbol,timeframe,market){const ps=providerSymbol(symbol,market);const body=await request('/time_series',{symbol:ps,interval:TF[timeframe],outputsize:'350',order:'ASC',timezone:'UTC'},TTL[timeframe],'ts:'+market+':'+symbol+':'+timeframe);const rows=normalize(body.values);if(rows.length<80)throw new Error('Twelve Data returned insufficient candles for '+symbol+' '+timeframe);return{rows,meta:body.meta||{},instrument:{symbol,name:body.meta?.name||symbol,providerSymbol:ps}}}
export async function twelveDataPrice(symbol,market){const ps=providerSymbol(symbol,market);const body=await request('/quote',{symbol:ps,interval:'1min',timezone:'UTC'},TTL.quote,'quote:'+market+':'+symbol);const mid=+body.close||+body.price||+body.last;if(!Number.isFinite(mid)||mid<=0)throw Object.assign(new Error('Twelve Data returned no live price for '+symbol),{code:'MARKET_DATA_PRICE_UNAVAILABLE'});const timestamp=Number(body.timestamp)*1000||Date.parse(String(body.datetime||'').replace(' ','T')+'Z');if(!Number.isFinite(timestamp))throw Object.assign(new Error('Twelve Data returned no quote timestamp for '+symbol),{code:'MARKET_DATA_PRICE_STALE'});const age=Date.now()-timestamp;if(age<-30000||age>120000)throw Object.assign(new Error('Twelve Data quote is stale for '+symbol),{code:'MARKET_DATA_PRICE_STALE'});return{bid:mid,ask:mid,mid,time:new Date(timestamp).toISOString(),tradeable:true,spread:0,marketState:'open',stale:false,instrument:{name:body.name||symbol,providerSymbol:ps}}}
