const BASE='https://query1.finance.yahoo.com/v8/finance/chart/';
const TF={ '1m':'1m','5m':'5m','15m':'15m','30m':'30m','1H':'1h','4H':'1h','1D':'1d','1W':'1wk' };
const RANGE={ '1m':'5d','5m':'1mo','15m':'1mo','30m':'1mo','1H':'2y','4H':'2y','1D':'5y','1W':'10y' };
const FOREX=['AUDCAD','AUDCHF','AUDJPY','AUDNZD','AUDUSD','CADCHF','CADJPY','CHFJPY','EURAUD','EURCAD','EURCHF','EURGBP','EURJPY','EURNZD','EURUSD','GBPAUD','GBPCAD','GBPCHF','GBPJPY','GBPNZD','GBPUSD','NZDCAD','NZDCHF','NZDJPY','NZDUSD','USDCAD','USDCHF','USDJPY','USDNOK','USDSEK','USDZAR','USDSGD','EURPLN','EURSEK','EURNOK','EURTRY','GBPPLN','GBPSEK','GBPNOK','NOKSEK','NZDSGD','SGDJPY','CHFSGD','CADSGD','AUDSGD','AUDNOK','AUDSEK','CADNOK','CADSEK','CHFPLN','CHFZAR','EURSGD','GBPZAR','NZDZAR','USDHKD','USDMXN','USDTRY','USDTHB','USDHUF','USDCNH'];
const COMMODITIES=[['XAUUSD','Gold / US Dollar','GC=F'],['XAGUSD','Silver / US Dollar','SI=F'],['XPTUSD','Platinum / US Dollar','PL=F'],['XPDUSD','Palladium / US Dollar','PA=F'],['USOIL','WTI Crude Oil','CL=F'],['UKOIL','Brent Crude Oil','BZ=F'],['NATGAS','Natural Gas','NG=F'],['COPPER','Copper','HG=F'],['CORN','Corn','ZC=F'],['WHEAT','Wheat','ZW=F'],['SOYBEAN','Soybeans','ZS=F'],['COFFEE','Coffee','KC=F'],['SUGAR','Sugar #11','SB=F'],['COTTON','Cotton','CT=F'],['COCOA','Cocoa','CC=F']];
const INDICES=[['US500','S&P 500','^GSPC'],['US100','Nasdaq 100','^NDX'],['US30','Dow Jones 30','^DJI'],['US2000','Russell 2000','^RUT'],['UK100','FTSE 100','^FTSE'],['GER40','DAX 40','^GDAXI'],['FRA40','CAC 40','^FCHI'],['JP225','Nikkei 225','^N225'],['HK50','Hang Seng','^HSI'],['EU50','Euro Stoxx 50','^STOXX50E'],['AUS200','ASX 200','^AXJO'],['VIX','VIX','^VIX'],['DXY','US Dollar Index','DX-Y.NYB']];
function yahooSymbol(symbol,market){if(market==='forex')return String(symbol).replace('/','')+'=X';const row=(market==='commodities'?COMMODITIES:INDICES).find(x=>x[0]===symbol);return row?.[2]||String(symbol)}
function yahooInstruments(market){if(market==='forex')return FOREX.map(symbol=>({symbol,name:symbol,type:'FOREX',providerSymbol:yahooSymbol(symbol,market)}));const rows=market==='commodities'?COMMODITIES:INDICES;return rows.map(([symbol,name,providerSymbol])=>({symbol,name,type:market==='commodities'?'COMMODITY':'INDEX',providerSymbol}))}
async function request(providerSymbol,timeframe){const interval=TF[timeframe],range=RANGE[timeframe];if(!interval||!range)throw new Error('Unsupported timeframe');const url=BASE+encodeURIComponent(providerSymbol)+'?interval='+encodeURIComponent(interval)+'&range='+encodeURIComponent(range)+'&events=history&includeAdjustedClose=true';const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'KitSetups/1.0'},cache:'no-store'});const body=await r.json().catch(()=>null);if(!r.ok||body?.chart?.error)throw new Error(body?.chart?.error?.description||`Yahoo market data request failed (${r.status})`);const result=body?.chart?.result?.[0];if(!result?.timestamp?.length)throw new Error(`Yahoo returned no candles for ${providerSymbol}`);const q=result.indicators?.quote?.[0]||{};const rows=result.timestamp.map((t,i)=>[Number(t)*1000,Number(q.open?.[i]),Number(q.high?.[i]),Number(q.low?.[i]),Number(q.close?.[i]),Number(q.volume?.[i]||0)]).filter(x=>[x[0],x[1],x[2],x[3],x[4]].every(Number.isFinite)).sort((a,b)=>a[0]-b[0]);if(rows.length<60)throw new Error(`Yahoo returned insufficient candles for ${providerSymbol} ${timeframe}`);return {rows,meta:result.meta||{}}}
function aggregate4h(rows){const buckets=new Map();for(const r of rows){const d=new Date(r[0]);const bucket=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),Math.floor(d.getUTCHours()/4)*4);const x=buckets.get(bucket);if(!x)buckets.set(bucket,[bucket,r[1],r[2],r[3],r[4],r[5]]);else{x[2]=Math.max(x[2],r[2]);x[3]=Math.min(x[3],r[3]);x[4]=r[4];x[5]+=r[5]}}return [...buckets.values()].sort((a,b)=>a[0]-b[0])}
export async function yahooCandles(symbol,timeframe,market){let instrument=yahooInstruments(market).find(x=>x.symbol===symbol)||{symbol,name:symbol,type:market==='commodities'?'COMMODITY':'INDEX',providerSymbol:yahooSymbol(symbol,market)};let rows;try{rows=(await request(instrument.providerSymbol,timeframe)).rows}catch(error){const fallback=market==='commodities'&&symbol==='XAUUSD'?'GC=F':market==='commodities'&&symbol==='XAGUSD'?'SI=F':null;if(!fallback||fallback===instrument.providerSymbol)throw error;rows=(await request(fallback,timeframe)).rows;instrument={...instrument,providerSymbol:fallback,sourceInstrument:fallback,sourceType:'FUTURES_FALLBACK'}}if(timeframe==='4H')rows=aggregate4h(rows);return {instrument,rows}}
export async function yahooPrice(symbol,market){const instrument=yahooInstruments(market).find(x=>x.symbol===symbol)||{symbol,name:symbol,providerSymbol:yahooSymbol(symbol,market)};let packet;try{packet=await request(instrument.providerSymbol,'1m')}catch(error){const fallback=market==='commodities'&&symbol==='XAUUSD'?'GC=F':market==='commodities'&&symbol==='XAGUSD'?'SI=F':null;if(!fallback||fallback===instrument.providerSymbol)throw error;packet=await request(fallback,'1m')}const rows=packet.rows,meta=packet.meta||{},last=rows.at(-1);const price=Number(meta.regularMarketPrice);const quoteTime=Number(meta.regularMarketTime)*1000;const mid=Number.isFinite(price)&&price>0?price:last?.[4];const time=Number.isFinite(quoteTime)&&quoteTime>0?new Date(quoteTime).toISOString():new Date(last?.[0]||0).toISOString();if(!Number.isFinite(mid)||mid<=0||!last)throw Object.assign(new Error('Yahoo live price is unavailable'),{code:'MARKET_DATA_PRICE_UNAVAILABLE'});return {instrument,bid:mid,ask:mid,mid,time,tradeable:true,spread:0,marketState:meta.marketState||'open',stale:false}}
export { yahooInstruments };
