import {isEvmChain} from '../chains/registry.js';

const win=()=>typeof window!=='undefined'?window:null;
const weiToUnit=(v,d=18)=>{try{const n=BigInt(v||0),p=10n**BigInt(d);return `${n/p}.${String(n%p).padStart(d,'0')}`.replace(/\.0+$/,'').replace(/(\.[0-9]*?)0+$/,'$1')}catch{return '0'}};

export const NATIVE_ADAPTERS={
  solana:{name:'Solana Wallet Standard',namespace:'solana',detect:w=>w?.solana||w?.phantom?.solana,connect:async w=>{const p=w?.solana||w?.phantom?.solana;if(!p)throw new Error('Install or connect a Solana wallet such as Phantom or Solflare.');const r=await p.connect();return r?.publicKey?.toString()||p.publicKey?.toString()||''},balance:async(c,a)=>{const r=await fetch(c.rpc,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'getBalance',params:[a]})});const j=await r.json();return weiToUnit(j?.result?.value,9)},send:async(w,to,amount,c)=>{const p=w?.solana||w?.phantom?.solana;if(!p)throw new Error('Solana wallet not detected.');const {Connection,PublicKey,SystemProgram,Transaction}=await import('@solana/web3.js');const from=new PublicKey(p.publicKey?.toString());const recipient=new PublicKey(to);const lamports=Math.round(Number(amount)*1e9);if(!Number.isSafeInteger(lamports)||lamports<=0)throw new Error('Invalid SOL amount.');const tx=new Transaction().add(SystemProgram.transfer({fromPubkey:from,toPubkey:recipient,lamports}));const connection=new Connection(c.rpc,'confirmed');const {blockhash}=await connection.getLatestBlockhash('confirmed');tx.recentBlockhash=blockhash;tx.feePayer=from;const signed=await p.signTransaction(tx);const sig=await connection.sendRawTransaction(signed.serialize(),{skipPreflight:false});await connection.confirmTransaction(sig,'confirmed');return sig}},
  bitcoin:{name:'Bitcoin wallet',namespace:'bip122',detect:w=>w?.unisat||w?.okxwallet?.bitcoin,connect:async w=>{const p=w?.unisat||w?.okxwallet?.bitcoin;if(!p)throw new Error('Install a Bitcoin wallet such as UniSat or OKX Wallet.');const a=await p.requestAccounts();return a?.[0]||''},balance:async(c,a)=>{try{const r=await fetch(`https://mempool.space/api/address/${encodeURIComponent(a)}`);const j=await r.json();const v=(j?.chain_stats?.funded_txo_sum||0)-(j?.chain_stats?.spent_txo_sum||0);return weiToUnit(v,8)}catch{return '—'}},send:async(w,to,amount)=>{const p=w?.unisat||w?.okxwallet?.bitcoin;if(!p?.sendBitcoin)throw new Error('Connected Bitcoin wallet does not expose sendBitcoin.');const sats=Math.round(Number(amount)*1e8);if(!Number.isSafeInteger(sats)||sats<=0)throw new Error('Invalid BTC amount.');return p.sendBitcoin(to,sats)}},
  tron:{name:'TRON wallet',namespace:'tron',detect:w=>w?.tronWeb||w?.tronLink,connect:async w=>{const t=w?.tronWeb;if(!t?.defaultAddress?.base58)throw new Error('Install or unlock TronLink.');return t.defaultAddress.base58},balance:async(w,a)=>{const t=w?.tronWeb;if(!t)return '0';return weiToUnit(await t.trx.getBalance(a),6)},send:async(w,to,amount)=>{const t=w?.tronWeb;if(!t)throw new Error('TronWeb wallet not detected.');const tx=await t.transactionBuilder.sendTrx(to,Math.round(Number(amount)*1e6),t.defaultAddress.base58);const signed=await t.trx.sign(tx);return t.trx.sendRawTransaction(signed)}},
  xrp:{name:'XRP wallet',namespace:'xrpl',detect:w=>w?.xumm||w?.Xaman,connect:async()=>{throw new Error('XRP Ledger wallet signing requires a Xaman/XRPL adapter session; no private keys are handled by KitAgent.')},balance:async()=> '—',send:async()=>{throw new Error('XRP Ledger adapter requires an approved wallet session.') }},
  stellar:{name:'Stellar wallet',namespace:'stellar',detect:w=>w?.freighterApi||w?.freighter,connect:async w=>{const f=w?.freighterApi||w?.freighter;if(!f?.getAddress)throw new Error('Install Freighter for Stellar.');const r=await f.getAddress();return r?.address||r||''},balance:async()=> '—',send:async()=>{throw new Error('Stellar transaction signing requires the Freighter adapter session.') }},
  cosmos:{name:'Cosmos wallet',namespace:'cosmos',detect:w=>w?.keplr,connect:async w=>{if(!w?.keplr)throw new Error('Install Keplr for Cosmos.');await w.keplr.enable('cosmoshub-4');const k=await w.keplr.getKey('cosmoshub-4');return k?.bech32Address||''},balance:async()=> '—',send:async()=>{throw new Error('Cosmos signing requires the chain-specific Keplr signer and protobuf transaction builder.') }},
  polkadot:{name:'Polkadot extension',namespace:'polkadot',detect:w=>w?.polkadot,connect:async w=>{if(!w?.polkadot?.enable)throw new Error('Install a Polkadot-compatible browser extension.');const e=await w.polkadot.enable('KitAgent');const a=await e.accounts.get();return a?.[0]?.address||''},balance:async()=> '—',send:async()=>{throw new Error('Polkadot signing requires the extension signer and SCALE transaction builder.') }},
  aptos:{name:'Aptos wallet standard',namespace:'aptos',detect:w=>w?.aptos||w?.petra,connect:async w=>{const p=w?.aptos||w?.petra;if(!p?.connect)throw new Error('Install Petra or another Aptos wallet.');const r=await p.connect();return r?.address||p.account?.address||''},balance:async()=> '—',send:async(w,to,amount)=>{const p=w?.aptos||w?.petra;if(!p?.signAndSubmitTransaction)throw new Error('This Aptos wallet does not expose signAndSubmitTransaction.');const octas=BigInt(Math.round(Number(amount)*1e8)).toString();return p.signAndSubmitTransaction({function:'0x1::aptos_account::transfer',type_arguments:[],arguments:[to,octas]})}},
  sui:{name:'Sui wallet standard',namespace:'sui',detect:w=>w?.sui||w?.suiWallet,connect:async w=>{const p=w?.sui||w?.suiWallet;if(!p?.connect)throw new Error('Install a Sui wallet.');const r=await p.connect();return r?.accounts?.[0]?.address||r?.address||''},balance:async(c,a)=>{try{const r=await fetch(c.rpc,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'suix_getBalance',params:[a]})});const j=await r.json();return weiToUnit(j?.result?.totalBalance,9)}catch{return '—'}},send:async()=>{throw new Error('Sui signing requires the wallet-standard programmable transaction builder.') }},
  near:{name:'NEAR wallet',namespace:'near',detect:w=>w?.nearWallet,connect:async()=>{throw new Error('NEAR requires a wallet-selector session; no private keys are handled by KitAgent.')},balance:async()=> '—',send:async()=>{throw new Error('NEAR wallet-selector adapter required.') }},
  cardano:{name:'Cardano CIP-30 wallet',namespace:'cardano',detect:w=>w?.cardano,connect:async w=>{const wallets=w?.cardano||{};const key=Object.keys(wallets)[0];if(!key||!wallets[key]?.enable)throw new Error('Install a CIP-30 Cardano wallet such as Eternl or Lace.');const api=await wallets[key].enable();return api?.getChangeAddress?await api.getChangeAddress():''},balance:async()=> '—',send:async()=>{throw new Error('Cardano signing requires CIP-30 transaction/CBOR construction.') }},
};

export function adapterFor(chain){if(!chain||isEvmChain(chain))return null;return NATIVE_ADAPTERS[chain.key]||NATIVE_ADAPTERS[chain.namespace]||null}
export function adapterStatus(chain){const a=adapterFor(chain);if(!a)return {available:false,label:'Adapter unavailable',reason:'No native adapter is registered for this namespace.'};const w=win();return {available:!!a.detect(w),label:a.name,namespace:a.namespace,connected:!!a.detect(w)} }
export async function connectNative(chain){const a=adapterFor(chain);if(!a)throw new Error(`${chain?.name||'Network'} does not have a native wallet adapter yet.`);return a.connect(win())}
export async function nativeBalance(chain,address){const a=adapterFor(chain);if(!a?.balance)throw new Error(`No balance adapter for ${chain?.name||'network'}`);return a.balance(win(),address,chain)}
export async function sendNative(chain,to,amount){const a=adapterFor(chain);if(!a)throw new Error(`No native transaction adapter for ${chain?.name||'network'}`);return a.send(win(),to,amount,chain)}
export const supportedNativeNamespaces=()=>[...new Set(Object.values(NATIVE_ADAPTERS).map(a=>a.namespace))];
