import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3, Copy, KeyRound, Laptop, LockKeyhole, RefreshCw, ShieldCheck, Smartphone, Sparkles } from 'lucide-react';

function countdown(target) { const ms=Math.max(0,new Date(target).getTime()-Date.now()); return { days:Math.floor(ms/86400000), hours:Math.floor(ms/3600000)%24, minutes:Math.floor(ms/60000)%60, seconds:Math.floor(ms/1000)%60, ms }; }

export default function ProfilePage({ userData, access, updateUser, trialEndsAt }) {
 const [now,setNow]=useState(Date.now()); const [copied,setCopied]=useState(false);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 const trial=countdown(trialEndsAt); const premiumUntil=userData.premiumUntil ? countdown(userData.premiumUntil) : null;
 const activeUntil=access==='premium' ? premiumUntil : trial;
 const trialPct=useMemo(()=>Math.min(100,Math.max(0,(trial.ms/(3*86400000))*100)),[trial.ms,now]);
 const activateDemo=()=>updateUser({premiumUntil:new Date(Date.now()+30*86400000).toISOString()});
 const copyAddress=async()=>{try{await navigator.clipboard.writeText(userData.walletAddress||'');setCopied(true);setTimeout(()=>setCopied(false),1000)}catch{}};
 return <div className="content-wrap"><section className="page-heading"><div><span className="eyebrow">ACCOUNT & ACCESS</span><h1>Profile</h1><p>Your subscription, device binding and trading preferences.</p></div><span className={`access-pill ${access}`}>{access==='premium'?'PREMIUM':access==='trial'?'3-DAY TRIAL':'TRIAL EXPIRED'}</span></section>
 <section className={`subscription-hero ${access}`}><div className="subscription-icon"><Sparkles/></div><div className="subscription-copy"><span className="eyebrow">{access==='premium'?'PREMIUM MEMBERSHIP':'FREE ACCESS'}</span><h2>{access==='premium'?'Premium is active':'Your KitAgent trial'}</h2><p>{access==='premium'?'Unlimited terminal and analysis access for this billing period.':'Your free trial starts at registration and runs for exactly 72 hours.'}</p></div><div className="subscription-clock"><span>{access==='premium'?'EXPIRES IN':'TRIAL REMAINING'}</span><strong>{activeUntil ? `${activeUntil.days}d ${String(activeUntil.hours).padStart(2,'0')}h ${String(activeUntil.minutes).padStart(2,'0')}m` : 'Expired'}</strong><small>{activeUntil ? `${String(activeUntil.seconds).padStart(2,'0')} seconds` : 'Upgrade required'}</small></div></section>
 <div className="progress-track"><span style={{width:`${access==='premium'?100:trialPct}%`}}/></div>
 <div className="profile-grid"><section className="panel"><div className="section-title"><div><h3>Account</h3><p>Identity and connected wallet.</p></div><ShieldCheck size={19}/></div><div className="identity"><div className="avatar-large">K</div><div><strong>KitAgent member</strong><span>Account ID {userData.id}</span></div></div><div className="info-rows"><Info label="Registered" value={new Date(userData.registeredAt).toLocaleString()}/><Info label="Wallet" value={userData.walletAddress || 'Disconnected'}/><Info label="Device binding" value="1 account / 1 device"/><Info label="Device ID" value={`${userData.deviceId.slice(0,10)}…`} /></div>{userData.walletAddress&&<button className="secondary-btn full" onClick={copyAddress}><Copy size={15}/>{copied?'Copied':'Copy wallet address'}</button>}</section>
 <section className="panel"><div className="section-title"><div><h3>Plans</h3><p>Simple access, no hidden entitlement flags.</p></div><Clock3 size={19}/></div><div className="plan-card trial-plan"><div><strong>Free trial</strong><span>72 hours from registration</span></div><b>{access==='trial'?'ACTIVE':'USED'}</b></div><div className="plan-card premium-plan"><div><strong>Premium</strong><span>$20 · 30 days</span></div><b>{access==='premium'?'ACTIVE':'LOCKED'}</b></div><button className="primary-btn full" onClick={activateDemo}><Sparkles size={16}/> Activate Premium demo · $20 / 30 days</button><p className="tiny-note">Demo activation is local UI state only. Production billing must be verified server-side before granting premium.</p></section></div>
 <div className="profile-grid"><section className="panel"><div className="section-title"><div><h3>Trading guardrails</h3><p>Conservative defaults are enforced by the product design.</p></div><LockKeyhole size={19}/></div><div className="settings-grid"><Setting label="Maximum risk / trade" value="1.5%"/><Setting label="Maximum trade size" value="$1,000"/><Setting label="Target risk / reward" value="2.5:1+"/><Setting label="Execution" value="Wallet confirmation"/></div></section><section className="panel"><div className="section-title"><div><h3>Security</h3><p>Secrets stay out of the browser.</p></div><KeyRound size={19}/></div><div className="security-list"><Security icon={Laptop} title="Device binding" text="One account is associated with this browser/device record."/><Security icon={Smartphone} title="Wallet-only signing" text="KitAgent does not store private keys or seed phrases."/><Security icon={RefreshCw} title="API rotation" text="Production API credentials should be hashed, scoped and rotatable server-side."/></div></div></section>
 <section className="panel note-panel"><CheckCircle2 size={18}/><div><strong>Security boundary</strong><p>Frontend storage is only a demo shell. Production account limits, trial expiry, billing, device enforcement and transaction authorization must be verified on a trusted server. VPN/proxy detection can add abuse signals, but no browser can guarantee perfect physical-device identity.</p></div></section>
 </div>;
}
function Info({label,value}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Setting({label,value}){return <div className="setting"><span>{label}</span><strong>{value}</strong></div>}
function Security({icon:Icon,title,text}){return <div className="security-row"><span className="security-icon"><Icon size={16}/></span><div><strong>{title}</strong><p>{text}</p></div></div>}
