import { useEffect, useState } from 'react';
import { addDoc, collection, doc, onSnapshot, serverTimestamp } from 'firebase/firestore';
import { Check, Copy, KeyRound, LoaderCircle, LogOut, ShieldCheck, Wallet, Zap } from 'lucide-react';
import { signOut } from 'firebase/auth';
import { auth, db } from './firebase.js';

const DAY=86400000;
export default function AccountPage({user,wallet,connectWallet}){
 const [profile,setProfile]=useState(null),[verification,setVerification]=useState(null),[message,setMessage]=useState(''),[hash,setHash]=useState(''),[copied,setCopied]=useState(false),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 useEffect(()=>{if(!db||!user?.uid)return;const uid=user.uid;return onSnapshot(doc(db,'users',uid),s=>{if(auth?.currentUser?.uid!==uid)return;setProfile(s.exists()?s.data():null)},e=>{if(auth?.currentUser?.uid===uid)setMessage(e?.message||'Profile sync is temporarily unavailable.')});},[user?.uid]);
 useEffect(()=>{if(!db||!user?.uid)return;const uid=user.uid;return onSnapshot(collection(db,'users',uid,'paymentVerifications'),s=>{if(auth?.currentUser?.uid!==uid)return;const a=s.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>timestampValue(b.createdAt)-timestampValue(a.createdAt));setVerification(a[0]||null)},e=>{if(auth?.currentUser?.uid===uid)setMessage(e?.message||'Payment verification sync is temporarily unavailable.')});},[user?.uid]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 const d=profile||{},sub=d.subscription||{},usage=d.monthlyUsage||{},api=d.api||{},name=d.displayName||user?.displayName||'KitAgent member',email=d.email||user?.email||'Firebase account',photo=d.photoURL||user?.photoURL||'',plan=String(d.plan||'free').toLowerCase();
 const trialStart=toMs(d.trialStartedAt),trialEnd=toMs(d.trialEndsAt),subscriptionEnd=toMs(d.subscriptionEndsAt);const trialTotal=Math.max(DAY*3,trialEnd-trialStart||DAY*3),trialRemaining=Math.max(0,trialEnd-now),trialActive=plan!=='premium'&&trialEnd>now,trialProgress=trialStart&&trialEnd?Math.min(100,Math.max(0,((now-trialStart)/trialTotal)*100)):0;const premiumActive=plan==='premium'&&(!subscriptionEnd||subscriptionEnd>now),premiumRemaining=Math.max(0,subscriptionEnd-now),premiumProgress=subscriptionEnd?Math.min(100,Math.max(0,1-premiumRemaining/(Number(sub.accessDays)||30)*DAY)):100;const walletAddress=wallet||d.walletAddress||'',paymentAddress=sub.paymentAddress||'';
 const copy=async()=>{try{await navigator.clipboard?.writeText(paymentAddress);setCopied(true);setTimeout(()=>setCopied(false),1400)}catch{setMessage('Copy is unavailable in this browser.')}};
 const verify=async()=>{if(!db||!user?.uid||hash.trim().length<8)return setMessage('Enter a valid transaction hash first.');setBusy(true);setMessage('');try{await addDoc(collection(db,'users',user.uid,'paymentVerifications'),{uid:user.uid,transactionHash:hash.trim(),asset:String(sub.paymentAsset||''),network:String(sub.paymentNetwork||''),amount:Number(sub.price)||0,currency:String(sub.currency||'USD'),status:'pending',createdAt:serverTimestamp()});setHash('');setMessage('Transaction submitted for review.')}catch(e){setMessage(e?.message||'Verification request could not be submitted.')}finally{setBusy(false)}};
 const logout=async()=>{setMessage('');try{await signOut(auth)}catch(e){console.error('KitAgent logout failed:',e);setMessage('Unable to sign out right now. Check your connection and try again.')}};
 return <div className="account-page">
  <section className="account-identity"><div className="account-avatar">{photo?<img src={photo} alt=""/>:<span>{initials(name)}</span>}</div><div className="account-name-block"><div className="account-name-row"><h2>{name}</h2><span className="account-active">{premiumActive?'PREMIUM':'ACTIVE'}</span></div><p>{email}</p></div><div className="account-live-state"><i/>{premiumActive?'PREMIUM ACTIVE':trialActive?'TRIAL ACTIVE':'ACCESS EXPIRED'}</div></section>
  <div className="account-section-label">ACCESS</div>
  <section className={`subscription-card free-plan ${trialActive?'trial-live':'trial-ended'}`}><div className="subscription-topline"><div><span className="subscription-label">FREE ACCESS</span><div className="plan-name-row"><h2>3 day trial</h2><span>{trialActive?'RUNNING':'ENDED'}</span></div></div><div className="remaining-block"><span className="subscription-label">REMAINING</span><strong>{trialActive?formatDuration(trialRemaining):'0D 00:00:00'}</strong></div></div><div className="trial-progress-meta"><span>Trial progress</span><b>{trialActive?`${Math.round(trialProgress)}% used`:'100% used'}</b></div><div className="usage-track trial-track"><i style={{width:`${trialProgress}%`}}/></div><div className="trial-dates"><span>{formatDate(trialStart)}</span><span>{formatDate(trialEnd)}</span></div></section>
  <section className={`subscription-card premium-plan ${premiumActive?'is-current':''}`}><div className="premium-header"><div className="premium-mark"><Zap size={16}/></div><div className="premium-copy"><h2>{sub.name||'Premium'}</h2><p>{Array.isArray(sub.features)?sub.features.join(' · '):'Unlimited setups · Live intelligence'}</p></div><div className="premium-price"><strong>{formatMoney(sub.price,sub.currency)||'$30'}</strong><span>/ 30 DAYS</span></div></div><div className="premium-stats"><div><strong>∞</strong><span>SETUPS</span></div><div><strong>LIVE</strong><span>INTELLIGENCE</span></div><div><strong>{sub.accessDays||30}D</strong><span>ACCESS</span></div></div>{premiumActive&&subscriptionEnd?<div className="subscription-live"><div><span>SUBSCRIPTION ACTIVE</span><b>{formatDuration(premiumRemaining)} remaining</b></div><div className="usage-track"><i style={{width:`${premiumProgress*100}%`}}/></div></div>:<div className="payment-panel"><div className="payment-heading"><span>PAY WITH {String(sub.paymentAsset||'USDT').toUpperCase()}</span><b>{String(sub.paymentNetwork||'BNB CHAIN').toUpperCase()}</b></div><div className={`payment-address ${paymentAddress?'':'is-empty'}`} onClick={paymentAddress?copy:undefined}><span>{paymentAddress||'Payment address not configured'}</span>{paymentAddress&&<button type="button" onClick={e=>{e.stopPropagation();copy()}}><Copy size={13}/></button>}</div><div className="payment-input-wrap"><span>TRANSACTION HASH</span><input value={hash} onChange={e=>{setHash(e.target.value);setMessage('')}} placeholder="Paste transaction hash"/></div><button className="verify-payment-btn" type="button" onClick={verify} disabled={busy||!paymentAddress||verification?.status==='pending'}>{busy?<LoaderCircle className="spin" size={14}/>:<ShieldCheck size={14}/>} {busy?'Submitting…':verification?.status==='pending'?'Verification pending':'Payment verification'}</button>{(copied||message||verification)&&<div className="payment-feedback"><Check size={12}/>{copied?'Payment address copied':message||`Verification: ${verification.status}.`}</div>}</div>}</section>
  <div className="account-section-label">ACCOUNT SERVICES</div><section className="account-tools"><div className="tool-card"><div className="tool-icon"><KeyRound size={16}/></div><div><span className="tool-kicker">DEVELOPER ACCESS</span><h3>API</h3><p>{api.status==='active'?'API access is enabled.':'Programmatic access is being prepared.'}</p></div><span className="coming-soon">{api.status==='active'?'ACTIVE':'COMING SOON'}</span></div><div className="tool-card"><div className="tool-icon"><Wallet size={16}/></div><div><span className="tool-kicker">CONNECTED WALLET</span><h3>{walletAddress?shortAddress(walletAddress):'No wallet connected'}</h3><p>Non-custodial wallet connection.</p></div><button className="wallet-action" type="button" onClick={connectWallet}>{walletAddress?'Connected':'Connect'}</button></div></section>
  <button className="account-logout" type="button" onClick={logout}><LogOut size={14}/> Log out</button>
 </div>;
}
function timestampValue(v){if(!v)return 0;if(typeof v.toMillis==='function')return v.toMillis();return new Date(v).getTime()||0}function toMs(v){if(!v)return 0;if(typeof v.toMillis==='function')return v.toMillis();if(typeof v.toDate==='function')return v.toDate().getTime();return new Date(v).getTime()||0}function formatDuration(ms){const s=Math.max(0,Math.floor(ms/1000)),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),x=s%60;return `${d}D ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}function formatDate(ms){return ms?new Date(ms).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—'}function formatMoney(v,c='USD'){const n=Number(v);if(!Number.isFinite(n))return '';try{return new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:2}).format(n)}catch{return `${c} ${n}`}}function initials(v){return String(v||'K').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'K'}function shortAddress(v){return v?`${v.slice(0,6)}…${v.slice(-4)}`:'Not connected'}