import { useEffect, useState } from 'react';
import { ArrowLeft, Bell, Check, ChevronRight, Copy, Edit3, Flame, Headphones, LoaderCircle, LogOut, Save, ShieldCheck, Trash2, UserRound, Users, WalletCards, X } from 'lucide-react';
import { signOut, updateProfile } from 'firebase/auth';
import { doc, onSnapshot, setDoc } from 'firebase/firestore';
import { auth, db } from './firebase.js';
import AffiliatePanel from './AffiliatePanel.jsx';
import LiveSupportPanel from './LiveSupportPanel.jsx';
import './profile-settings.css';

const DAY=86400000;
const PREMIUM_PAYMENT_ADDRESS='0x046b97b07c13c4ad5e61599d98fcb52f1246247d';

export default function AccountPage({user,onBack=()=>{window.location.assign('/')}}){
 const [profile,setProfile]=useState(null),[verification,setVerification]=useState(null),[message,setMessage]=useState(''),[hash,setHash]=useState(''),[copied,setCopied]=useState(false),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now()),[editing,setEditing]=useState(false),[editName,setEditName]=useState(''),[editAvatar,setEditAvatar]=useState(''),[profileBusy,setProfileBusy]=useState(false),[profileMessage,setProfileMessage]=useState('');
 const [expanded,setExpanded]=useState(''),[supportOpen,setSupportOpen]=useState(false);
 const [notifications,setNotifications]=useState(()=>{try{return localStorage.getItem('kitagent-notifications')!=='off'}catch{return true}});
 useEffect(()=>{if(!db||!user?.uid)return;const uid=user.uid;return onSnapshot(doc(db,'users',uid),s=>{if(auth?.currentUser?.uid!==uid)return;const data=s.exists()?s.data():null;setProfile(data);setVerification(data?.latestPaymentVerification||null)},e=>{if(auth?.currentUser?.uid===uid)setMessage(e?.message||'Profile sync is temporarily unavailable.')})},[user?.uid]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 const d=profile||{},sub=d.subscription||{},name=d.displayName||user?.displayName||'KitSetups member',email=d.email||user?.email||'Firebase account',photo=d.photoURL||user?.photoURL||'',plan=String(d.plan||'free').toLowerCase();
 const trialStart=toMs(d.trialStartedAt),trialEnd=toMs(d.trialEndsAt),subscriptionEnd=toMs(d.subscriptionEndsAt);const trialTotal=Math.max(DAY*3,trialEnd-trialStart||DAY*3),trialRemaining=Math.max(0,trialEnd-now),trialActive=plan!=='premium'&&trialEnd>now,trialProgress=trialStart&&trialEnd?Math.min(100,Math.max(0,((now-trialStart)/trialTotal)*100)):0;const premiumActive=plan==='premium'&&(!subscriptionEnd||subscriptionEnd>now),premiumRemaining=Math.max(0,subscriptionEnd-now),premiumProgress=subscriptionEnd?Math.min(100,Math.max(0,1-premiumRemaining/(Number(sub.accessDays)||30)*DAY)):100;const paymentAddress=PREMIUM_PAYMENT_ADDRESS;
 const openProfileEditor=()=>{setEditName(name);setEditAvatar(photo);setProfileMessage('');setEditing(true)};
 const saveProfile=async()=>{const cleanName=editName.trim().replace(/\s+/g,' ').slice(0,32);const cleanAvatar=editAvatar.trim().slice(0,500);if(!cleanName)return setProfileMessage('Enter a username.');if(!auth?.currentUser||!db||!user?.uid)return setProfileMessage('Your account is not ready yet.');setProfileBusy(true);setProfileMessage('');try{await updateProfile(auth.currentUser,{displayName:cleanName,photoURL:cleanAvatar||null});await setDoc(doc(db,'users',user.uid),{displayName:cleanName,photoURL:cleanAvatar||''},{merge:true});setProfile(data=>({...data,displayName:cleanName,photoURL:cleanAvatar||''}));window.dispatchEvent(new CustomEvent('kitsetups:profile-updated',{detail:{displayName:cleanName,photoURL:cleanAvatar||''}}));setEditing(false)}catch(e){setProfileMessage(e?.message||'Profile could not be updated.')}finally{setProfileBusy(false)}};
 const copy=async()=>{try{await navigator.clipboard?.writeText(paymentAddress);setCopied(true);setTimeout(()=>setCopied(false),1400)}catch{setMessage('Copy is unavailable in this browser.')}};
 const verify=async()=>{if(!/^0x[a-f0-9]{64}$/i.test(hash.trim()))return setMessage('Enter the full transaction hash.');if(!auth?.currentUser)return setMessage('Authentication is required.');setBusy(true);setMessage('');try{const token=await auth.currentUser.getIdToken(true);const response=await fetch('/api/verify-payment',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({transactionHash:hash.trim()})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Payment verification failed.');setHash('');setMessage(`Payment verified. ${result.accessDays||30} days of Premium access granted.${result.affiliateCommission?` Affiliate commission recorded: $${Number(result.affiliateCommission).toFixed(2)}.`:''}`)}catch(e){setMessage(e?.message||'Payment verification could not be completed.')}finally{setBusy(false)}};
 const logout=async()=>{setMessage('');try{try{sessionStorage.removeItem('kitsetups:entrance-seen');sessionStorage.removeItem('kitsetups:current-page')}catch{}await signOut(auth)}catch(e){console.error('KitSetups logout failed:',e);setMessage('Unable to sign out right now. Check your connection and try again.')}};
 const toggleNotifications=()=>setNotifications(value=>{const next=!value;try{localStorage.setItem('kitagent-notifications',next?'on':'off')}catch{};window.dispatchEvent(new CustomEvent('kitagent:notifications-setting',{detail:{enabled:next}}));return next});
 const toggleSection=key=>{setExpanded(value=>value===key?'':key);setSupportOpen(false)};
 const openSupport=()=>{setSupportOpen(value=>!value);setExpanded('')};
 const row=(key,label,Icon,color,action,expandedRow=false)=><button className={`profile-settings-row ${expandedRow&&expanded===key?'is-expanded':''}`} data-profile-row={key} type="button" onClick={e=>{e.preventDefault();e.stopPropagation();action()}} aria-expanded={expandedRow?expanded===key:undefined}><span className={`profile-row-icon ${color}`}><Icon/></span><span>{label}</span>{expandedRow?<ChevronRight className={`profile-row-chevron ${expanded===key?'is-open':''}`}/>:null}</button>;
 return <div className="account-page profile-settings-page">
  <div className="profile-screen-heading"><button type="button" className="profile-back" aria-label="Back" onClick={onBack}><ArrowLeft size={17}/></button><h1>Profile</h1><div className="profile-plan-pill"><span>🔥</span>{premiumActive?'Premium':trialActive?`${Math.max(1,Math.ceil(trialRemaining/DAY))} Days`:'Free'}</div></div>
  <section className="profile-identity-row"><div className="profile-settings-avatar">{photo?<img src={photo} alt=""/>:<span>{initials(name)}</span>}</div><div className="profile-settings-user"><h2>{name}</h2><p>{email}</p></div><button className="profile-edit-icon" type="button" aria-label="Edit profile" onClick={openProfileEditor}><Edit3 size={17}/></button></section>
  {editing&&<div className="profile-editor-backdrop" role="dialog" aria-modal="true" aria-label="Edit profile"><div className="profile-editor"><div className="profile-editor-head"><div><span className="profile-editor-kicker">ACCOUNT PROFILE</span><h3>Edit your profile</h3><p>Change the name and avatar shown across KitSetups.</p></div><button type="button" onClick={()=>setEditing(false)} aria-label="Close"><X size={16}/></button></div><label className="profile-editor-field"><span>USERNAME</span><input value={editName} maxLength={32} onChange={e=>setEditName(e.target.value)} placeholder="Your name"/></label><label className="profile-editor-field"><span>AVATAR URL</span><input value={editAvatar} onChange={e=>setEditAvatar(e.target.value)} placeholder="https://…"/></label><div className="profile-editor-avatar-row"><div className="profile-editor-preview">{editAvatar?<img src={editAvatar} alt=""/>:<span>{initials(editName||name)}</span>}</div><div><b>Avatar preview</b><small>Use any public image URL. Your image stays tied to your account profile.</small></div></div>{profileMessage&&<div className="profile-editor-message"><UserRound size={13}/>{profileMessage}</div>}<div className="profile-editor-actions"><button type="button" className="profile-cancel" onClick={()=>setEditing(false)}>Cancel</button><button type="button" className="profile-save" onClick={saveProfile} disabled={profileBusy}>{profileBusy?<LoaderCircle className="spin" size={14}/>:<Save size={14}/>} {profileBusy?'Saving…':'Save changes'}</button></div></div></div>}
  <p className="profile-settings-caption">SETTINGS</p>
  <div className="profile-settings-list">
   <button className={`profile-settings-row ${expanded==='payments'?'is-expanded':''}`} data-profile-row="payments" type="button" onClick={()=>toggleSection('payments')} aria-expanded={expanded==='payments'}><span className="profile-row-icon payments"><WalletCards/></span><span>Subscription</span><ChevronRight className={`profile-row-chevron ${expanded==='payments'?'is-open':''}`}/></button>
   {expanded==='payments'&&<div className="profile-settings-expand profile-payment-slot" data-profile-panel="payments"><div className={`subscription-card free-plan ${trialActive?'trial-live':'trial-ended'}`}><div className="subscription-topline"><div><span className="subscription-label">FREE ACCESS</span><div className="plan-name-row"><h2>3 day trial</h2><span>{trialActive?'RUNNING':'ENDED'}</span></div></div><div className="remaining-block"><span className="subscription-label">REMAINING</span><strong>{trialActive?formatDuration(trialRemaining):'0D 00:00:00'}</strong></div></div><div className="trial-progress-meta"><span>Trial progress</span><b>{trialActive?`${Math.round(trialProgress)}% used`:'100% used'}</b></div><div className="usage-track trial-track"><i style={{width:`${trialProgress}%`}}/></div><div className="trial-dates"><span>{formatDate(trialStart)}</span><span>{formatDate(trialEnd)}</span></div></div><section className={`subscription-card premium-plan ${premiumActive?'is-current':''}`}><div className="premium-header"><div className="premium-mark"><Flame size={16}/></div><div className="premium-copy"><h2>{sub.name||'Premium'}</h2><p>{Array.isArray(sub.features)?sub.features.join(' · '):'Unlimited setups · Live intelligence'}</p></div><div className="premium-price"><strong>$20</strong><span>/ 30 DAYS</span></div></div><div className="premium-stats"><div><strong>∞</strong><span>SETUPS</span></div><div><strong>LIVE</strong><span>INTELLIGENCE</span></div><div><strong>{sub.accessDays||30}D</strong><span>ACCESS</span></div></div>{premiumActive&&subscriptionEnd?<div className="subscription-live"><div><span>SUBSCRIPTION ACTIVE</span><b>{formatDuration(premiumRemaining)} remaining</b></div><div className="usage-track"><i style={{width:`${premiumProgress*100}%`}}/></div></div>:<div className="payment-panel"><div className="payment-heading"><span>PAY WITH {String(sub.paymentAsset||'USDT').toUpperCase()}</span><b>{String(sub.paymentNetwork||'BNB CHAIN').toUpperCase()}</b></div><div className="payment-address" onClick={copy}><span>{paymentAddress}</span><button type="button" onClick={e=>{e.stopPropagation();copy()}}><Copy size={13}/></button></div><div className="payment-input-wrap"><span>TRANSACTION HASH</span><input value={hash} onChange={e=>{setHash(e.target.value);setMessage('')}} placeholder="Paste BNB Chain USDT transaction hash"/></div><button className="verify-payment-btn" type="button" onClick={verify} disabled={busy}>{busy?<LoaderCircle className="spin" size={14}/>:<ShieldCheck size={14}/>} {busy?'Verifying payment…':'Verify payment'}</button>{(copied||message||verification)&&<div className="payment-feedback"><Check size={12}/>{copied?'Payment address copied':message||`Verification: ${verification.status}.`}</div>}</div>}</section></div>}
   <button className={`profile-settings-row ${expanded==='affiliate'?'is-expanded':''}`} data-profile-row="affiliate" type="button" onClick={()=>toggleSection('affiliate')} aria-expanded={expanded==='affiliate'}><span className="profile-row-icon referrals"><Users/></span><span>Affiliate</span><ChevronRight className={`profile-row-chevron ${expanded==='affiliate'?'is-open':''}`}/></button>
   {expanded==='affiliate'&&<div className="profile-settings-expand profile-affiliate-slot" data-profile-panel="affiliate"><AffiliatePanel/></div>}
   <button className="profile-settings-row" type="button" aria-pressed={notifications} onClick={toggleNotifications}><span className="profile-row-icon notifications"><Bell/></span><span>Notifications</span><span className={`profile-toggle ${notifications?'is-on':''}`} aria-hidden="true"/></button>
   {row('support','Support',Headphones,'support',openSupport)}
   {supportOpen&&<div className="profile-settings-expand support-form"><LiveSupportPanel user={user} name={name} email={email}/></div>}
   <button className="profile-settings-row" type="button" onClick={()=>window.location.assign('/delete-account')}><span className="profile-row-icon delete"><Trash2/></span><span>Delete Account</span><ChevronRight className="profile-row-chevron"/></button>
   <button className="profile-settings-row logout-row" type="button" onClick={logout}><span className="profile-row-icon logout"><LogOut/></span><span>Logout</span></button>
  </div>
  {message&&!expanded.includes('payments')&&<p className="profile-inline-note" role="status">{message}</p>}
 </div>;
}
function toMs(v){if(!v)return 0;if(typeof v.toMillis==='function')return v.toMillis();if(typeof v.toDate==='function')return v.toDate().getTime();return new Date(v).getTime()||0}
function formatDuration(ms){const s=Math.max(0,Math.floor(ms/1000)),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),x=s%60;return `${d}D ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function formatDate(ms){return ms?new Date(ms).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—'}
function initials(v){return String(v||'K').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'K'}
