import { useEffect, useMemo, useState } from 'react';
import { browserLocalPersistence, onAuthStateChanged, setPersistence, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { ArrowLeft, CheckCircle2, Clock3, Gift, KeyRound, LogIn, MailPlus, Search, ShieldCheck, UserRound, Users, XCircle, RefreshCw } from 'lucide-react';
import { auth } from './firebase.js';
import './admin-page.css';

function toMs(v){if(!v)return 0;if(typeof v.toMillis==='function')return v.toMillis();if(typeof v.toDate==='function')return v.toDate().getTime();return new Date(v).getTime()||0}
function formatDate(v){const ms=toMs(v);return ms?new Date(ms).toLocaleString([], {month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—'}
function initials(v){return String(v||'U').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'U'}

export default function AdminPage(){
 const [adminUser,setAdminUser]=useState(null),[authReady,setAuthReady]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authBusy,setAuthBusy]=useState(false),[query,setQuery]=useState(''),[users,setUsers]=useState([]),[admins,setAdmins]=useState([]),[selected,setSelected]=useState(null),[days,setDays]=useState(30),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[adminEmail,setAdminEmail]=useState('');
 useEffect(()=>{if(!auth)return;setPersistence(auth,browserLocalPersistence).catch(()=>{});return onAuthStateChanged(auth,u=>{setAdminUser(u||null);setAuthReady(true)})},[]);
 const call=async(options={})=>{const current=auth?.currentUser;if(!current)throw new Error('Admin session is not active.');let token=await current.getIdToken(true);const request=t=>fetch('/api/admin/grant-premium'+(options.query?'?q='+encodeURIComponent(options.query):''),{method:options.method||'GET',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:options.body?JSON.stringify(options.body):undefined});let response=await request(token);if(response.status===401){token=await current.getIdToken(true);response=await request(token)}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Admin request failed.');return data};
 const load=async()=>{if(!adminUser)return;setLoading(true);setError('');try{const [u,a]=await Promise.all([call({query:query.trim()}),call({query:'__admins__'})]);setUsers(u.users||[]);setAdmins(a.admins||[])}catch(e){setError(e.message||'Unable to load admin data.')}finally{setLoading(false)}};
 useEffect(()=>{if(!adminUser)return;const t=setTimeout(load,180);return()=>clearTimeout(t)},[adminUser,query]);
 const visible=useMemo(()=>users.slice(0,50),[users]);
 const login=async e=>{e.preventDefault();setAuthBusy(true);setError('');try{await setPersistence(auth,browserLocalPersistence);await signInWithEmailAndPassword(auth,email.trim().toLowerCase(),password);setPassword('')}catch(e){setError(e?.code==='auth/invalid-credential'?'Email or password is incorrect.':e?.code==='auth/too-many-requests'?'Too many attempts. Please wait a moment.':'Admin sign in failed.')}finally{setAuthBusy(false)}};
 const addAdmin=async()=>{const clean=adminEmail.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(clean))return setError('Enter a valid admin email.');setBusy(true);setError('');setNotice('');try{await call({method:'POST',body:{action:'add-admin',email:clean}});setAdminEmail('');setNotice(clean+' is now authorized as a KitSetups admin.');await load()}catch(e){setError(e.message||'Could not add admin.')}finally{setBusy(false)}};
 const removeAdmin=async mail=>{if(!window.confirm('Remove admin access for '+mail+'?'))return;setBusy(true);setError('');try{await call({method:'POST',body:{action:'remove-admin',email:mail}});setNotice(mail+' no longer has admin access.');await load()}catch(e){setError(e.message||'Could not remove admin.')}finally{setBusy(false)}};
 const hardReset=async()=>{if(!selected||busy)return;const label=selected.displayName||selected.email||selected.uid;if(!window.confirm('HARD RESET '+label+'? This permanently deletes the Firebase account, profile, device binding, signup locks, and account-linked KitSetups data. This cannot be undone.'))return;setBusy(true);setError('');setNotice('');try{await call({method:'POST',body:{action:'hard-reset',uid:selected.uid}});setUsers(current=>current.filter(x=>x.uid!==selected.uid));setSelected(null);setNotice(label+' was completely reset. They can register again from the same device.')}catch(e){setError(e.message||'Hard reset failed.')}finally{setBusy(false)}};
 const grant=async()=>{if(!selected||busy)return;setBusy(true);setError('');setNotice('');try{const data=await call({method:'POST',body:{uid:selected.uid,days}});setNotice(`Premium gifted to ${data.displayName||data.email} for ${days} days.`);await load();setSelected(x=>users.find(u=>u.uid===x?.uid)||x)}catch(e){setError(e.message||'Premium gift failed.')}finally{setBusy(false)}};
 if(!authReady)return <div className="admin-login"><div className="admin-login-card"><ShieldCheck size={22}/><h1>KitSetups Admin</h1><p>Loading secure admin session…</p></div></div>;
 if(!adminUser)return <div className="admin-login"><div className="admin-login-card"><div className="admin-login-brand"><ShieldCheck size={20}/><span>INTERNAL ACCESS</span></div><h1>KitSetups Admin</h1><p>Private operations dashboard. Your admin session is remembered on this device.</p><form onSubmit={login}><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email"/><input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/>{error&&<div className="admin-alert error">{error}</div>}<button className="admin-login-button" disabled={authBusy}><LogIn size={15}/>{authBusy?'Signing in…':'Enter admin dashboard'}</button></form><button className="admin-back login-back" onClick={()=>window.location.href='/'}><ArrowLeft size={15}/> Back to KitSetups</button></div></div>;
 return <div className="admin-shell"><header className="admin-topbar"><button className="admin-back" onClick={()=>window.location.href='/'}><ArrowLeft size={16}/> KitSetups</button><div className="admin-title"><span>PRIVATE OPERATIONS</span><h1>Admin Dashboard</h1></div><div className="admin-user"><ShieldCheck size={15}/><span>{adminUser.email}</span><button onClick={()=>signOut(auth)} title="Sign out">Sign out</button></div></header>
 <main className="admin-content"><div className="admin-hero"><div className="admin-kicker"><ShieldCheck size={14}/> INTERNAL ACCESS</div><h2>KitSetups control center.</h2><p>Manage Premium access, account recovery, device resets, support operations and administrator access from one clean workspace.</p></div>
 {error&&<div className="admin-alert error"><XCircle size={16}/><span>{error}</span></div>}{notice&&<div className="admin-alert success"><CheckCircle2 size={16}/><span>{notice}</span></div>}
 <div className="admin-tools"><section className="admin-card admin-admin-card"><div className="admin-card-head"><div><span>ADMIN ACCESS</span><h3>Manage administrators</h3></div><Users size={18}/></div><div className="admin-add-row"><input value={adminEmail} onChange={e=>setAdminEmail(e.target.value)} placeholder="admin@example.com" type="email"/><button onClick={addAdmin} disabled={busy}><MailPlus size={15}/> Add admin</button></div><div className="admin-admin-list">{admins.map(a=><div className="admin-admin-row" key={a.email}><span className="admin-avatar">{initials(a.email)}</span><div><b>{a.email}</b><small>{a.source==='owner'?'Owner access':'Admin access'}</small></div>{a.source!=='owner'&&<button onClick={()=>removeAdmin(a.email)} disabled={busy}>Remove</button>}</div>)}</div><small className="admin-note">Adding an email grants admin access when that person signs in with the matching KitSetups account.</small></section>
 <button type="button" className="admin-support-link" onClick={()=>window.location.href='/admin/support'}>Support inbox <span>Open live conversations →</span></button></div>
 <section className="admin-grid"><div className="admin-card"><div className="admin-card-head"><div><span>ACCOUNT OPERATIONS</span><h3>Registered users</h3></div><UserRound size={18}/></div><label className="admin-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, username or email"/></label><div className="admin-user-list">{loading?<div className="admin-empty">Loading…</div>:visible.length===0?<div className="admin-empty">No registered users found.</div>:visible.map(item=><button key={item.uid} className={'admin-user-row '+(selected?.uid===item.uid?'selected':'')} onClick={()=>{setSelected(item);setError('');setNotice('')}}><span className="admin-avatar">{item.photoURL?<img src={item.photoURL} alt=""/>:initials(item.displayName||item.email)}</span><span className="admin-user-copy"><b>{item.displayName||'Unnamed user'}</b><small>{item.email||item.username||item.uid}</small></span><span className={'admin-plan '+(item.plan==='premium'?'premium':'')}>{item.plan==='premium'?'PREMIUM':'FREE'}</span></button>)}</div></div>
 <div className="admin-card admin-gift-card"><div className="admin-card-head"><div><span>SELECTED ACCOUNT</span><h3>{selected?'Account controls':'Choose a user'}</h3></div><KeyRound size={18}/></div>{!selected?<div className="admin-empty large">Select a registered user to manage Premium access or perform a complete account reset.</div>:<><div className="admin-recipient"><span className="admin-avatar">{selected.photoURL?<img src={selected.photoURL} alt=""/>:initials(selected.displayName||selected.email)}</span><div><b>{selected.displayName||'Unnamed user'}</b><small>{selected.email}</small></div></div><div className="admin-duration-label">PREMIUM DURATION</div><div className="admin-duration-grid">{[7,30,90].map(v=><button key={v} className={days===v?'active':''} onClick={()=>setDays(v)}><strong>{v}</strong><span>days</span></button>)}</div><div className="admin-current"><Clock3 size={14}/><span>Current Premium expiry</span><b>{formatDate(selected.subscriptionEndsAt)}</b></div><button className="admin-grant" disabled={busy} onClick={grant}><Gift size={16}/>{busy?'Working…':`Grant ${days} days Premium`}</button><button className="admin-reset" disabled={busy} onClick={hardReset}><RefreshCw size={15}/>{busy?'Resetting account…':'Hard reset account'}</button><small className="admin-note">Hard reset removes the Firebase account, profile tree, device binding, signup locks and account-linked records handled by the reset service.</small></>}</div></section></main></div>
}