import { useEffect, useMemo, useState } from 'react';
import { browserLocalPersistence, onAuthStateChanged, setPersistence, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { Activity, AlertTriangle, ArrowLeft, CheckCircle2, Clock3, Gift, LayoutDashboard, LogIn, MailPlus, Menu, RefreshCw, Search, Settings, ShieldCheck, Ticket, UserRound, Users, X, XCircle } from 'lucide-react';
import { auth } from './firebase.js';
import './admin-page.css';

function toMs(v){if(!v)return 0;if(typeof v.toMillis==='function')return v.toMillis();if(typeof v.toDate==='function')return v.toDate().getTime();return new Date(v).getTime()||0}
function formatDate(v){const ms=toMs(v);return ms?new Date(ms).toLocaleString([], {month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—'}
function initials(v){return String(v||'U').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'U'}

const nav=[['overview','Overview',LayoutDashboard],['users','Users',Users],['premium','Premium',Gift],['recovery','Account Recovery',RefreshCw],['support','Support',Ticket],['admins','Administrators',ShieldCheck]];

export default function AdminPage(){
 const [adminUser,setAdminUser]=useState(null),[authReady,setAuthReady]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authBusy,setAuthBusy]=useState(false),[section,setSection]=useState('overview'),[query,setQuery]=useState(''),[users,setUsers]=useState([]),[admins,setAdmins]=useState([]),[selected,setSelected]=useState(null),[days,setDays]=useState(30),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[adminEmail,setAdminEmail]=useState(''),[showAddAdmin,setShowAddAdmin]=useState(false),[mobileNav,setMobileNav]=useState(false);
 useEffect(()=>{if(!auth)return;setPersistence(auth,browserLocalPersistence).catch(()=>{});return onAuthStateChanged(auth,u=>{setAdminUser(u||null);setAuthReady(true)})},[]);
 const call=async(options={})=>{const current=auth?.currentUser;if(!current)throw new Error('Admin session is not active.');let token=await current.getIdToken(true);const request=t=>fetch('/api/admin/grant-premium'+(options.query?'?q='+encodeURIComponent(options.query):''),{method:options.method||'GET',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:options.body?JSON.stringify(options.body):undefined});let response=await request(token);if(response.status===401){token=await current.getIdToken(true);response=await request(token)}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Admin request failed.');return data};
 const load=async()=>{if(!adminUser)return;setLoading(true);setError('');try{const [u,a]=await Promise.all([call({query:query.trim()}),call({query:'__admins__'})]);setUsers(u.users||[]);setAdmins(a.admins||[])}catch(e){setError(e.message||'Unable to load admin data.')}finally{setLoading(false)}};
 useEffect(()=>{if(!adminUser)return;const t=setTimeout(load,180);return()=>clearTimeout(t)},[adminUser,query]);
 const visible=useMemo(()=>users.slice(0,50),[users]);
 const login=async e=>{e.preventDefault();setAuthBusy(true);setError('');try{await setPersistence(auth,browserLocalPersistence);await signInWithEmailAndPassword(auth,email.trim().toLowerCase(),password);setPassword('')}catch(e){setError(e?.code==='auth/invalid-credential'?'Email or password is incorrect.':e?.code==='auth/too-many-requests'?'Too many attempts. Please wait a moment.':'Admin sign in failed.')}finally{setAuthBusy(false)}};
 const addAdmin=async()=>{const clean=adminEmail.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(clean))return setError('Enter a valid admin email.');setBusy(true);setError('');setNotice('');try{await call({method:'POST',body:{action:'add-admin',email:clean}});setAdminEmail('');setShowAddAdmin(false);setNotice(clean+' now has admin access. They can enter /admin with their KitSetups account.');await load()}catch(e){setError(e.message||'Could not add admin.')}finally{setBusy(false)}};
 const removeAdmin=async mail=>{if(!window.confirm('Remove admin access for '+mail+'?'))return;setBusy(true);setError('');try{await call({method:'POST',body:{action:'remove-admin',email:mail}});setNotice(mail+' no longer has admin access.');await load()}catch(e){setError(e.message||'Could not remove admin.')}finally{setBusy(false)}};
 const hardReset=async()=>{if(!selected||busy)return;const label=selected.displayName||selected.email||selected.uid;if(!window.confirm('HARD RESET '+label+'? This permanently deletes the Firebase account, profile, device binding, signup locks, and account-linked KitSetups data. This cannot be undone.'))return;setBusy(true);setError('');setNotice('');try{await call({method:'POST',body:{action:'hard-reset',uid:selected.uid}});setUsers(current=>current.filter(x=>x.uid!==selected.uid));setSelected(null);setNotice(label+' was completely reset. They can register again from the same device.')}catch(e){setError(e.message||'Hard reset failed.')}finally{setBusy(false)}};
 const grant=async()=>{if(!selected||busy)return;setBusy(true);setError('');setNotice('');try{const data=await call({method:'POST',body:{uid:selected.uid,days}});setNotice(`Premium gifted to ${data.displayName||data.email} for ${days} days.`);await load()}catch(e){setError(e.message||'Premium gift failed.')}finally{setBusy(false)}};
 if(!authReady)return <div className="admin-login"><div className="admin-login-card"><ShieldCheck size={22}/><h1>KitSetups Admin</h1><p>Loading secure admin session…</p></div></div>;
 if(!adminUser)return <div className="admin-login"><div className="admin-login-card"><div className="admin-login-brand"><ShieldCheck size={20}/><span>PRIVATE ADMIN</span></div><h1>KitSetups Admin</h1><p>Sign in with your authorized KitSetups account. Your admin session is remembered on this device.</p><form onSubmit={login}><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address"/><input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/>{error&&<div className="admin-alert error">{error}</div>}<button className="admin-login-button" disabled={authBusy}><LogIn size={15}/>{authBusy?'Signing in…':'Enter dashboard'}</button></form><button className="admin-back login-back" onClick={()=>window.location.href='/'}><ArrowLeft size={15}/> Back to KitSetups</button></div></div>;
 const activeTitle=nav.find(x=>x[0]===section)?.[1]||'Overview';
 return <div className="admin-app">
  <aside className={'admin-sidebar '+(mobileNav?'open':'')}><div className="admin-brand"><div className="admin-brand-mark"><ShieldCheck size={17}/></div><div><b>KitSetups</b><span>ADMIN CONSOLE</span></div><button className="admin-close-nav" onClick={()=>setMobileNav(false)}><X size={17}/></button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>{setSection(id);setMobileNav(false);setError('')}}><Icon size={16}/><span>{label}</span></button>)}</nav><div className="admin-sidebar-foot"><div><span>Signed in as</span><b>{adminUser.email}</b></div><button onClick={()=>signOut(auth)}>Sign out</button></div></aside>
  {mobileNav&&<button className="admin-nav-scrim" onClick={()=>setMobileNav(false)} aria-label="Close navigation"/>}
  <section className="admin-main"><header className="admin-header"><button className="admin-menu" onClick={()=>setMobileNav(true)}><Menu size={18}/></button><div><span>INTERNAL OPERATIONS</span><h1>{activeTitle}</h1></div><div className="admin-header-right"><span className="admin-live"><i/> System active</span><button onClick={()=>window.location.href='/'} title="Back to KitSetups"><ArrowLeft size={15}/></button></div></header>
   <main className="admin-page">
    {error&&<div className="admin-alert error"><XCircle size={16}/><span>{error}</span><button onClick={()=>setError('')}><X size={14}/></button></div>}{notice&&<div className="admin-alert success"><CheckCircle2 size={16}/><span>{notice}</span><button onClick={()=>setNotice('')}><X size={14}/></button></div>}
    {section==='overview'&&<><div className="admin-welcome"><div><span className="admin-kicker">CONTROL CENTER</span><h2>Everything important, organized.</h2><p>Manage users, Premium access, account recovery, support and administrator permissions from one workspace.</p></div><Activity size={30}/></div><div className="admin-stat-grid"><div className="admin-stat"><Users size={17}/><span>Registered users</span><b>{users.length}</b></div><div className="admin-stat"><Gift size={17}/><span>Premium users</span><b>{users.filter(u=>u.plan==='premium').length}</b></div><div className="admin-stat"><ShieldCheck size={17}/><span>Administrators</span><b>{admins.length}</b></div></div><div className="admin-quick-grid"><button onClick={()=>setSection('users')}><Users size={19}/><b>Manage users</b><span>Search accounts and open controls →</span></button><button onClick={()=>setSection('recovery')}><RefreshCw size={19}/><b>Account recovery</b><span>Resolve binding and account issues →</span></button><button onClick={()=>setSection('premium')}><Gift size={19}/><b>Premium access</b><span>Gift Premium to an existing account →</span></button><button onClick={()=>setSection('admins')}><ShieldCheck size={19}/><b>Administrators</b><span>Control internal dashboard access →</span></button></div></>}
    {section==='users'&&<section className="admin-section-card"><div className="section-heading"><div><span>ACCOUNT DIRECTORY</span><h2>Registered users</h2><p>Search an account and select it to view its available controls.</p></div><UserRound size={20}/></div><label className="admin-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, username or email"/></label><div className="admin-users-layout"><div className="admin-user-list">{loading?<div className="admin-empty">Loading users…</div>:visible.length===0?<div className="admin-empty">No registered users found.</div>:visible.map(item=><button key={item.uid} className={'admin-user-row '+(selected?.uid===item.uid?'selected':'')} onClick={()=>setSelected(item)}><span className="admin-avatar">{item.photoURL?<img src={item.photoURL} alt=""/>:initials(item.displayName||item.email)}</span><span className="admin-user-copy"><b>{item.displayName||'Unnamed user'}</b><small>{item.email||item.username||item.uid}</small></span><span className={'admin-plan '+(item.plan==='premium'?'premium':'')}>{item.plan==='premium'?'PREMIUM':'FREE'}</span></button>)}</div><UserPanel selected={selected} days={days} setDays={setDays} busy={busy} grant={grant} hardReset={hardReset}/></div></section>}
    {section==='premium'&&<section className="admin-section-card"><div className="section-heading"><div><span>PREMIUM ACCESS</span><h2>Grant Premium</h2><p>Choose a registered user, select a duration and grant access.</p></div><Gift size={20}/></div><div className="premium-layout"><div className="admin-user-list compact">{visible.map(item=><button key={item.uid} className={'admin-user-row '+(selected?.uid===item.uid?'selected':'')} onClick={()=>setSelected(item)}><span className="admin-avatar">{item.photoURL?<img src={item.photoURL} alt=""/>:initials(item.displayName||item.email)}</span><span className="admin-user-copy"><b>{item.displayName||'Unnamed user'}</b><small>{item.email}</small></span><span className="admin-plan">{item.plan==='premium'?'PREMIUM':'FREE'}</span></button>)}</div><UserPanel selected={selected} days={days} setDays={setDays} busy={busy} grant={grant}/></div></section>}
    {section==='recovery'&&<section className="admin-section-card"><div className="section-heading"><div><span>ACCOUNT RECOVERY</span><h2>Hard reset</h2><p>Use this only when an account must be completely cleared so the user can start again.</p></div><RefreshCw size={20}/></div><label className="admin-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find the account to reset"/></label><div className="recovery-layout"><div className="admin-user-list compact">{visible.map(item=><button key={item.uid} className={'admin-user-row '+(selected?.uid===item.uid?'selected':'')} onClick={()=>setSelected(item)}><span className="admin-avatar">{item.photoURL?<img src={item.photoURL} alt=""/>:initials(item.displayName||item.email)}</span><span className="admin-user-copy"><b>{item.displayName||'Unnamed user'}</b><small>{item.email}</small></span></button>)}</div><div className="danger-panel">{selected?<><AlertTriangle size={22}/><span>DANGER ZONE</span><h3>Reset {selected.displayName||selected.email}</h3><p>This removes the Firebase account and the account-linked records handled by the reset service, including device binding and signup locks.</p><button className="admin-danger" disabled={busy} onClick={hardReset}><RefreshCw size={15}/>{busy?'Resetting…':'Hard reset this account'}</button></>:<div className="admin-empty large">Select an account to prepare a hard reset.</div>}</div></div></section>}
    {section==='admins'&&<section className="admin-section-card"><div className="section-heading"><div><span>ACCESS CONTROL</span><h2>Administrators</h2><p>Only authorized emails can enter the private admin console.</p></div><ShieldCheck size={20}/></div><div className="admin-toolbar"><div><b>Admin access</b><span>{admins.length} authorized account{admins.length===1?'':'s'}</span></div><button className="primary-small" onClick={()=>setShowAddAdmin(true)}><MailPlus size={15}/> Add administrator</button></div><div className="admin-table">{admins.map(a=><div className="admin-table-row" key={a.email}><span className="admin-avatar">{initials(a.email)}</span><div><b>{a.email}</b><small>{a.source==='owner'?'Owner access':'Administrator access'}</small></div><span className="admin-access-badge">ACTIVE</span>{a.source!=='owner'&&<button onClick={()=>removeAdmin(a.email)}>Remove</button>}</div>)}</div></section>}
    {section==='support'&&<section className="admin-section-card"><div className="section-heading"><div><span>SUPPORT OPERATIONS</span><h2>Support inbox</h2><p>Open the dedicated live support workspace.</p></div><Ticket size={20}/></div><button className="support-open" onClick={()=>window.location.href='/admin/support'}><Ticket size={19}/><b>Open live conversations</b><span>Go to support workspace →</span></button></section>}
   </main>
  </section>
  {showAddAdmin&&<div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setShowAddAdmin(false)}><div className="admin-modal"><button className="modal-close" onClick={()=>setShowAddAdmin(false)}><X size={17}/></button><span>ADMINISTRATOR ACCESS</span><h2>Add administrator</h2><p>Enter the email address of an existing KitSetups account. That account will then be able to sign in at <b>/admin</b>.</p><label>Email address<input autoFocus type="email" value={adminEmail} onChange={e=>setAdminEmail(e.target.value)} placeholder="name@example.com" onKeyDown={e=>e.key==='Enter'&&addAdmin()}/></label><div className="modal-actions"><button className="secondary" onClick={()=>setShowAddAdmin(false)}>Cancel</button><button className="primary-small" disabled={busy} onClick={addAdmin}>{busy?'Adding…':'Grant admin access'}</button></div></div></div>}
 </div>
}

function UserPanel({selected,days,setDays,busy,grant,hardReset}){return <div className="user-panel">{!selected?<div className="admin-empty large">Select a user to view account controls.</div>:<><div className="panel-user"><span className="admin-avatar">{selected.photoURL?<img src={selected.photoURL} alt=""/>:initials(selected.displayName||selected.email)}</span><div><b>{selected.displayName||'Unnamed user'}</b><small>{selected.email}</small></div></div><div className="panel-rule"/><span className="panel-label">PREMIUM DURATION</span><div className="admin-duration-grid">{[7,30,90].map(v=><button key={v} className={days===v?'active':''} onClick={()=>setDays(v)}><strong>{v}</strong><span>days</span></button>)}</div><div className="admin-current"><Clock3 size={14}/><span>Current expiry</span><b>{formatDate(selected.subscriptionEndsAt)}</b></div><button className="admin-grant" disabled={busy} onClick={grant}><Gift size={15}/>{busy?'Working…':`Grant ${days} days Premium`}</button>{hardReset&&<button className="admin-reset" disabled={busy} onClick={hardReset}><RefreshCw size={15}/>{busy?'Resetting…':'Hard reset account'}</button>}</>}</div>}
