import { useEffect, useState } from 'react';
import { Copy, LoaderCircle, Users, WalletCards } from 'lucide-react';
import { auth } from './firebase.js';
import './affiliate-panel.css';

export default function AffiliatePanel(){
 const [data,setData]=useState(null),[busy,setBusy]=useState(true),[message,setMessage]=useState(''),[code,setCode]=useState('');
 const load=async()=>{if(!auth?.currentUser)return;setBusy(true);setMessage('');try{const token=await auth.currentUser.getIdToken();const r=await fetch('/api/affiliate',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'dashboard'})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Affiliate data could not be loaded.');setData(body);setCode(body.referralCode||'')}catch(e){setMessage(e?.message||'Affiliate data could not be loaded.')}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const register=async()=>{if(!auth?.currentUser)return;setBusy(true);setMessage('');try{const token=await auth.currentUser.getIdToken();const r=await fetch('/api/affiliate',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'register',referralCode:code})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Affiliate registration failed.');setData(body);setCode(body.referralCode||'')}catch(e){setMessage(e?.message||'Affiliate registration failed.')}finally{setBusy(false)}};
 const link=code?`https://kitagent.xyz/?ref=${encodeURIComponent(code)}`:'';
 const copy=async()=>{if(!link)return;try{await navigator.clipboard?.writeText(link);setMessage('Referral link copied.')}catch{setMessage('Copy is unavailable in this browser.')}};
 if(busy&&!data)return <section className="account-section-label"><LoaderCircle className="spin" size={14}/> AFFILIATE</section>;
 return <><div className="account-section-label">AFFILIATE</div><section className="affiliate-account-card"><div className="affiliate-account-head"><div><span>GROW WITH KITAGENT</span><h3>Affiliate programme</h3><p>Share your link and earn on qualifying Premium payments.</p></div><Users size={20}/></div>{data?.affiliate?<><div className="affiliate-metrics"><div><small>CODE</small><b>{data.referralCode}</b></div><div><small>AVAILABLE</small><b>${Number(data.availableBalance||0).toFixed(2)}</b></div><div><small>TOTAL EARNED</small><b>${Number(data.totalEarned||0).toFixed(2)}</b></div></div><div className="affiliate-link-row"><input readOnly value={link}/><button type="button" onClick={copy}><Copy size={14}/> Copy</button></div><div className="affiliate-foot"><span><WalletCards size={14}/> {Number(data.commissionRateBps||0)/100}% commission rate</span><span>{data.status||'active'}</span></div></>:<><div className="affiliate-register-row"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,''))} maxLength={24} placeholder="Optional referral code"/><button type="button" onClick={register} disabled={busy}>Join programme</button></div><small>Leave the code blank and KitAgent will generate one for you.</small></>}{message&&<div className="payment-feedback">{message}</div>}</section></>;
}
