import { useEffect, useState } from 'react';
import { Copy, LoaderCircle, Users, WalletCards } from 'lucide-react';
import { auth } from './firebase.js';
import './affiliate-panel.css';

export default function AffiliatePanel(){
 const [data,setData]=useState(()=>{try{return JSON.parse(localStorage.getItem('kitsetups:affiliate-cache')||'null')}catch{return null}}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[code,setCode]=useState(''),[wallet,setWallet]=useState(''),[savingWallet,setSavingWallet]=useState(false);
 const load=async()=>{if(!auth?.currentUser)return;setBusy(true);setMessage('');try{const token=await auth.currentUser.getIdToken();const r=await fetch('/api/affiliate',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'dashboard'})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Affiliate data could not be loaded.');setData(body);try{localStorage.setItem('kitsetups:affiliate-cache',JSON.stringify(body))}catch{}setCode(body.referralCode||'');setWallet(body.payoutWallet||'')}catch(e){setMessage(e?.message||'Affiliate data could not be loaded.')}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const register=async()=>{if(!auth?.currentUser)return;setBusy(true);setMessage('');try{const token=await auth.currentUser.getIdToken();const r=await fetch('/api/affiliate',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'register',referralCode:code})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Affiliate registration failed.');setData(body);setCode(body.referralCode||'')}catch(e){setMessage(e?.message||'Affiliate registration failed.')}finally{setBusy(false)}};
 const saveWallet=async()=>{if(!auth?.currentUser)return;setSavingWallet(true);setMessage('');try{const token=await auth.currentUser.getIdToken();const r=await fetch('/api/affiliate',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'wallet',payoutWallet:wallet})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Wallet could not be saved.');setWallet(body.payoutWallet||wallet);setMessage('BEP20 payout wallet saved.')}catch(e){setMessage(e?.message||'Wallet could not be saved.')}finally{setSavingWallet(false)}};
 const link=code?`https://kitsetups.xyz/?ref=${encodeURIComponent(code)}`:'';
 const copy=async()=>{if(!link)return;try{await navigator.clipboard?.writeText(link);setMessage('Referral link copied.')}catch{setMessage('Copy is unavailable in this browser.')}};
 if(false)return <section className="account-section-label"><LoaderCircle className="spin" size={14}/> AFFILIATE</section>;
 return <><div className="account-section-label">AFFILIATE</div><section className="affiliate-account-card"><div className="affiliate-account-head"><div><span>GROW WITH KITSETUPS</span><h3>Affiliate programme</h3><p>Share your KitSetups referral link and earn 10% on qualifying Premium payments.</p></div><Users size={20}/></div>{data?.affiliate?<><div className="affiliate-metrics"><div><small>REFERRALS</small><b>{Number(data.referralCount||0)}</b></div><div><small>AVAILABLE</small><b>${Number(data.availableBalance||0).toFixed(2)}</b></div><div><small>TOTAL EARNED</small><b>${Number(data.totalEarned||0).toFixed(2)}</b></div><div><small>TOTAL PAID OUT</small><b>${Number(data.paidOut||0).toFixed(2)}</b></div></div><div className="affiliate-link-row"><input readOnly value={link}/><button type="button" onClick={copy}><Copy size={14}/> Copy</button></div><div className="affiliate-wallet-row"><input value={wallet} onChange={e=>setWallet(e.target.value.trim())} placeholder="BEP20 USDT payout wallet"/><button type="button" onClick={saveWallet} disabled={savingWallet}>{savingWallet?<LoaderCircle className="spin" size={13}/>:<WalletCards size={13}/>} Save</button></div><div className="affiliate-foot"><span><WalletCards size={14}/> {Number(data.commissionRateBps||0)/100}% recurring commission</span><span>USDT · BEP20 · $20 minimum</span></div></>:<><div className="affiliate-register-row"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,''))} maxLength={24} placeholder="Optional referral code"/><button type="button" onClick={register} disabled={busy}>Join programme</button></div><small>Leave the code blank and KitSetups will generate one for you.</small></>}{message&&<div className="payment-feedback">{message}</div>}</section></>;
}
