import { adapterRegistry } from './adapters/index.js';
import { simulateTransaction, submitPlan, waitForReceipt } from './engine/transactionEngine.js';
import { getActiveProvider, getConnectedAddress } from './walletConnector.js';
import { getDecimals, parseUnits } from './onchain/erc20.js';

const ADDRESS=/0x[a-fA-F0-9]{40}/g;
const NATIVE=/\b(eth|native|rbh|robinhood|ether)\b/i;

function normalizeCommand(command){return String(command||'').trim().replace(/\s+/g,' ');}
function addresses(text){return String(text).match(ADDRESS)||[];}
function amount(text){const m=String(text).match(/\b\d+(?:\.\d+)?\b/);return m?.[0]||null;}
function detectIntent(command){const s=String(command).toLowerCase();if(/\b(send|transfer)\b/.test(s))return'send';if(/\b(swap|exchange)\b/.test(s))return'swap';if(/\b(bridge|cross.?chain)\b/.test(s))return'bridge';if(/\b(buy|purchase)\b/.test(s))return'buy';if(/\b(sell|dump)\b/.test(s)&&/\bnft\b/.test(s))return'nft';if(/\b(nft|erc721|erc1155|list)\b/.test(s))return'nft';if(/\b(lend|supply|deposit.*morpho|earn.*yield)\b/.test(s))return'lend';if(/\b(borrow|loan)\b/.test(s))return'borrow';if(/\b(stake|staking)\b/.test(s))return'stake';if(/\b(withdraw|unstake|redeem)\b/.test(s))return'withdraw';if(/\b(claim|airdrop)\b/.test(s))return'claim';if(/\bfaucet\b/.test(s))return'faucet';if(/\b(balance|wallet|portfolio|positions?)\b/.test(s))return'wallet';if(/\b(market|markets|apy|yield|tvl|morpho|opportunit|analy[sz]e|price)\b/.test(s))return'market';return'help';}
async function serverPlan(command,wallet){const r=await fetch('/api/agent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({command,wallet})});const data=await r.json();if(!r.ok||data.ok===false)throw new Error(data.error||'Agent API failed');return data;}
async function quoteBridge(body){const r=await fetch('/api/agent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operation:'bridge-quote',...body})});const data=await r.json();if(!r.ok||data.ok===false)throw new Error(data.error||'Bridge adapter failed');return data;}

async function prepareNativeSend(command,from){const recipient=addresses(command).at(-1);const qty=amount(command);if(!recipient||!qty)throw new Error('Send needs an amount and recipient address.');return adapterRegistry.get('native-eth').prepare({from,to:recipient,amountWei:parseUnits(qty,18)});}
async function prepareTokenSend(command,from){const a=addresses(command);const qty=amount(command);if(a.length<2||!qty)throw new Error('Token send needs token contract, recipient and amount.');const decimals=await getDecimals(a[0]);return adapterRegistry.get('erc20').prepare({from,token:a[0],to:a.at(-1),amount:parseUnits(qty,decimals)});}
async function prepareSwap(command,from){const a=addresses(command);const qty=amount(command);if(!from||!qty)throw new Error('Swap needs a connected wallet and amount.');const nativeIn=NATIVE.test(command);const nativeOut=/\b(to|for|into)\s+(eth|native|rbh|ether)\b/i.test(command);if(nativeIn&&nativeOut)throw new Error('Choose different input and output assets.');let tokenIn=a[0];let tokenOut=a[1];if(nativeIn){if(!tokenOut)throw new Error('Swap ETH into a token contract address.');}else if(nativeOut){if(!tokenIn)throw new Error('Swap a token contract address into ETH.');}else if(a.length<2)throw new Error('Swap needs tokenIn and tokenOut contract addresses.');const amountIn=nativeIn?qty:parseUnits(qty,await getDecimals(tokenIn));return adapterRegistry.get('uniswap-v2').prepare({from,tokenIn,tokenOut,amountIn,slippageBps:100,nativeIn,nativeOut});}
async function validatePlan(plan){if(!plan?.transactions?.length)throw new Error('Adapter returned an empty transaction plan.');const transactions=await Promise.all(plan.transactions.map(async(tx,index)=>{if(index>0)return{...tx,simulation:{ok:true,skipped:true,reason:'Prerequisite transaction must execute first.'}};try{return{...tx,simulation:await simulateTransaction({from:plan.from,to:tx.to,data:tx.data||'0x',value:tx.value||0n})};}catch(error){throw new Error(`Transaction simulation failed: ${error.message}`);}}));return{...plan,transactions,state:'simulated'};}

export async function planCommand({command,wallet}){const normalized=normalizeCommand(command);const intent=detectIntent(normalized);if(!normalized)return{status:'needs-input',intent:'help',message:'Tell me what you want to execute.'};const from=wallet||getConnectedAddress();if(intent==='send'){if(!from)throw new Error('Connect your wallet first.');return{status:'ready',intent,execution:await validatePlan(NATIVE.test(normalized)?await prepareNativeSend(normalized,from):await prepareTokenSend(normalized,from))};}if(intent==='swap'){if(!from)throw new Error('Connect your wallet first.');return{status:'ready',intent,execution:await validatePlan(await prepareSwap(normalized,from))};}if(intent==='bridge'){const a=addresses(normalized);const qty=amount(normalized);const chains=String(normalized).match(/\b\d{2,6}\b/g)||[];if(!from)throw new Error('Connect your wallet first.');if(a.length<2||chains.length<2||!qty)throw new Error('Bridge needs amount, source token, destination token, source chain ID and destination chain ID.');return{status:'ready',intent,execution:await quoteBridge({wallet:from,tokenIn:a[0],tokenOut:a[1],amount:qty,originChain:chains[0],destinationChain:chains[1],recipient:from})};}return serverPlan(normalized,from);}

export async function executePreparedPlan(plan){if(!plan)throw new Error('No execution plan.');if(plan.execution?.execute)return plan.execution.execute();const execution=plan.execution||plan;if(!execution.transactions?.length)throw new Error(execution.message||'No executable transaction plan was produced.');const provider=getActiveProvider();if(!provider?.request)throw new Error('Connected wallet provider is unavailable.');const submitted=await submitPlan(execution,provider);const receipts=[];for(const hash of submitted.hashes||[])receipts.push(await waitForReceipt(hash));return{hashes:submitted.hashes,receipts,adapter:execution.adapter,metadata:execution.metadata,quote:execution.quote,quoteId:execution.quoteId};}

export { detectIntent, normalizeCommand, addresses, amount };
