import { adapterRegistry } from './adapters/index.js';
import { keccak256, stringToHex } from 'viem';
import { discover as discoverMorpho } from './integrations/morpho.js';
import { status as lighterStatus } from './integrations/lighter.js';
import { stockTokenAssets, stockTokenPrices } from './integrations/robinhoodStockTokens.js';
import { chainHealth } from './integrations/robinhoodChain.js';

const RPC_URL='https://rpc.mainnet.chain.robinhood.com';
const EXPLORER_API='https://robinhoodchain.blockscout.com/api/v2';
const ADDRESS=/^0x[0-9a-fA-F]{40}$/;
const TX_HASH=/^0x[0-9a-fA-F]{64}$/;
const short=(a)=>a?`${a.slice(0,6)}…${a.slice(-4)}`:'';
const weiToEth=(v)=>Number(BigInt(v||'0'))/1e18;
const workflowStages=['Discover','Prepare','Review','Ask for approval','Execute','Verify'];
const approvalTopic=keccak256(stringToHex('Approval(address,uint256)'));

async function rpc(method,params=[]){const r=await fetch(RPC_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method,params})});if(!r.ok)throw new Error(`Robinhood RPC returned ${r.status}`);const j=await r.json();if(j.error)throw new Error(j.error.message||'RPC request failed');return j.result;}
async function explorer(path){const r=await fetch(`${EXPLORER_API}${path}`);if(!r.ok)throw new Error(`Explorer returned ${r.status}`);return r.json();}
async function walletSnapshot(address){const [balance,txs,tokens,nfts]=await Promise.allSettled([rpc('eth_getBalance',[address,'latest']),explorer(`/addresses/${address}/transactions?items_count=5`),explorer(`/addresses/${address}/tokens?type=ERC-20&items_count=20`),explorer(`/addresses/${address}/nft/collections?items_count=20`)]);const tokenItems=tokens.status==='fulfilled'?(tokens.value.items||[]).filter(x=>x.token?.type==='ERC-20'):[];const nftItems=nfts.status==='fulfilled'?(nfts.value.items||[]):[];return{address,balance:balance.status==='fulfilled'?weiToEth(balance.value):null,transactions:txs.status==='fulfilled'?(txs.value.items||[]).length:null,transactionItems:txs.status==='fulfilled'?(txs.value.items||[]).slice(0,5):[],tokens:tokenItems.length,tokenHoldings:tokenItems.slice(0,12).map(x=>({symbol:x.token?.symbol||'UNKNOWN',name:x.token?.name||'',balance:x.value??x.balance??null,decimals:x.token?.decimals??18,address:x.token?.address||x.token?.hash||null})),nftCollections:nftItems.length,nfts:nftItems.slice(0,12).map(x=>({name:x.name||x.collection?.name||'NFT collection',address:x.address||x.collection?.address||null,count:x.amount??x.token_count??null}))};}
async function readApprovals(address){const latest=BigInt(await rpc('eth_blockNumber'));const from=latest>100000n?latest-100000n:0n;let logs=[];try{logs=await rpc('eth_getLogs',[{fromBlock:`0x${from.toString(16)}`,toBlock:'latest',topics:[approvalTopic,`0x${address.slice(2).padStart(64,'0')}`]}]);}catch{logs=[];}const unique=new Map();for(const log of logs||[]){const spender=log.topics?.[2];if(!spender)continue;const key=`${log.address.toLowerCase()}:${spender.toLowerCase()}`;unique.set(key,{token:log.address,spender:`0x${spender.slice(-40)}`});}const active=[];for(const item of Array.from(unique.values()).slice(0,30)){try{const data=`0xdd62ed3e${address.slice(2).padStart(64,'0')}${item.spender.slice(2).padStart(64,'0')}`;const result=await rpc('eth_call',[{to:item.token,data},'latest']);const allowance=BigInt(result||'0');if(allowance>0n)active.push({...item,allowance:allowance.toString()});}catch{}}return{address,scannedBlocks:`${from.toString()}–${latest.toString()}`,activeApprovals:active};}
async function marketSnapshot(symbol='BTC/USDT',timeframe='4H'){const r=await fetch(`/api/market?${new URLSearchParams({symbol,timeframe})}`);if(!r.ok)throw new Error(`Market adapter returned ${r.status}`);return r.json();}
async function perpetualSnapshot(symbol='BTC/USDT',timeframe='4H'){const r=await fetch(`/api/perpetual?${new URLSearchParams({symbol,timeframe})}`);if(!r.ok)throw new Error(`Perpetual adapter returned ${r.status}`);return r.json();}
async function transactionSnapshot(wallet,requestedHash=''){if(!wallet&&!requestedHash)throw new Error('Connect a wallet or provide a transaction hash.');if(requestedHash){if(!TX_HASH.test(requestedHash))throw new Error('That transaction hash is not valid.');const tx=await explorer(`/transactions/${requestedHash}`);let receipt=null;try{receipt=await rpc('eth_getTransactionReceipt',[requestedHash]);}catch{}return{hash:requestedHash,transaction:tx,receipt};}const data=await explorer(`/addresses/${wallet}/transactions?items_count=5`);const items=data.items||[];if(!items.length)return{hash:null,transaction:null,receipt:null};const latest=items[0];const hash=latest.hash||latest.transaction_hash||latest.tx_hash;if(!hash)return{hash:null,transaction:latest,receipt:null};let receipt=null;try{receipt=await rpc('eth_getTransactionReceipt',[hash]);}catch{}return{hash,transaction:latest,receipt};}
const discovery=(message,data,stages=['Discover','Review'])=>({kind:'discovery',message,data,stages});
const workflow=(action,message,execution='adapter-required')=>({kind:'prepare',action:{...action,execution},message,stages:workflowStages});

export async function executeAgent(text,{wallet='',pair='BTC/USDT',timeframe='4H'}={}){
 const input=text.trim(),lower=input.toLowerCase();if(!input)return{kind:'empty',message:'Tell KitAgent what needs to happen. I will inspect live context, prepare the exact action, ask before execution, then verify it.',stages:workflowStages};
 if(/\b(what can you do|help|capabilit|how do you work|what are you)\b/.test(lower))return{kind:'help',message:'I can inspect live wallet, NFT and token state, scan recent approvals, analyze markets, query Robinhood Chain DeFi and perps, discover faucets, bridges, NFT venues and airdrop sources, and execute supported on-chain actions through real adapters. Consequential actions always stop for your approval before the wallet signs.',stages:workflowStages};
 if(/\b(track|verify)\b.*\b(transaction|tx|hash)\b|\b(last|latest)\s+transaction\b|\bverify my last transaction\b/.test(lower)){const requested=input.match(/\b0x[0-9a-fA-F]{64}\b/)?.[0];if(!wallet&&!requested)return{kind:'transaction',message:'Connect a wallet and I will inspect its latest transaction, or paste a 0x transaction hash to verify a specific transaction.',stages:['Connect wallet','Find transaction','Verify receipt']};const data=await transactionSnapshot(wallet,requested);if(!data.hash)return{kind:'transaction',data,message:`No recent transaction was found for ${short(wallet)} on Robinhood Chain.`,stages:['Scan wallet history','No transaction found']};const receiptStatus=data.receipt?.status;const confirmed=receiptStatus==='0x1'||receiptStatus===1||data.transaction?.status==='ok'||data.transaction?.status==='success';const failed=receiptStatus==='0x0'||receiptStatus===0||data.transaction?.status==='error'||data.transaction?.status==='failed';return{kind:'transaction',data,message:`${requested?'Transaction':'Latest transaction'} ${short(data.hash)} ${confirmed?'is confirmed and successful.':failed?'failed on-chain.':'was found; the receipt is still pending or unavailable.'}`,stages:['Find transaction','Read explorer record','Verify receipt']};}
 if(/\b(prepare|swap|exchange|trade)\b/.test(lower)&&/\bswap\b/.test(lower)&&!/\b\d+(?:\.\d+)?\s*eth\b/i.test(input)&&!ADDRESS.test(input.match(/\b0x[0-9a-fA-F]{40}\b/)?.[0]||''))return{kind:'clarify',message:'I can prepare a real swap, but I need the asset pair and amount first. Example: “swap 0.01 ETH for 0xTOKEN_ADDRESS”. I will quote and simulate it before asking for wallet approval.',stages:['Understand request','Missing swap amount','Missing token route']};
 if(/\b(check my nft collection|show my nft holdings|my nft collection|nft holdings)\b/.test(lower)){if(!wallet)return{kind:'wallet',message:'Connect a wallet first. I will then inspect its NFT collections directly on Robinhood Chain.',stages:['Connect wallet','Scan NFT collections','Display holdings']};const s=await walletSnapshot(wallet);return{kind:'nft',data:{address:s.address,nftCollections:s.nftCollections,nfts:s.nfts},message:`Scanned ${short(wallet)} on Robinhood Chain. Found ${s.nftCollections??0} NFT collections. Read-only; nothing was transferred or listed.`,stages:['Scan wallet','Read NFT collections','Display holdings']};}
 if(/\b(review my token approvals|token approvals|approvals)\b/.test(lower)){if(!wallet)return{kind:'wallet',message:'Connect a wallet first. I will scan recent ERC-20 Approval activity and verify which allowances are still active.',stages:['Connect wallet','Scan approval events','Verify allowances']};const data=await readApprovals(wallet);return discovery(data.activeApprovals.length?`Found ${data.activeApprovals.length} active ERC-20 allowance(s) in the recent approval scan.`:'No active ERC-20 allowances were found in the recent approval scan.',data,['Scan approval events','Verify current allowances','Display risk']);}
 if(/\b(show my token holdings|token holdings|show my live wallet balance|show my recent transactions|check my wallet|wallet balance|portfolio|holdings|tokens|assets|positions|transactions|recent activity)\b/.test(lower)){if(!wallet)return{kind:'wallet',message:'Connect a wallet and I can inspect its live Robinhood Chain state. Inspection is read-only.',stages:['Connect wallet','Inspect live state','Display results']};const s=await walletSnapshot(wallet);return{kind:'wallet',data:s,message:`Live wallet scan for ${short(wallet)}: ${s.balance==null?'balance unavailable':`${s.balance.toFixed(5)} ETH`}, ${s.tokens} token holdings, ${s.nftCollections} NFT collections and ${s.transactions??'unavailable'} recent transactions. Read-only.`,stages:['Inspect live wallet','Read indexed assets','Display results']};}
 if(/\b(chain health|network status|robinhood chain status|rpc status|check my robinhood chain gas)\b/.test(lower)){const data=await chainHealth();return discovery(`Robinhood Chain is reachable. Chain ${data.chainId}, latest block ${data.blockNumber}.`,data,['Check RPC','Verify chain','Display health']);}
 if(/\b(find my best defi opportunity|morpho|lending markets|lending opportunities|best lending|yield opportunities|vaults)\b/.test(lower)){const data=await discoverMorpho();return discovery('Scanning live Morpho markets and vaults on Robinhood Chain. I will rank the returned opportunities without inventing APYs or risk data.',data,['Scan Morpho','Compare markets','Review risk']);}
 if(/\b(lighter|perp venues|perpetual venues|perps status)\b/.test(lower)){const data=await lighterStatus();return discovery('Lighter has a dedicated Robinhood Chain instance. I can use its live API surface for discovery and market data, then require wallet approval for consequential actions.',data,['Check Lighter','Inspect live API','Review before trade']);}
 if(/\b(stock token|tokenized stock|equity token|rwa|real world asset|aapl|tsla|nvda|msft|amzn|googl)\b/.test(lower)){const symbol=input.match(/\b(AAPL|TSLA|NVDA|MSFT|AMZN|GOOGL)\b/i)?.[1];const data=symbol?await stockTokenPrices(symbol):await stockTokenAssets();return discovery(symbol?`Live Robinhood Stock Token quote for ${symbol.toUpperCase()} is available.`:'Live Robinhood Stock Token assets are available on Robinhood Chain.',data,['Query Robinhood data','Review token state','Read-only']);}
 if(/\b(find active faucets|faucets?|get me faucet gas|testnet gas)\b/.test(lower)){const data=await adapterRegistry.get('discovery').discover({kind:'faucet'});return discovery('The official Robinhood Chain faucet is for testnet ETH. Mainnet gas is ETH and is not dispensed by that faucet. I found the faucet destination; nothing was submitted.',data,['Discover faucet','Check network','No execution']);}
 if(/\b(find airdrops|airdrop|claim.*airdrop|eligible.*airdrop)\b/.test(lower)){const data=await adapterRegistry.get('discovery').discover({kind:'airdrop'});return discovery('Scanning supported airdrop sources. I will only present a claim when the campaign, eligibility rule and claim contract can be verified; otherwise I will clearly mark it unverified.',data,['Discover campaigns','Check eligibility','Verify claim source']);}
 if(/\b(sell.*nft|list.*nft|buy.*nft|nft marketplace|nft market)\b/.test(lower)){const data=await adapterRegistry.get('discovery').discover({kind:'nft-marketplace'});return discovery('Scanning live NFT venues on Robinhood Chain. I will inspect the asset and marketplace route before preparing a listing or sale.',data,['Discover NFT venues','Inspect asset','Prepare marketplace route']);}
 if(/\b(bridge|move.*chain|cross.?chain)\b/.test(lower)){const data=await adapterRegistry.get('discovery').discover({kind:'bridge'});return discovery('Scanning supported Robinhood Chain bridge routes. No bridge transaction is prepared until a route, asset and destination are known.',data,['Discover bridge routes','Compare route','Await executable route']);}
 if(/\b(stake|staking|lend|lending|borrow|borrowing|defi|liquidity|yield)\b/.test(lower)){const data=await adapterRegistry.get('discovery').discover({kind:'defi'});return discovery('Scanning live DeFi protocol surfaces on Robinhood Chain. I will not claim an action is executable until its adapter can quote, simulate and build exact calldata.',data,['Discover protocol','Review risk','Await executable adapter']);}
 if(/\b(analy[sz]e|price|market|btc|eth|sol|xrp|bnb|doge|ada|avax|link|dot|trx|uni|aave|arb|op|sui|pepe|signal|setup|technical)\b/.test(lower)){const symbol=(input.match(/\b(BTC|ETH|SOL|XRP|BNB|DOGE|ADA|AVAX|LINK|DOT|TRX|UNI|AAVE|ARB|OP|SUI|PEPE)\s*\/?\s*USDT\b/i)?.[1]||pair.split('/')[0]).toUpperCase()+'/USDT';const tf=input.match(/\b(15m|30m|1h|4h|1d|1w)\b/i)?.[1]||timeframe;const data=await marketSnapshot(symbol,tf);return{kind:'market',data,message:`Live ${symbol} ${tf} market analysis is ready. Analysis is read-only.`,stages:['Fetch live market','Analyze structure','Display thesis']};}
 if(/\b(perpetual|perp|futures)\b/.test(lower)){const symbol=(input.match(/\b(BTC|ETH|SOL|XRP|BNB|DOGE|ADA|AVAX|LINK|DOT|TRX|UNI|AAVE|ARB|OP|SUI|PEPE)\s*\/?\s*USDT\b/i)?.[1]||'BTC').toUpperCase()+'/USDT';const tf=input.match(/\b(15m|30m|1h|4h|1d|1w)\b/i)?.[1]||timeframe;const data=await perpetualSnapshot(symbol,tf);return{kind:'perpetual',data,message:`Live perpetual data for ${symbol} ${tf} is ready. No order is submitted without a real order adapter and your approval.`,stages:['Fetch live perpetual','Analyze setup','Display thesis']};}
 const transferMatch=input.match(/\b(?:send|transfer|pay)\s+(\d+(?:\.\d+)?)\s*(?:eth)?\s+(?:to\s+)?(0x[0-9a-fA-F]{40})\b/i);if(transferMatch)return workflow({kind:'native-send',title:'Send ETH',summary:`Send ${transferMatch[1]} ETH to ${short(transferMatch[2])} on Robinhood Chain.`,amount:transferMatch[1],to:transferMatch[2],risk:'Native asset leaves the connected wallet only after approval.'},'I found the amount and destination. I will simulate, estimate gas, ask for approval, then send and verify.','native-transfer');
 const tokenApprove=input.match(/\b(?:approve|allow)\b.*?\b(0x[0-9a-fA-F]{40})\b(?:.*?\bfor\b\s*)?(0x[0-9a-fA-F]{40})\b.*?\b(\d+)\b/i);if(tokenApprove)return workflow({kind:'token-approve',title:'Approve ERC-20 spending',summary:'Prepare an exact token approval.',token:tokenApprove[1],spender:tokenApprove[2],amount:tokenApprove[3],risk:'Token approval can authorize spending.'},'I found the token, spender and base-unit amount. I will simulate and ask before signing.','token-approve');
 const nativeSwap=input.match(/\b(?:swap|exchange|trade)\s+(\d+(?:\.\d+)?)\s*ETH\s+(?:to|for)\s+(0x[0-9a-fA-F]{40})\b/i);if(nativeSwap)return workflow({kind:'swap',title:'Swap ETH on Uniswap',summary:`Swap ${nativeSwap[1]} ETH for ${short(nativeSwap[2])} using the live Robinhood Chain Uniswap adapter.`,nativeIn:true,nativeOut:false,amountIn:nativeSwap[1],tokenOut:nativeSwap[2],slippageBps:50,risk:'Live DEX swap; review quote, slippage, route and gas.'},'I can build a real Uniswap transaction on Robinhood Chain. I will quote it, prepare calldata, simulate it, show the output and slippage, then ask for wallet approval.','uniswap-v2');
 const tokenSwap=input.match(/\b(?:swap|exchange|trade)\s+(\d+)\s+(0x[0-9a-fA-F]{40})\s+(?:to|for)\s+(0x[0-9a-fA-F]{40})\b/i);if(tokenSwap)return workflow({kind:'swap',title:'Swap tokens on Uniswap',summary:`Swap token ${short(tokenSwap[2])} for ${short(tokenSwap[3])}.`,nativeIn:false,nativeOut:false,amountIn:tokenSwap[1],tokenIn:tokenSwap[2],tokenOut:tokenSwap[3],slippageBps:50,risk:'Live DEX swap; an approval may be required first.'},'I found both token contracts and the base-unit amount. I will quote and prepare a real Uniswap transaction, simulate it, then ask for approval.','uniswap-v2');
 const nftTransfer=input.match(/\btransfer\s+nft\s+(0x[0-9a-fA-F]{40})\s+#?(\d+)\s+to\s+(0x[0-9a-fA-F]{40})\b/i);if(nftTransfer)return workflow({kind:'nft-transfer',title:'Transfer NFT',summary:`Transfer NFT ${short(nftTransfer[1])} #${nftTransfer[2]} to ${short(nftTransfer[3])}.`,token:nftTransfer[1],tokenId:nftTransfer[2],to:nftTransfer[3],risk:'NFT transfer is irreversible after confirmation.'},'I found the NFT contract, token ID and recipient. I will prepare the ERC-721 transaction, simulate it, then ask before signing.','erc721');
 return{kind:'help',message:'I can work across live wallet state, NFTs, approvals, DeFi, markets, faucets, airdrop discovery, bridges and supported on-chain actions. If a request cannot be executed safely, I will show exactly what is missing instead of pretending it worked.',stages:['Understand request','Discover context','Prepare when supported','Ask before execution','Execute','Verify']};
}
