import { adapterRegistry } from './adapters/index.js';
import { discover as discoverMorpho } from './integrations/morpho.js';
import { status as lighterStatus } from './integrations/lighter.js';
import { stockTokenAssets, stockTokenPrices } from './integrations/robinhoodStockTokens.js';
import { chainHealth } from './integrations/robinhoodChain.js';

const RPC_URL='https://rpc.mainnet.chain.robinhood.com';
const EXPLORER_API='https://robinhoodchain.blockscout.com/api/v2';
const ADDRESS=/^0x[0-9a-fA-F]{40}$/;
const short=(a)=>a?`${a.slice(0,6)}…${a.slice(-4)}`:'';
const weiToEth=(v)=>Number(BigInt(v||'0'))/1e18;
const workflowStages=['Discover','Prepare','Review','Ask for approval','Execute','Verify'];
async function rpc(method,params=[]){const r=await fetch(RPC_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method,params})});if(!r.ok)throw new Error(`Robinhood RPC returned ${r.status}`);const j=await r.json();if(j.error)throw new Error(j.error.message||'RPC request failed');return j.result;}
async function explorer(path){const r=await fetch(`${EXPLORER_API}${path}`);if(!r.ok)throw new Error(`Explorer returned ${r.status}`);return r.json();}
async function walletSnapshot(address){const [balance,txs,tokens,nfts]=await Promise.allSettled([rpc('eth_getBalance',[address,'latest']),explorer(`/addresses/${address}/transactions?items_count=5`),explorer(`/addresses/${address}/tokens?type=ERC-20&items_count=20`),explorer(`/addresses/${address}/nft/collections?items_count=10`)]);return{address,balance:balance.status==='fulfilled'?weiToEth(balance.value):null,transactions:txs.status==='fulfilled'?(txs.value.items||[]).length:null,tokens:tokens.status==='fulfilled'?(tokens.value.items||[]).filter(x=>x.token?.type==='ERC-20').length:null,nftCollections:nfts.status==='fulfilled'?(nfts.value.items||[]).length:null};}
async function marketSnapshot(symbol='BTC/USDT',timeframe='4H'){const r=await fetch(`/api/market?${new URLSearchParams({symbol,timeframe})}`);if(!r.ok)throw new Error(`Market adapter returned ${r.status}`);return r.json();}
async function perpetualSnapshot(symbol='BTC/USDT',timeframe='4H'){const r=await fetch(`/api/perpetual?${new URLSearchParams({symbol,timeframe})}`);if(!r.ok)throw new Error(`Perpetual adapter returned ${r.status}`);return r.json();}
const discovery=(message,data,stages=['Discover','Review'])=>({kind:'discovery',message,data,stages});
const workflow=(action,message,execution='adapter-required')=>({kind:'prepare',action:{...action,execution},message,stages:workflowStages});
export async function executeAgent(text,{wallet='',pair='BTC/USDT',timeframe='4H'}={}){
 const input=text.trim(),lower=input.toLowerCase();if(!input)return{kind:'empty',message:'Tell me the outcome you want. I will inspect live context, prepare the exact action, ask before execution, then verify it.',stages:workflowStages};
 if(/\b(what can you do|help|capabilit|how do you work|what are you)\b/.test(lower))return{kind:'help',message:'I can inspect live wallet state, markets, Robinhood Chain health and stock tokens; discover faucets, airdrops, bridges, NFT venues and DeFi; query Morpho and Lighter; and execute supported on-chain actions through real adapters. Consequential actions always stop for your approval before the wallet signs.',stages:workflowStages};
 if(/\b(chain health|network status|robinhood chain status|rpc status)\b/.test(lower)){const data=await chainHealth();return discovery(`Robinhood Chain is reachable. Chain ${data.chainId}, latest block ${data.blockNumber}.`,data,['Check RPC','Verify chain','Display health']);}
 if(/\b(morpho|lending markets|lending opportunities|best lending|yield opportunities|vaults)\b/.test(lower)){const data=await discoverMorpho();return discovery('Live Morpho market and vault data is available on Robinhood Chain. I am showing discovery data only; no supply, borrow or vault transaction is being prepared without a specific protocol action.',data,['Query Morpho','Compare markets','Review risk']);}
 if(/\b(lighter|perp venues|perpetual venues|perps status)\b/.test(lower)){const data=await lighterStatus();return discovery('Lighter has a dedicated Robinhood Chain instance. I can use its live API surface for discovery and market data, then require wallet approval for consequential actions.',data,['Check Lighter','Inspect live API','Review before trade']);}
 if(/\b(stock token|tokenized stock|equity token|rwa|real world asset|aapl|tsla|nvda|msft|amzn|googl)\b/.test(lower)){const symbol=input.match(/\b(AAPL|TSLA|NVDA|MSFT|AMZN|GOOGL)\b/i)?.[1];const data=symbol?await stockTokenPrices(symbol):await stockTokenAssets();return discovery(symbol?`Live Robinhood Stock Token quote for ${symbol.toUpperCase()} is available.`:'Live Robinhood Stock Token assets are available on Robinhood Chain.',data,['Query Robinhood data','Review token state','Read-only']);}
 if(/\b(find active faucets|faucets?|get me faucet gas|testnet gas)\b/.test(lower)){const data=await adapterRegistry.get('discovery').discover({kind:'faucet'});return discovery('I found the official Robinhood Chain testnet faucet. Mainnet gas is not dispensed by a faucet; the faucet is for testnet ETH. Nothing was submitted.',data,['Discover faucet','Show destination','No execution']);}
 if(/\b(find airdrops|airdrop|claim.*airdrop|eligible.*airdrop)\b/.test(lower)){const data=await adapterRegistry.get('discovery').discover({kind:'airdrop'});return discovery('I can discover supported airdrop sources, but I will not invent eligibility or fabricate a claim transaction. I will show the source first, then prepare a real claim only when a verified claim contract is available.',data,['Discover sources','Check eligibility','Review before claim']);}
 if(/\b(sell.*nft|list.*nft|buy.*nft|nft marketplace|nft market)\b/.test(lower)){const data=await adapterRegistry.get('discovery').discover({kind:'nft-marketplace'});return discovery('I found live NFT venues on Robinhood Chain. I will not pretend a listing is executable until the marketplace order contract and signed order data are available. Choose a venue or give me the NFT contract and token ID.',data,['Discover NFT venues','Review marketplace','Await NFT details']);}
 if(/\b(bridge|move.*chain|cross.?chain)\b/.test(lower)){const data=await adapterRegistry.get('discovery').discover({kind:'bridge'});return discovery('I found the official Robinhood Chain bridge routes. Bridge execution is route-specific, so I will only submit after the route and calldata are available.',data,['Discover bridge routes','Review route','Await executable route']);}
 if(/\b(stake|staking|lend|lending|borrow|borrowing|defi|liquidity|yield)\b/.test(lower)){const data=await adapterRegistry.get('discovery').discover({kind:'defi'});return discovery('I found live DeFi protocol surfaces on Robinhood Chain. Morpho market/vault data is also available, but I will not claim a DeFi action is executable until its protocol adapter can quote, simulate and build the exact calldata.',data,['Discover protocol','Review risk','Await executable adapter']);}
 if(/\b(balance|portfolio|wallet|holdings|tokens|assets|positions|approvals|transactions|recent activity)\b/.test(lower)){if(!wallet)return{kind:'wallet',message:'Connect a wallet and I can inspect its live Robinhood Chain state. Inspection is read-only.',stages:['Connect wallet','Inspect live state','Display results']};const s=await walletSnapshot(wallet);return{kind:'wallet',data:s,message:`Live wallet state for ${short(wallet)}: ${s.balance==null?'balance unavailable':`${s.balance.toFixed(5)} ETH`}, ${s.tokens??'token data unavailable'} token holdings, ${s.nftCollections??'NFT'} NFT collections and ${s.transactions??'transaction'} recent transactions. Read-only.`,stages:['Inspect live wallet','Display results','Ready for next action']};}
 if(/\b(analy[sz]e|price|market|btc|eth|sol|xrp|bnb|doge|ada|avax|link|dot|trx|uni|aave|arb|op|sui|pepe|signal|setup|technical)\b/.test(lower)){const symbol=(input.match(/\b(BTC|ETH|SOL|XRP|BNB|DOGE|ADA|AVAX|LINK|DOT|TRX|UNI|AAVE|ARB|OP|SUI|PEPE)\s*\/?\s*USDT\b/i)?.[1]||pair.split('/')[0]).toUpperCase()+'/USDT';const tf=input.match(/\b(15m|30m|1h|4h|1d|1w)\b/i)?.[1]||timeframe;const data=await marketSnapshot(symbol,tf);return{kind:'market',data,message:`Live ${symbol} ${tf} market analysis is ready. Analysis is read-only.`,stages:['Fetch live market','Analyze structure','Display thesis']};}
 if(/\b(perpetual|perp|futures)\b/.test(lower)){const symbol=(input.match(/\b(BTC|ETH|SOL|XRP|BNB|DOGE|ADA|AVAX|LINK|DOT|TRX|UNI|AAVE|ARB|OP|SUI|PEPE)\s*\/?\s*USDT\b/i)?.[1]||'BTC').toUpperCase()+'/USDT';const tf=input.match(/\b(15m|30m|1h|4h|1d|1w)\b/i)?.[1]||timeframe;const data=await perpetualSnapshot(symbol,tf);return{kind:'perpetual',data,message:`Live perpetual data for ${symbol} ${tf} is ready. No order is submitted without a real order adapter and your approval.`,stages:['Fetch live perpetual','Analyze setup','Display thesis']};}
 const transferMatch=input.match(/\b(?:send|transfer|pay)\s+(\d+(?:\.\d+)?)\s*(?:eth)?\s+(?:to\s+)?(0x[0-9a-fA-F]{40})\b/i);if(transferMatch)return workflow({kind:'native-send',title:'Send ETH',summary:`Send ${transferMatch[1]} ETH to ${short(transferMatch[2])} on Robinhood Chain.`,amount:transferMatch[1],to:transferMatch[2],risk:'Native asset leaves the connected wallet only after approval.'},'I found the amount and destination. I will simulate, estimate gas, ask for approval, then send and verify.','native-transfer');
 const tokenApprove=input.match(/\b(?:approve|allow)\b.*?\b(0x[0-9a-fA-F]{40})\b(?:.*?\bfor\b\s*)?(0x[0-9a-fA-F]{40})\b.*?\b(\d+)\b/i);if(tokenApprove)return workflow({kind:'token-approve',title:'Approve ERC-20 spending',summary:'Prepare an exact token approval.',token:tokenApprove[1],spender:tokenApprove[2],amount:tokenApprove[3],risk:'Token approval can authorize spending.'},'I found the token, spender and base-unit amount. I will simulate and ask before signing.','token-approve');
 const nativeSwap=input.match(/\b(?:swap|exchange|trade)\s+(\d+(?:\.\d+)?)\s*ETH\s+(?:to|for)\s+(0x[0-9a-fA-F]{40})\b/i);if(nativeSwap)return workflow({kind:'swap',title:'Swap ETH on Uniswap',summary:`Swap ${nativeSwap[1]} ETH for ${short(nativeSwap[2])} using the live Robinhood Chain Uniswap adapter.`,nativeIn:true,nativeOut:false,amountIn:nativeSwap[1],tokenOut:nativeSwap[2],slippageBps:50,risk:'Live DEX swap; review quote, slippage, route and gas.'},'I can build a real Uniswap transaction on Robinhood Chain. I will quote it, prepare calldata, simulate it, show the output and slippage, then ask for wallet approval.','uniswap-v2');
 const tokenSwap=input.match(/\b(?:swap|exchange|trade)\s+(\d+)\s+(0x[0-9a-fA-F]{40})\s+(?:to|for)\s+(0x[0-9a-fA-F]{40})\b/i);if(tokenSwap)return workflow({kind:'swap',title:'Swap tokens on Uniswap',summary:`Swap token ${short(tokenSwap[2])} for ${short(tokenSwap[3])}.`,nativeIn:false,nativeOut:false,amountIn:tokenSwap[1],tokenIn:tokenSwap[2],tokenOut:tokenSwap[3],slippageBps:50,risk:'Live DEX swap; an approval may be required first.'},'I found both token contracts and the base-unit amount. I will quote and prepare a real Uniswap transaction, simulate it, then ask for approval.','uniswap-v2');
 const nftTransfer=input.match(/\btransfer\s+nft\s+(0x[0-9a-fA-F]{40})\s+#?(\d+)\s+to\s+(0x[0-9a-fA-F]{40})\b/i);if(nftTransfer)return workflow({kind:'nft-transfer',title:'Transfer NFT',summary:`Transfer NFT ${short(nftTransfer[1])} #${nftTransfer[2]} to ${short(nftTransfer[3])}.`,token:nftTransfer[1],tokenId:nftTransfer[2],to:nftTransfer[3],risk:'NFT transfer is irreversible after confirmation.'},'I found the NFT contract, token ID and recipient. I will prepare the ERC-721 transaction, simulate it, then ask before signing.','erc721');
 return{kind:'help',message:'I understand natural-language requests, but I will not fake an adapter. Try “find active faucets”, “show lending opportunities”, “check Lighter”, “show AAPL stock token”, “swap 0.01 ETH to 0x…”, “transfer NFT 0x… #1 to 0x…”, “send 0.1 ETH to 0x…”, or a market analysis.',stages:['Understand request','Discover context','Prepare when supported','Ask before execution','Execute','Verify']};
}
