import React,{useState} from 'react';
import {createUserWithEmailAndPassword,signInWithEmailAndPassword,sendPasswordResetEmail} from 'firebase/auth';
import {auth} from './lib/firebase.js';
import {securityHeaders} from './lib/device-security.js';

export default function AuthPage({onAuthed}){
  const[signup,setSignup]=useState(false);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
  async function submit(e){e.preventDefault();setError('');setMessage('');if(signup&&password!==confirm)return setError('Passwords do not match.');if(password.length<8)return setError('Use at least 8 characters.');setBusy(true);try{const cred=signup?await createUserWithEmailAndPassword(auth,email.trim(),password):await signInWithEmailAndPassword(auth,email.trim(),password);const token=await cred.user.getIdToken(true);const headers=await securityHeaders(token);const r=await fetch('/api/security/register',{method:'POST',headers,body:JSON.stringify({email:cred.user.email})});const d=await r.json().catch(()=>({}));if(!r.ok){if(signup&&cred.user)try{await cred.user.delete()}catch{}throw new Error(d.error||'This device is already linked to another KitAgent account.')}setMessage(signup?'Account created. Your 3-day trading trial is active.':'Welcome back.');onAuthed?.(cred.user)}catch(err){setError(err?.message||'Authentication failed.')}finally{setBusy(false)}}
  async function reset(){setError('');setMessage('');if(!email.trim())return setError('Enter your email first.');try{await sendPasswordResetEmail(auth,email.trim());setMessage('Password reset email sent.')}catch(err){setError(err?.message||'Could not send reset email.')}}
  return <div className="auth-screen"><div className="auth-glow"/><div className="auth-card"><div className="auth-brand"><img src="https://www.t3kit.xyz/assets/images/logo.webp" alt="T3Kit"/><span>KIT<span>AGENT</span></span></div><div className="auth-kicker">SECURE ACCESS</div><h1>{signup?'Create your account':'Welcome back'}</h1><p>{signup?'Start with a 3-day free Trading Layer trial. The Terminal stays free.':'Sign in to continue to your KitAgent terminal and trading layer.'}</p><form onSubmit={submit}><label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label><label>Password<input type="password" autoComplete={signup?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" required minLength={8}/></label>{signup&&<label>Confirm password<input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="••••••••" required minLength={8}/></label>}<button className="auth-submit" disabled={busy}>{busy?'SECURING ACCOUNT…':signup?'CREATE ACCOUNT':'SIGN IN'} <span>↗</span></button></form>{!signup&&<button className="auth-reset" onClick={reset}>Forgot password?</button>}{error&&<div className="auth-error">{error}</div>}{message&&<div className="auth-success">{message}</div>}<div className="auth-switch"><span>{signup?'Already have an account?':'New to KitAgent?'}</span><button onClick={()=>{setSignup(v=>!v);setError('');setMessage('')}}>{signup?'Sign in':'Create account'}</button></div><div className="auth-security"><span>◇</span> One account per registered device · secure session controls</div></div></div>;
}
