import { cloneElement, useEffect, useRef, useState } from 'react';
import { browserLocalPersistence, onAuthStateChanged, setPersistence, signInWithCustomToken, signInWithEmailAndPassword, updateProfile } from 'firebase/auth';
import { getToken } from 'firebase/app-check';
import { doc, getDoc, setDoc, serverTimestamp } from 'firebase/firestore';
import { ShieldCheck, LoaderCircle, LogIn, UserPlus, Eye, EyeOff } from 'lucide-react';
import { auth, db, appCheck, firebaseConfigured } from './firebase.js';
import { getDeviceBindingId } from './deviceBinding.js';

function makeUsername(email,uid){const base=(email||'user').split('@')[0].toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,18)||'user';const suffix=(uid||'').replace(/[^a-z0-9]/gi,'').slice(-5).toLowerCase()||Math.random().toString(36).slice(2,7);return `${base}-${suffix}`}
function makeAvatar(username){const seed=encodeURIComponent(`kitsetups-${username||Math.random().toString(36).slice(2)}`);return `https://api.dicebear.com/9.x/adventurer/svg?seed=${seed}&backgroundType=gradientLinear&radius=24&size=96`}
async function registerDevice(user){const deviceId=await getDeviceBindingId();const token=await user.getIdToken();const response=await fetch('/api/register-device',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({deviceId})});let payload={};try{payload=await response.json()}catch{}if(!response.ok)throw new Error(payload.error||'This device cannot be registered.');return deviceId}
async function getAppCheckHeaders(){if(!appCheck)return {};const token=await getToken(appCheck);return {'X-Firebase-AppCheck':token.token}}
async function initializeAccount(user){
 if(!db)throw new Error('KitSetups database is not configured.');
 const ref=doc(db,'users',user.uid);const snapshot=await getDoc(ref);const existing=snapshot.exists()?(snapshot.data()||{}):{};const isNew=!snapshot.exists();
 const username=existing.username||makeUsername(user.email||existing.email,user.uid);
 const existingPhoto=existing.photoURL||'';const photoURL=existingPhoto&&!existingPhoto.startsWith('data:image/svg+xml')?existingPhoto:(user.photoURL||makeAvatar(username));
 if(user.displayName!==username||user.photoURL!==photoURL){try{await updateProfile(user,{displayName:username,photoURL})}catch(error){console.warn('KitSetups profile update deferred:',error)}}
 const trialPatch=isNew?{plan:'free',trialStartedAt:serverTimestamp(),trialEndsAt:new Date(Date.now()+3*24*60*60*1000)}:(!existing.trialStartedAt||!existing.trialEndsAt)?{plan:existing.plan||'free',trialStartedAt:existing.trialStartedAt||serverTimestamp(),trialEndsAt:new Date(Date.now()+3*24*60*60*1000)}:{};
 await setDoc(ref,{uid:user.uid,email:user.email||existing.email||'',username,displayName:username,photoURL,emailVerified:Boolean(user.emailVerified),authProvider:'password',authProviders:['password'],walletAddress:existing.walletAddress||'',maxRiskPercent:existing.maxRiskPercent??1.5,maxTradeSize:existing.maxTradeSize??0,tradingPreferences:existing.tradingPreferences||{targetRiskReward:2.5},apiKeyMetadata:existing.apiKeyMetadata||{},...trialPatch,updatedAt:serverTimestamp()},{merge:true});
 try{const deviceBindingId=await registerDevice(user);await setDoc(ref,{securitySettings:{...(existing.securitySettings||{}),deviceBindingId},updatedAt:serverTimestamp()},{merge:true})}catch(error){console.error('KitSetups device registration deferred:',error)}
}

export default function AuthGate({children}){const [user,setUser]=useState(null),[ready,setReady]=useState(false),[mode,setMode]=useState('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[captchaToken,setCaptchaToken]=useState('');const captchaContainer=useRef(null);const captchaWidget=useRef(null);
 useEffect(()=>{if(!auth||!db){setReady(true);return undefined}let active=true;setPersistence(auth,browserLocalPersistence).catch(e=>console.error('KitSetups auth persistence setup failed:',e));const unsubscribe=onAuthStateChanged(auth,async next=>{if(!active)return;if(!next){setUser(null);setReady(true);return}try{await initializeAccount(next);if(!active)return;setUser(next);setReady(true)}catch(error){console.error('KitSetups account initialization failed:',error);if(!active)return;setUser(next);setReady(true)}});return()=>{active=false;unsubscribe()}},[]);
 useEffect(()=>{setCaptchaToken('');captchaWidget.current=null;if(mode!=='signup')return undefined;const siteKey=import.meta.env.VITE_RECAPTCHA_SITE_KEY||'';if(!siteKey){setMessage('reCAPTCHA is not configured for this deployment.');return undefined}let cancelled=false;let attempts=0;const renderCaptcha=()=>{if(cancelled||!captchaContainer.current)return;if(window.grecaptcha?.render){try{captchaWidget.current=window.grecaptcha.render(captchaContainer.current,{sitekey:siteKey,theme:'dark',callback:token=>{setCaptchaToken(token);setMessage('')},'expired-callback':()=>setCaptchaToken(''),'error-callback':()=>{setCaptchaToken('');setMessage('reCAPTCHA could not be loaded. Please try again.')}})}catch(error){console.error('KitSetups reCAPTCHA render failed:',error);setMessage('reCAPTCHA could not be loaded. Please refresh and try again.')}}else if(attempts++<40)setTimeout(renderCaptcha,250)};renderCaptcha();return()=>{cancelled=true;captchaWidget.current=null}},[mode]);
 const submit=async event=>{event.preventDefault();if(!auth||!db)return;setBusy(true);setMessage('');const cleanEmail=email.trim().toLowerCase();try{await setPersistence(auth,browserLocalPersistence);if(mode==='signup'){if(!captchaToken){setMessage('Please complete the reCAPTCHA check.');return}const response=await fetch('/api/register-account',{method:'POST',headers:{'Content-Type':'application/json',...(await getAppCheckHeaders())},body:JSON.stringify({email:cleanEmail,password,recaptchaToken:captchaToken})});let payload={};try{payload=await response.json()}catch{}if(!response.ok)throw Object.assign(new Error(payload.error||'Account creation failed.'),{code:payload.code||'auth/registration-failed'});await signInWithCustomToken(auth,payload.customToken)}else await signInWithEmailAndPassword(auth,cleanEmail,password)}catch(error){const code=error?.code||'';const friendly={'ACCOUNT_ALREADY_EXISTS':'An account already exists for this email identity. Sign in instead.','NETWORK_ACCOUNT_EXISTS':'An account has already been created from this network. Sign in instead.','auth/email-already-in-use':'An account already exists with this email. Sign in instead.','auth/invalid-credential':'Email or password is incorrect.','auth/invalid-email':'Enter a valid email address.','auth/weak-password':'Use a stronger password (at least 6 characters).','auth/network-request-failed':'Network error. Check your connection and try again.','auth/too-many-requests':'Too many attempts. Please wait a moment and try again.','auth/registration-failed':'Account creation could not be completed. Please try again.','auth/app-check-token-is-invalid':'Security verification failed. Please refresh and try again.','auth/app-check-token-is-missing':'Security verification is unavailable. Please refresh and try again.','RECAPTCHA_FAILED':'Please complete the reCAPTCHA check and try again.'};setMessage(friendly[code]||error?.message||'Authentication failed.')}finally{setBusy(false)}};
 if(!firebaseConfigured)return <AuthScreen title="KitSetups setup required" message="Firebase is not configured for this deployment. Add the VITE_FIREBASE_* environment variables in Vercel, then redeploy."/>;if(!ready)return typeof children==='function'?children(null):cloneElement(children,{user:null});if(!user)return <AuthScreen mode={mode} setMode={setMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} busy={busy} message={message} onSubmit={submit} captchaContainer={captchaContainer}/>;return typeof children==='function'?children(user):cloneElement(children,{user})}

function AuthScreen({mode='signin',setMode,email='',setEmail,password='',setPassword,busy=false,message='',onSubmit,title='KitSetups',captchaContainer}){const interactive=Boolean(onSubmit);const [showPassword,setShowPassword]=useState(false);return <div className="auth-screen"><div className="auth-glow"/><div className="auth-card"><div className="auth-brand"><img src="/kitsetups-logo.svg" alt="KitSetups"/><div><b>KitSetups</b><small>The Crypto Command Center</small></div></div><div className="auth-kicker"><ShieldCheck size={14}/> SECURE ACCOUNT ACCESS</div><h1>{title}</h1>{interactive&&<p className="auth-intro">{mode==='signin'?'Sign in to continue to your command center.':'Create your account and KitSetups will generate your username and unique visual avatar automatically.'}</p>}{interactive&&<form onSubmit={onSubmit}><label className="auth-label">EMAIL<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label className="auth-label">PASSWORD<div style={{position:'relative'}}><input required minLength={6} type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters" style={{paddingRight:44}}/><button type="button" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?'Hide password':'Show password'} title={showPassword?'Hide password':'Show password'} style={{position:'absolute',right:10,top:'50%',transform:'translateY(-50%)',display:'grid',placeItems:'center',width:28,height:28,padding:0,border:0,background:'transparent',color:'#7c9299',cursor:'pointer'}}>{showPassword?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{mode==='signup'&&<div ref={captchaContainer} style={{minHeight:78,margin:'4px 0 12px',display:'flex',alignItems:'center',justifyContent:'flex-start',overflow:'hidden',borderRadius:8}}/>}{message&&<div className="auth-error">{message}</div>}<button disabled={busy} className="auth-submit" type="submit">{busy?<LoaderCircle size={16}/>:mode==='signin'?<LogIn size={16}/>:<UserPlus size={16}/>} {busy?'Securing account…':mode==='signin'?'Sign in':'Create account'}</button><button type="button" onClick={()=>{setMode(mode==='signin'?'signup':'signin');setMessage('');setShowPassword(false)}} className="auth-switch">{mode==='signin'?'New to KitSetups? Create an account':'Already have an account? Sign in'}</button></form>}{!interactive&&<div className="auth-error">{message}</div>}<div className="auth-foot">Your account is secured by Firebase Authentication and Firebase App Check. KitSetups never asks for your seed phrase or private key.</div></div></div>}
