(()=>{
const ROOT_IDS=['kit-cex-stable','kit-cex'];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const num=(v,d=8)=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(Number(v))?(Number(v)*100).toFixed(4)+'%':'—';
const state=()=>{try{return JSON.parse(localStorage.getItem('kitagent_cex_v2')||'{}')}catch{return{}}};
const api=async(action,s,extra={})=>{const r=await fetch('/api/cex',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,symbol:s.symbol||'BTCUSDT',key:s.key||'',secret:s.secret||'',...extra})});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||`MEXC request failed (${r.status})`);return j};
let lastMarket=null,lastAccount={};
function root(){return ROOT_IDS.map(id=>document.getElementById(id)).find(Boolean)}
function symbolFromRoot(r){const el=r?.querySelector('[data-pair],#ks');return String(el?.value||'BTCUSDT').toUpperCase().replace(/[-/]/g,'').replace('_USDT','USDT')}
function credentials(){const s=state();return {symbol:symbolFromRoot(root()),key:s.key||'',secret:s.secret||''}}
function addStyle(){if(document.getElementById('kit-mexc-data-css'))return;const st=document.createElement('style');st.id='kit-mexc-data-css';st.textContent=`#kit-mexc-data{border-top:1px solid #171d27;background:#080c12;padding:10px}#kit-mexc-data .mx-top{display:flex;justify-content:space-between;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:8px}#kit-mexc-data .mx-title{font-size:11px;font-weight:800}#kit-mexc-data .mx-actions{display:flex;gap:5px;flex-wrap:wrap}#kit-mexc-data button{background:#111721;color:#d8e1ec;border:1px solid #263141;border-radius:5px;padding:5px 8px;font-size:9px;cursor:pointer}#kit-mexc-data .mx-grid{display:grid;grid-template-columns:repeat(6,minmax(90px,1fr));gap:5px}#kit-mexc-data .mx-card{background:#0b1119;border:1px solid #192331;border-radius:6px;padding:7px;min-width:0}#kit-mexc-data small{display:block;color:#657287;font-size:7px;margin-bottom:3px}#kit-mexc-data b{font-size:10px;font-variant-numeric:tabular-nums}#kit-mexc-data .mx-specs{display:grid;grid-template-columns:repeat(5,minmax(100px,1fr));gap:5px;margin-top:7px}#kit-mexc-data .mx-note{font-size:8px;color:#718097;margin-top:7px}#kit-mexc-data .mx-error{color:#ff6878}#kit-mexc-data input[type=file]{display:none}@media(max-width:900px){#kit-mexc-data .mx-grid{grid-template-columns:repeat(3,minmax(90px,1fr))}#kit-mexc-data .mx-specs{grid-template-columns:repeat(3,minmax(100px,1fr))}}@media(max-width:600px){#kit-mexc-data .mx-grid,#kit-mexc-data .mx-specs{grid-template-columns:repeat(2,minmax(100px,1fr))}}`;document.head.appendChild(st)}
function ensurePanel(){const r=root();if(!r)return null;addStyle();let p=r.querySelector('#kit-mexc-data');if(p)return p;p=document.createElement('section');p.id='kit-mexc-data';p.innerHTML='<div class="mx-top"><span class="mx-title">MEXC market & risk data</span><div class="mx-actions"><button data-mx-refresh>Refresh</button><button data-mx-export>Export snapshot</button><button data-mx-import>Import snapshot</button><input data-mx-file type="file" accept="application/json,.json"></div></div><div data-mx-body class="mx-note">Loading MEXC data…</div>';r.appendChild(p);p.querySelector('[data-mx-refresh]').onclick=()=>load(true);p.querySelector('[data-mx-export]').onclick=exportSnapshot;p.querySelector('[data-mx-import]').onclick=()=>p.querySelector('[data-mx-file]').click();p.querySelector('[data-mx-file]').onchange=importSnapshot;return p}
function render(m,account,err=''){const p=ensurePanel();if(!p)return;const t=m?.ticker||{},c=m?.contract||{},f=m?.funding||{},i=m?.index||{},fp=m?.fairPrice||{};const body=p.querySelector('[data-mx-body]');body.innerHTML=`<div class="mx-grid"><div class="mx-card"><small>LAST</small><b>${num(t.lastPrice)}</b></div><div class="mx-card"><small>24H HIGH</small><b>${num(t.high24Price)}</b></div><div class="mx-card"><small>24H LOW</small><b>${num(t.lower24Price)}</b></div><div class="mx-card"><small>24H VOLUME</small><b>${num(t.volume24,2)}</b></div><div class="mx-card"><small>24H TURNOVER</small><b>${num(t.amount24,2)}</b></div><div class="mx-card"><small>24H CHANGE</small><b>${pct(t.riseFallRate)}</b></div><div class="mx-card"><small>BID / ASK</small><b>${num(t.bid1)} / ${num(t.ask1)}</b></div><div class="mx-card"><small>INDEX</small><b>${num(i.indexPrice||t.indexPrice)}</b></div><div class="mx-card"><small>FAIR / MARK</small><b>${num(fp.fairPrice||t.fairPrice)}</b></div><div class="mx-card"><small>FUNDING</small><b>${pct(f.fundingRate||t.fundingRate)}</b></div><div class="mx-card"><small>NEXT FUNDING</small><b>${f.nextSettleTime?new Date(f.nextSettleTime).toLocaleTimeString():'—'}</b></div><div class="mx-card"><small>OPEN INTEREST</small><b>${num(t.holdVol)}</b></div></div><div class="mx-specs"><div class="mx-card"><small>CONTRACT SIZE</small><b>${num(c.contractSize)}</b></div><div class="mx-card"><small>MIN / MAX LEVERAGE</small><b>${num(c.minLeverage,0)}x / ${num(c.maxLeverage,0)}x</b></div><div class="mx-card"><small>MIN / MAX VOL</small><b>${num(c.minVol)} / ${num(c.maxVol)}</b></div><div class="mx-card"><small>PRICE / VOL SCALE</small><b>${num(c.priceScale,0)} / ${num(c.volScale,0)}</b></div><div class="mx-card"><small>PRICE / VOL UNIT</small><b>${num(c.priceUnit)} / ${num(c.volUnit)}</b></div><div class="mx-card"><small>MAKER / TAKER FEE</small><b>${pct(c.makerFeeRate)} / ${pct(c.takerFeeRate)}</b></div><div class="mx-card"><small>MAINT. / INITIAL MARGIN</small><b>${pct(c.maintenanceMarginRate)} / ${pct(c.initialMarginRate)}</b></div><div class="mx-card"><small>RISK TYPE / LEVELS</small><b>${esc(c.riskLimitType||'—')} / ${num(c.riskLevelLimit,0)}</b></div><div class="mx-card"><small>POSITION OPEN TYPE</small><b>${c.positionOpenType===1?'Isolated':c.positionOpenType===2?'Cross':'Both'}</b></div><div class="mx-card"><small>MARKET ORDER LEVEL</small><b>${num(c.marketOrderMaxLevel,0)}</b></div></div>${account?.assets?`<div class="mx-note">Account data: ${account.assets.length} asset(s) · ${account.positions?.length||0} open position(s) · ${account.orders?.length||0} open order(s)</div>`:''}<div class="mx-note ${err?'mx-error':''}">${esc(err||'Live MEXC data')}</div>`}
async function load(force=false){const r=root();if(!r)return;const s=credentials();try{const m=await api('market',s);lastMarket=m;let account={};if(s.key&&s.secret){const results=await Promise.allSettled([api('assets',s),api('positions',s),api('orders',s)]);account.assets=results[0].status==='fulfilled'?(results[0].value?.data||[]):[];account.positions=results[1].status==='fulfilled'?(results[1].value?.data||[]):[];account.orders=results[2].status==='fulfilled'?(results[2].value?.data||[]):[]}lastAccount=account;render(m,account)}catch(e){render(lastMarket,lastAccount,e.message||'MEXC data unavailable')}}
function exportSnapshot(){const s=credentials();const payload={version:1,exportedAt:new Date().toISOString(),exchange:'mexc',symbol:s.symbol,market:lastMarket,account:lastAccount};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`kitagent-mexc-${s.symbol}-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importSnapshot(e){const file=e.target.files?.[0];if(!file)return;try{const payload=JSON.parse(await file.text());if(payload.exchange&&payload.exchange!=='mexc')throw Error('This is not a MEXC snapshot');lastMarket=payload.market||null;lastAccount=payload.account||{};render(lastMarket,lastAccount,'Imported snapshot — live data resumes on refresh')}catch(err){render(lastMarket,lastAccount,err.message||'Invalid snapshot')}finally{e.target.value=''}}
let timer=0,observer=null;
function boot(){if(!root())return;ensurePanel();load();clearInterval(timer);timer=setInterval(()=>{if(document.visibilityState!=='hidden')load()},10000);if(!observer){observer=new MutationObserver(()=>{if(root()&&!root().querySelector('#kit-mexc-data')){ensurePanel();if(lastMarket)render(lastMarket,lastAccount)}});observer.observe(document.body,{childList:true,subtree:true})}}
boot();setTimeout(boot,500);setTimeout(boot,1500);setTimeout(boot,3000);
})();
