import {useEffect,useMemo,useRef,useState} from 'react';
import {ChevronDown,LogOut,RefreshCw,Share2,X,Wallet,Zap} from 'lucide-react';
import {ExchangeClient,HttpTransport} from '@nktkas/hyperliquid';
import {createWalletClient,custom} from 'viem';
import {arbitrum} from 'viem/chains';

const HL='https://api.hyperliquid.xyz/info';
const intervals=['1m','3m','5m','15m','30m','1h','2h','4h','8h','12h','1d','3d','1w'];
const postInfo=body=>fetch(HL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'}).then(async r=>{if(!r.ok)throw Error(`Hyperliquid request failed (${r.status})`);return r.json()});
const fmt=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const usd=v=>Number.isFinite(Number(v))?`$${fmt(v,2)}`:'—';
const clean=v=>String(v??'').replace(/[^0-9.]/g,'');
const stepDown=(v,d)=>{const n=Number(v),p=10**d;return n>0?Math.floor(n*p+1e-10)/p:0};

export default function HyperliquidPerpetualsPage({wallet,connectWallet}){
 const [meta,setMeta]=useState(null),[coin,setCoin]=useState('BTC'),[query,setQuery]=useState(''),[picker,setPicker]=useState(false),[tf,setTf]=useState('5m');
 const [ctx,setCtx]=useState(null),[book,setBook]=useState({bids:[],asks:[]}),[candles,setCandles]=useState([]),[connected,setConnected]=useState(Boolean(wallet));
 const [state,setState]=useState(null),[orders,setOrders]=useState([]),[fills,setFills]=useState([]),[side,setSide]=useState('Buy'),[type,setType]=useState('Market'),[margin,setMargin]=useState('100'),[leverage,setLeverage]=useState(5),[limit,setLimit]=useState('');
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[walletClient,setWalletClient]=useState(null); const timer=useRef(null);
 const universe=meta?.universe||[]; const asset=universe.find(x=>x.name===coin); const idx=universe.findIndex(x=>x.name===coin); const px=Number(ctx?.midPx||ctx?.markPx||0); const szDecimals=Number(asset?.szDecimals??5); const maxLev=Number(asset?.maxLeverage||50); const qty=stepDown((Number(margin)||0)*(Number(leverage)||1)/(px||1),szDecimals); const filtered=useMemo(()=>universe.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())).slice(0,180),[universe,query]);
 const say=x=>{setNotice(x);clearTimeout(timer.current);timer.current=setTimeout(()=>setNotice(''),6000)};
 const ensureWallet=async()=>{try{if(!window.ethereum)throw Error('Install MetaMask or another injected EVM wallet first.');const accounts=await window.ethereum.request({method:'eth_requestAccounts'});const address=accounts?.[0];if(!address)throw Error('No wallet account selected.');try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:'0xa4b1'}]})}catch(e){if(e?.code===4902)await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:'0xa4b1',chainName:'Arbitrum One',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://arb1.arbitrum.io/rpc'],blockExplorerUrls:['https://arbiscan.io']} ]});else throw e}const wc=createWalletClient({account:address,chain:arbitrum,transport:custom(window.ethereum)});setWalletClient(wc);setConnected(true);say('Wallet connected to Arbitrum for Hyperliquid.');return wc}catch(e){say(e?.message||'Wallet connection failed.');throw e}};
 const refresh=async()=>{try{const m=await postInfo({type:'metaAndAssetCtxs'});setMeta(m[0]);const i=(m[0]?.universe||[]).findIndex(x=>x.name===coin);if(i>=0)setCtx(m[1]?.[i]||null);const [b,c]=await Promise.all([postInfo({type:'l2Book',coin}),postInfo({type:'candleSnapshot',req:{coin,interval:tf,startTime:Date.now()-1000*60*60*24*7,endTime:Date.now()}})]);setBook({bids:(b?.levels?.[0]||[]).map(x=>({price:+x.px,size:+x.sz})),asks:(b?.levels?.[1]||[]).map(x=>({price:+x.px,size:+x.sz}))});setCandles((c||[]).map(x=>({time:+x.t,open:+x.o,high:+x.h,low:+x.l,close:+x.c,volume:+x.v})));if(wallet){const [s,o,f]=await Promise.all([postInfo({type:'clearinghouseState',user:wallet}),postInfo({type:'openOrders',user:wallet}),postInfo({type:'userFills',user:wallet})]);setState(s);setOrders(o||[]);setFills((f||[]).slice(0,50))} }catch(e){say(e.message)}};
 useEffect(()=>{refresh();const id=setInterval(refresh,2500);return()=>clearInterval(id)},[coin,tf,wallet]);
 useEffect(()=>{setConnected(Boolean(wallet))},[wallet]);
 const place=async()=>{if(!wallet){await connectWallet?.();return}if(!(qty>0))return say('Enter a valid margin.');if(type==='Limit'&&!(Number(limit)>0))return say('Enter a valid limit price.');setBusy(true);try{const wc=walletClient||await ensureWallet();const exchange=new ExchangeClient({transport:new HttpTransport(),wallet:wc,signatureChainId:'0xa4b1'});await exchange.updateLeverage({asset:idx,isCross:true,leverage:Number(leverage)});const order={a:idx,b:side==='Buy',p:type==='Limit'?String(limit):String(px),s:String(qty),r:false,t:type==='Limit'?{limit:{tif:'Gtc'}}:{limit:{tif:'Ioc'}}};const result=await exchange.order({orders:[order],grouping:'na'});say(`${side==='Buy'?'Long':'Short'} order submitted on Hyperliquid.`);console.log(result);await refresh()}catch(e){say(e?.message||'Order failed.')}finally{setBusy(false)}};
 const cancel=async(o)=>{setBusy(true);try{const wc=walletClient||await ensureWallet();const exchange=new ExchangeClient({transport:new HttpTransport(),wallet:wc,signatureChainId:'0xa4b1'});await exchange.cancel({cancels:[{a:Number(o.a),o:Number(o.oid)}]});say('Order cancelled.');await refresh()}catch(e){say(e.message)}finally{setBusy(false)}};
 const current=state?.assetPositions?.find(x=>x.position?.coin===coin)?.position; const pnl=Number(current?.unrealizedPnl||0); const chart=candles.slice(-100);const lo=chart.length?Math.min(...chart.map(x=>x.low)):0;const hi=chart.length?Math.max(...chart.map(x=>x.high)):1;const range=hi-lo||1;
 const share=async()=>{if(!current)return say('No open position to share.');const text=`KitSetups Perpetuals · ${coin}-PERP\n${current.szi>0?'Long':'Short'} · PnL ${pnl>=0?'+':''}${usd(pnl)}\nEntry ${usd(current.entryPx)} · Mark ${usd(ctx?.markPx)}`;try{if(navigator.share)await navigator.share({title:'KitSetups PnL',text});else await navigator.clipboard.writeText(text);say('PnL copied.')}catch{}};
 return <div className="page-wrap ka-perps"><style>{CSS}</style>{notice&&<div className="ka-toast">{notice}<button onClick={()=>setNotice('')}><X size={14}/></button></div>}
 <div className="ka-marketbar glass-panel"><div className="pair"><button onClick={()=>setPicker(v=>!v)}><i>{coin[0]}</i><span><b>{coin}-PERP</b><small>Hyperliquid perpetual</small></span><ChevronDown size={14}/></button>{picker&&<div className="pair-menu"><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search markets…"/>{filtered.map(m=><button key={m.name} onClick={()=>{setCoin(m.name);setPicker(false);setQuery('')}}><b>{m.name}-PERP</b><small>{m.maxLeverage||'—'}x</small></button>)}</div>}</div><div className="stats"><span>Mark <b>{usd(ctx?.markPx)}</b></span><span>24h <b className={Number(ctx?.prevDayPx)&&px>=Number(ctx.prevDayPx)?'long':'short'}>{Number(ctx?.prevDayPx)?`${((px/Number(ctx.prevDayPx)-1)*100).toFixed(2)}%`:'—'}</b></span><span>Funding <b>{ctx?.funding?`${(Number(ctx.funding)*100).toFixed(4)}%`:'—'}</b></span><span>OI <b>{fmt(ctx?.openInterest,0)}</b></span><span>Volume <b>{fmt(ctx?.dayNtlVlm,0)}</b></span></div><div className="account">{wallet?<><em className="connected"><i/>Wallet connected</em><b>{usd(state?.marginSummary?.accountValue)}</b><button onClick={()=>setConnected(false)}><LogOut size={13}/>Disconnect</button></>:<button className="connect" onClick={ensureWallet}><Wallet size={13}/>Connect wallet</button>}<button onClick={refresh}><RefreshCw size={14}/></button></div></div>
 <div className="perp-grid"><main><section className="chart-panel glass-panel"><header><b>{coin}-PERP <small>● LIVE</small></b><nav>{intervals.map(x=><button className={tf===x?'sel':''} onClick={()=>setTf(x)} key={x}>{x}</button>)}</nav></header><div className="chart">{chart.length?<svg viewBox="0 0 1000 420" preserveAspectRatio="none">{chart.map((c,i)=>{const x=(i+.5)*(1000/chart.length),w=Math.max(2,720/chart.length),oy=420-(c.open-lo)/range*390,cy=420-(c.close-lo)/range*390,hy=420-(c.high-lo)/range*390,ly=420-(c.low-lo)/range*390;const up=c.close>=c.open;return <g key={c.time}><line x1={x} x2={x} y1={hy} y2={ly} className={up?'long-stroke':'short-stroke'}/><rect x={x-w/2} y={Math.min(oy,cy)} width={w} height={Math.max(1,Math.abs(cy-oy))} className={up?'long-fill':'short-fill'}/></g>})}</svg>:<div className="empty">Loading live market data…</div>}</div></section><section className="subpanel glass-panel"><header><b>Positions</b><button onClick={share}><Share2 size={14}/>Share PnL</button></header>{current?<div className="position-row"><b className={Number(current.szi)>0?'long':'short'}>{Number(current.szi)>0?'Long':'Short'} {Math.abs(Number(current.szi))} {coin}</b><span>Entry {usd(current.entryPx)}</span><span>Mark {usd(ctx?.markPx)}</span><span className={pnl>=0?'long':'short'}>PnL {pnl>=0?'+':''}{usd(pnl)}</span></div>:<div className="empty">No open {coin} position.</div>}</section></main>
 <aside><section className="book glass-panel"><header><b>Order book</b><small>LIVE</small></header><div className="book-head"><span>Price</span><span>Size</span></div><div className="book-side">{book.asks.slice(0,12).reverse().map((x,i)=><div key={i}><b className="short">{fmt(x.price,2)}</b><span>{fmt(x.size,4)}</span></div>)}</div><div className="mid">{usd(px)}</div><div className="book-side">{book.bids.slice(0,12).map((x,i)=><div key={i}><b className="long">{fmt(x.price,2)}</b><span>{fmt(x.size,4)}</span></div>)}</div></section><section className="trade-panel glass-panel"><header><div><button className={side==='Buy'?'activeBuy':''} onClick={()=>setSide('Buy')}>Long</button><button className={side==='Sell'?'activeSell':''} onClick={()=>setSide('Sell')}>Short</button></div></header><div className="tabs"><button className={type==='Market'?'sel':''} onClick={()=>setType('Market')}>Market</button><button className={type==='Limit'?'sel':''} onClick={()=>setType('Limit')}>Limit</button></div><label className="pf"><span>Margin</span><div><input inputMode="decimal" value={margin} onChange={e=>setMargin(clean(e.target.value))}/><small>USD</small></div></label>{type==='Limit'&&<label className="pf"><span>Price</span><div><input inputMode="decimal" value={limit} onChange={e=>setLimit(clean(e.target.value))} placeholder={String(px)}/><small>USD</small></div></label>}<div className="lev"><span>Leverage <b>{leverage}x</b></span><input type="range" min="1" max={maxLev} value={leverage} onChange={e=>setLeverage(+e.target.value)}/><div>{[2,5,10,20].filter(x=>x<=maxLev).map(x=><button key={x} onClick={()=>setLeverage(x)}>{x}x</button>)}</div></div><div className="estimate"><span>Size</span><b>{qty} {coin}</b></div><button className={side==='Buy'?'longBtn':'shortBtn'} disabled={busy} onClick={place}><Zap size={15}/>{busy?'Submitting…':`${side==='Buy'?'Long':'Short'} ${coin}`}</button><p className="risk">Orders are signed by your connected wallet and executed on Hyperliquid. KitSetups never asks for your private key.</p></section></aside></div>
 {wallet&&orders.length>0&&<section className="subpanel glass-panel"><header><b>Open orders</b></header>{orders.slice(0,10).map(o=><div className="position-row" key={o.oid}><b>{o.coin}</b><span>{o.side==='B'?'Buy':'Sell'} {o.sz}</span><span>{o.limitPx}</span><button onClick={()=>cancel(o)} disabled={busy}>Cancel</button></div>)}</section>}
 </div>;
}
const CSS=`.ka-perps{--cyan:#18e0ff;--red:#ff5570;color:#eef7ff}.ka-perps .long,.ka-perps .long-stroke{color:var(--cyan);stroke:var(--cyan)}.ka-perps .short,.ka-perps .short-stroke{color:var(--red);stroke:var(--red)}.ka-perps .long-fill{fill:rgba(24,224,255,.8)}.ka-perps .short-fill{fill:rgba(255,85,112,.8)}.ka-perps .chart svg{width:100%;height:100%;display:block}.ka-perps .book,.ka-perps .trade-panel,.ka-perps .subpanel{padding:14px}.ka-perps .book-side>div,.ka-perps .position-row{display:flex;justify-content:space-between;gap:12px;padding:4px 0;font-size:12px}.ka-perps .book-head,.ka-perps .stats{display:flex;justify-content:space-between;gap:12px}.ka-perps .book-head{font-size:10px;opacity:.55;padding-bottom:5px}.ka-perps .mid{margin:7px 0;padding:7px;border-block:1px solid rgba(255,255,255,.07);font-weight:700}.ka-perps .trade-panel header>div{display:flex;gap:6px}.ka-perps .trade-panel header button,.ka-perps .tabs button{border:0;background:transparent;color:inherit;padding:8px 10px;border-radius:8px}.ka-perps .activeBuy{background:rgba(24,224,255,.13)!important;color:var(--cyan)!important}.ka-perps .activeSell{background:rgba(255,85,112,.13)!important;color:var(--red)!important}.ka-perps .tabs{display:flex;gap:4px;border-bottom:1px solid rgba(255,255,255,.08);margin:8px 0}.ka-perps .tabs .sel{color:var(--cyan);border-bottom:2px solid var(--cyan)}.ka-perps .pf{display:block;margin:10px 0}.ka-perps .pf>span,.ka-perps .lev>span{display:flex;justify-content:space-between;font-size:11px;opacity:.7;margin-bottom:5px}.ka-perps .pf div{display:flex;align-items:center;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:8px}.ka-perps .pf input{width:100%;background:none;border:0;outline:0;color:inherit;padding:10px}.ka-perps .pf small{padding-right:9px;opacity:.55}.ka-perps .lev input{width:100%}.ka-perps .lev>div{display:flex;gap:5px;margin-top:5px}.ka-perps .lev button{flex:1;background:rgba(255,255,255,.04);color:inherit;border:0;border-radius:6px;padding:5px}.ka-perps .estimate{display:flex;justify-content:space-between;font-size:12px;padding:9px 0}.ka-perps .longBtn,.ka-perps .shortBtn{width:100%;border:0;border-radius:9px;padding:12px;font-weight:800;display:flex;justify-content:center;gap:6px}.ka-perps .longBtn{background:var(--cyan);color:#001015}.ka-perps .shortBtn{background:var(--red);color:#180006}.ka-perps .risk{font-size:10px;opacity:.5;line-height:1.4}.ka-perps .empty{padding:28px;text-align:center;opacity:.45;font-size:12px}.ka-perps .ka-toast{position:fixed;right:18px;top:82px;z-index:50;background:#10171e;border:1px solid rgba(255,255,255,.12);padding:10px 12px;border-radius:10px;box-shadow:0 15px 40px #0008;display:flex;gap:10px;align-items:center;font-size:12px}.ka-perps .ka-toast button{border:0;background:none;color:inherit}.ka-perps .connected i{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--red);box-shadow:0 0 9px var(--red);margin-right:5px}`