export const KIT_LESSONS=[
{id:'risk-basics',title:'Risk comes before the trade',category:'Risk management',minutes:2,body:'Before thinking about profit, decide what you are willing to lose if the idea is wrong. Your stop loss defines the invalidation point; position size should be adjusted so that a stopped trade does not damage your account.',tip:'A smaller position with a sensible stop is usually safer than forcing a tight stop just to trade a larger size.'},
{id:'leverage',title:'What leverage actually changes',category:'Risk management',minutes:2,body:'Leverage lets a smaller amount of margin control a larger position. It does not make a setup safer. The same price move against a larger position creates a larger loss relative to your margin, and liquidation can occur when available margin is exhausted.',tip:'Choose position size and stop distance from your risk plan first; treat leverage as a tool, not a target.'},
{id:'stop-loss',title:'Stop loss = invalidation',category:'Risk management',minutes:2,body:'A stop loss should sit where the trade idea is no longer valid, not simply at an arbitrary number of points. For a long idea that can mean below a protected low; for a short idea, above a protected high.',tip:'If the structurally correct stop makes the risk too large, reduce size or skip the trade.'},
{id:'take-profit',title:'What makes a TP meaningful?',category:'Risk management',minutes:2,body:'A take profit is stronger when it is tied to a real market objective: a swing high or low, a liquidity area, or another clearly defined structural target. A target chosen only to manufacture a desired RR can produce misleading setups.',tip:'The market structure chooses the destination; risk/reward helps you decide whether the journey is worth taking.'},
{id:'market-vs-limit',title:'Market order vs limit order',category:'Execution',minutes:2,body:'A market order seeks execution at the best available current price. A limit order waits for price to reach a price you specify. A limit entry can improve location, but there is no guarantee that price will return to it.',tip:'Do not chase a missed limit entry simply because you wanted the trade.'},
{id:'liquidity',title:'Liquidity in simple terms',category:'Market structure',minutes:2,body:'Liquidity describes areas where orders are likely concentrated. Equal highs, equal lows and obvious swing points can become areas where stops and pending orders cluster. Price can interact with these areas before choosing its next direction.',tip:'A liquidity touch or sweep is context, not a trade signal by itself.'},
{id:'protected-low',title:'What is a protected low?',category:'Market structure',minutes:2,body:'A protected low is a meaningful swing low that helps define the current bullish structure. If price breaks and accepts below that level, the bullish idea may no longer be valid. The exact level depends on the structure and timeframe being analyzed.',tip:'Always identify the timeframe before calling a low protected.'},
{id:'protected-high',title:'What is a protected high?',category:'Market structure',minutes:2,body:'A protected high is a meaningful swing high that helps define bearish structure. A decisive break and acceptance above it can invalidate the bearish idea. It is not simply the highest candle you can see.',tip:'Structure is about meaningful swings and their relationships, not isolated candles.'},
{id:'swing-structure',title:'Read swings before indicators',category:'Market structure',minutes:2,body:'Swing highs and swing lows give you the skeleton of price action. Higher highs and higher lows describe an advancing structure; lower highs and lower lows describe a declining structure. Ranges can alternate between both.',tip:'Indicators can add context, but they should not override clear structural invalidation.'},
{id:'candle-body-wick',title:'Body vs wick',category:'Price action',minutes:2,body:'The candle body shows the distance between open and close. The wicks show where price travelled but did not finish. A long wick can show rejection, but one wick alone does not prove a reversal.',tip:'Read the candle in relation to nearby structure and liquidity rather than in isolation.'},
{id:'top-down',title:'Why top-down analysis matters',category:'Market structure',minutes:2,body:'Top-down analysis starts with the higher timeframe and moves toward execution. A higher timeframe can establish context while lower timeframes refine structure, entry and risk. The lower timeframe should not casually override a clear higher-timeframe invalidation.',tip:'Think context first, setup second, execution third.'},
{id:'rr',title:'Risk/reward is not a win-rate guarantee',category:'Risk management',minutes:2,body:'A 1:3 risk/reward means risking one unit to target three units. It does not mean the trade has a 3-to-1 chance of winning. RR describes payoff relative to risk, not probability.',tip:'Never turn an attractive RR number into a claim that a trade is likely to win.'},
{id:'displacement',title:'What is displacement?',category:'Price action',minutes:2,body:'Displacement is a strong directional move that shows urgency in price. Traders often look for a decisive candle or sequence that moves away from a prior area and helps confirm that participation has shifted.',tip:'A large candle is not automatically displacement; location and structure still matter.'}
];