import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {CHAINS,getToken,ZERO_ADDRESS} from './chains/registry.js';
import {ADDRESS_RE,HEX_RE,ERC20,toBase,toHex,fromBase,erc20Transfer,erc20Approve,erc20BalanceOf,erc721Transfer,erc1155Transfer,setApprovalForAll,parseAddress,parseAmount} from './transactions/abi.js';
import {rpc,estimate,preflight,waitForReceipt,decode,risk,networkHealth,erc20Balance} from './transactions/engine.js';
import {connect,ensureChain,accounts,send,watchWallet,providerInfo} from './wallet/connector.js';
import {classify,parseSend,parseBridge} from './agent/intent.js';
import {parseSwapIntent,quoteRoute,routeTx,routeSummary} from './protocols/routing.js';
import {validateBatch,riskBatch} from './transactions/batch.js';
import {explorerAddress,summarizeActivity} from './portfolio/index.js';

const EXAMPLES=['Send 0.01 ETH to 0x…','Swap 25 USDC for ETH','Bridge 100 USDC to Robinhood Chain','Show my portfolio','Estimate gas','Get test ETH','Approve a spender','Transfer my NFT','Supply 100 USDC','Batch two calls'];
const ACTIONS=[['send','Send','ETH / ERC-20','↗'],['swap','Swap','DEX / aggregator','⇄'],['bridge','Bridge','Cross-chain','◈'],['defi','DeFi','Lend / borrow / stake','◌'],['nft','NFT','ERC-721 / 1155','◇'],['contract','Contract','Any EVM call','⌁'],['batch','Batch','Multi-call planner','⊕']];
const TESTNETS=[{name:'Robinhood Chain Testnet',chainId:46630,rpc:CHAINS.robinhoodTestnet.rpc,faucet:CHAINS.robinhoodTestnet.faucet,explorer:CHAINS.robinhoodTestnet.explorer},{name:'Custom EVM Testnet',chainId:'',rpc:'',faucet:'',explorer:''}];
const shorten=(v,l=8,r=6)=>v&&v.length>l+r+1?`${v.slice(0,l)}…${v.slice(-r)}`:v||'';
const fmtFee=v=>fromBase(v||0n,18);
function Icon({name}){const m={bolt:'ϟ',wallet:'▣',activity:'⌁',command:'⌘',faucet:'♢',settings:'⚙',shield:'◇'};return <span className="icon-glyph">{m[name]||'•'}</span>}
function App(){
 const[chainKey,setChainKey]=useState('robinhood');const chain=CHAINS[chainKey];const[account,setAccount]=useState('');const[command,setCommand]=useState('');const[mode,setMode]=useState('command');const[action,setAction]=useState('send');const[status,setStatus]=useState('READY');const[notice,setNotice]=useState('');const[loading,setLoading]=useState(false);const[native,setNative]=useState('—');const[tokens,setTokens]=useState([]);const[activity,setActivity]=useState([]);const[summary,setSummary]=useState(null);const[gas,setGas]=useState(null);const[plan,setPlan]=useState(null);const[route,setRoute]=useState(null);const[routeBusy,setRouteBusy]=useState(false);const[sendTo,setSendTo]=useState('');const[sendAmount,setSendAmount]=useState('');const[tokenAddress,setTokenAddress]=useState('');const[tokenRecipient,setTokenRecipient]=useState('');const[tokenAmount,setTokenAmount]=useState('');const[tokenDecimals,setTokenDecimals]=useState('18');const[spender,setSpender]=useState('');const[allowance,setAllowance]=useState('');const[contractTo,setContractTo]=useState('');const[contractData,setContractData]=useState('0x');const[contractValue,setContractValue]=useState('');const[nftStandard,setNftStandard]=useState('721');const[nftContract,setNftContract]=useState('');const[nftRecipient,setNftRecipient]=useState('');const[nftTokenId,setNftTokenId]=useState('');const[nftOperator,setNftOperator]=useState('');const[batchText,setBatchText]=useState('');const[customRpc,setCustomRpc]=useState('');const[customChainId,setCustomChainId]=useState('');const[customFaucet,setCustomFaucet]=useState('');const[health,setHealth]=useState(null);const[intent]=useState(()=>classify(command));
 const currentIntent=useMemo(()=>classify(command),[command]);
 useEffect(()=>{accounts().then(a=>a?.[0]&&setAccount(a[0])).catch(()=>{});return watchWallet(a=>{setAccount(a);if(a)refresh(a)},()=>{})},[]);
 useEffect(()=>{if(account)refresh(account)},[account,chainKey]);
 async function refresh(a=account){if(!a)return;try{const b=await rpc(chain,'eth_getBalance',[a,'latest']);setNative(fromBase(BigInt(b),18));const d=await explorerAddress(chain,a);setActivity(d.transactions);setTokens(d.tokens);setSummary(summarizeActivity(d.transactions));}catch(e){setNotice(`Indexer unavailable: ${e.message}`)}}
 async function connectWallet(){try{const a=await connect();if(a?.[0]){setAccount(a[0]);await ensureChain(chain);setNotice('Wallet connected and network checked.')}}catch(e){setNotice(e.message||'Wallet connection failed')}}
 async function switchChain(){try{await ensureChain(chain);setNotice(`${chain.name} selected.`);if(account)refresh()}catch(e){setNotice(e.message||'Network switch failed')}}
 async function preflightTx(tx,label='Transaction',opts={}){if(!account)throw new Error('Connect a wallet first');setStatus('UNDERSTAND');setLoading(true);await new Promise(r=>setTimeout(r,100));setStatus('VERIFY');const r=await preflight(chain,tx,{account,...opts});setStatus('SIMULATE');setGas({units:r.gas.toString(),price:fmtFee(r.gasPrice),fee:fmtFee(r.fee)});setPlan({label,tx,decoded:decode(tx,label),risks:risk(tx,label),gas:r});setStatus('SIMULATION PASSED');return r}
 async function executeTx(tx,label='Transaction',opts={}){try{const r=await preflightTx(tx,label,opts);setStatus('APPROVE');setNotice(`${label} is ready. Review the wallet prompt.`);const hash=await send({...tx,gas:`0x${r.gas.toString(16)}`});setStatus('BROADCAST');setNotice(`${label} broadcast · ${shorten(hash,12,8)}`);setActivity(p=>[{hash,to:tx.to,status:'pending',method:label},...p].slice(0,20));setStatus('CONFIRMING');const receipt=await waitForReceipt(chain,hash);if(receipt.status==='0x0')throw new Error('Transaction reverted on-chain');setStatus('CONFIRMED');setNotice(`${label} confirmed in block ${Number(BigInt(receipt.blockNumber))}`);refresh();return receipt}catch(e){setStatus('READY');setNotice(e.message||'Transaction failed')}}
 function buildPlan(){try{if(currentIntent==='portfolio'){setMode('portfolio');return}if(currentIntent==='faucet'){setMode('faucet');return}if(currentIntent==='gas'){setAction('contract');setNotice('Gas mode: enter the transaction target for an exact estimate.');return}if(currentIntent==='send'){const p=parseSend(command);if(!p.address)throw new Error('I need a valid 0x recipient address');setSendTo(p.address);setSendAmount(p.amount||'0.01');setAction('send');return}if(['swap','bridge','defi','nft','contract','batch'].includes(currentIntent)){setAction(currentIntent);return}setAction('contract');setContractData('0x');setNotice('Choose an action or describe the exact EVM call.')}catch(e){setNotice(e.message)}}
 async function sendNative(){if(!ADDRESS_RE.test(sendTo)||!sendAmount)return setNotice('Enter a valid recipient and ETH amount');try{await executeTx({from:account,to:sendTo,value:toHex(sendAmount)},'ETH transfer')}catch(e){setNotice(e.message)}}
 async function sendToken(){try{if(!ADDRESS_RE.test(tokenAddress)||!ADDRESS_RE.test(tokenRecipient)||!tokenAmount)throw new Error('Enter token, recipient and amount');const d=Number(tokenDecimals);const amount=toBase(tokenAmount,d);await executeTx({from:account,to:tokenAddress,data:erc20Transfer(tokenRecipient,tokenAmount,d),value:'0x0'},'ERC-20 transfer',{requiredToken:tokenAddress,requiredAmount:amount,requiredDecimals:d,spender:tokenAddress})}catch(e){setNotice(e.message)}}
 async function approve(){try{if(!ADDRESS_RE.test(tokenAddress)||!ADDRESS_RE.test(spender)||!tokenAmount)throw new Error('Enter token, spender and amount');await executeTx({from:account,to:tokenAddress,data:erc20Approve(spender,tokenAmount,Number(tokenDecimals)),value:'0x0'},'ERC-20 approval')}catch(e){setNotice(e.message)}}
 async function readToken(){try{if(!ADDRESS_RE.test(tokenAddress))throw new Error('Invalid token address');const d=await rpc(chain,'eth_call',[{to:tokenAddress,data:'0x313ce567'},'latest']);const dec=Number(BigInt(d));setTokenDecimals(String(dec));const bal=await erc20Balance(chain,tokenAddress,account,dec);setNotice(`Token balance: ${bal}`)}catch(e){setNotice(e.message)}}
 async function readAllowance(){try{if(!ADDRESS_RE.test(tokenAddress)||!ADDRESS_RE.test(spender))throw new Error('Enter token and spender');const raw=await rpc(chain,'eth_call',[{to:tokenAddress,data:`0xdd62ed3e${account.slice(2).padStart(64,'0')}${spender.slice(2).padStart(64,'0')}`},'latest']);setAllowance(fromBase(BigInt(raw),Number(tokenDecimals)))}catch(e){setNotice(e.message)}}
 async function contractSim(){try{if(!ADDRESS_RE.test(contractTo)||!HEX_RE.test(contractData))throw new Error('Enter valid target and calldata');await preflightTx({from:account,to:contractTo,data:contractData,value:contractValue?toHex(contractValue):'0x0'},'Contract call')}catch(e){setNotice(e.message)}}
 async function contractExec(){try{if(!ADDRESS_RE.test(contractTo)||!HEX_RE.test(contractData))throw new Error('Enter valid target and calldata');await executeTx({from:account,to:contractTo,data:contractData,value:contractValue?toHex(contractValue):'0x0'},'Contract call')}catch(e){setNotice(e.message)}}
 async function findSwap(){try{if(!account)throw new Error('Connect wallet first');setRouteBusy(true);const p=parseSwapIntent(command||'Swap 1 ETH for WETH',chain.id,account);const input={fromChain:p.fromChain,toChain:p.toChain,fromToken:p.fromToken,toToken:p.toToken,fromAmount:toBase(p.fromAmount,p.fromDecimals).toString(),fromAddress:account,toAddress:account};const q=await quoteRoute(input);setRoute(q);setPlan({label:'Swap route',tx:routeTx(q,account),decoded:decode(routeTx(q,account),'Swap route'),risks:risk(routeTx(q,account),'Swap route')});setNotice(`Route found via ${routeSummary(q).tool}`)}catch(e){setNotice(e.message)}finally{setRouteBusy(false)}}
 async function executeRoute(){if(!route)return;const tx=routeTx(route,account);await executeTx(tx,`Route · ${route.toolDetails?.name||route.tool||'aggregator'}`)}
 async function bridgeRoute(){try{const p=parseBridge(command);if(p.destination.toLowerCase().includes('robinhood')&&chain.id!==4663)throw new Error('Select Robinhood Chain as the destination network');throw new Error('Bridge planning requires a destination chain ID. KitAgent will not guess it. Use Contract mode or a fully specified route.')}catch(e){setNotice(e.message)}}
 async function nft(kind){try{if(!ADDRESS_RE.test(nftContract))throw new Error('Invalid NFT contract');if(kind==='operator'){if(!ADDRESS_RE.test(nftOperator))throw new Error('Invalid operator');return executeTx({from:account,to:nftContract,data:setApprovalForAll(nftOperator,true),value:'0x0'},'NFT operator approval')}if(!ADDRESS_RE.test(nftRecipient)||!nftTokenId)throw new Error('Enter recipient and token ID');const data=nftStandard==='721'?erc721Transfer(account,nftRecipient,nftTokenId):erc1155Transfer(account,nftRecipient,nftTokenId,1);return executeTx({from:account,to:nftContract,data,value:'0x0'},`ERC-${nftStandard} transfer`)}catch(e){setNotice(e.message)}}
 async function runBatch(){try{const calls=JSON.parse(batchText||'[]');const normalized=validateBatch(calls,account);const details=riskBatch(normalized);setPlan({label:`Batch · ${normalized.length} calls`,batch:normalized,details,risks:details.map(x=>`Call ${x.index+1} → ${shorten(x.target)}`)});setNotice('Batch planned. A true atomic multicall is only used when a verified Multicall3 address is configured; otherwise calls remain individually reviewable.')}catch(e){setNotice(e.message)}}
 async function checkHealth(){try{setHealth(await networkHealth(chain));setNotice('RPC health check passed.')}catch(e){setHealth(null);setNotice(`RPC health failed: ${e.message}`)}}
 const sponsorship=Boolean(import.meta.env.VITE_BUNDLER_URL&&import.meta.env.VITE_PAYMASTER_URL);const provider=providerInfo();
 return <div className="app-shell"><aside className="rail"><div className="brand-mini"><div className="brand-mark"><i/><i/><i/></div><span>KIT<span>AGENT</span></span></div><nav>{[['command','command','Command'],['portfolio','wallet','Portfolio'],['activity','activity','Activity'],['faucet','faucet','Gas Station']].map(([m,i,l])=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}><Icon name={i}/><span>{l}</span></button>)}</nav><div className="rail-bottom"><button onClick={connectWallet}><Icon name="wallet"/></button><button onClick={checkHealth}><Icon name="settings"/></button></div></aside><main className="main-shell"><header className="topbar"><div className="top-status"><span className="pulse-dot"/> KITAGENT <b>•</b> ONCHAIN COMMAND CENTER</div><div className="top-controls"><select className="chain-picker" value={chainKey} onChange={e=>{setChainKey(e.target.value);setTimeout(switchChain,0)}}><option value="robinhood">Robinhood Chain</option><option value="robinhoodTestnet">Robinhood Testnet</option></select><button className="wallet-button" onClick={connectWallet}><span className="wallet-dot"/>{account?shorten(account):'Connect wallet'}</button></div></header>
 {mode==='command'&&<><section className="hero-row"><div><div className="eyebrow">ONCHAIN INTENT ENGINE · {chain.name}</div><h1>Command the<br/><em>chain.</em></h1><p>Intent → verified route → preflight → simulation → wallet approval → confirmation. KitAgent stays non-custodial while handling native transfers, ERC-20, NFTs, routes, bridges, DeFi calls and arbitrary EVM transactions.</p></div><div className="agent-core"><div className="core-orbit one"/><div className="core-orbit two"/><div className="core-dot"/><span>AGENT ONLINE</span></div></section>
 <section className="command-grid"><div className="glow-card command-panel"><div className="panel-top"><div><div className="eyebrow">COMMAND</div><small>Describe the outcome. KitAgent builds the transaction plan.</small></div><span className="guard"><Icon name="shield"/> NO KEYS STORED</span></div><textarea value={command} onChange={e=>setCommand(e.target.value)} placeholder="e.g. Swap 25 USDC for ETH and keep enough ETH for gas…"/><div className="command-footer"><div className="quick-row">{EXAMPLES.map(x=><button key={x} onClick={()=>setCommand(x)}>{x}</button>)}</div><button className="execute-intent" disabled={!command.trim()||loading} onClick={buildPlan}>BUILD PLAN ↗</button></div><div className="intent-reading"><b>{currentIntent.toUpperCase()}</b><i/>UNDERSTAND <i/>VERIFY <i/>SIMULATE <i/>APPROVE</div></div><div className="glow-card agent-panel"><div className="workbench-head"><div><div className="eyebrow">EXECUTION GUARD</div><small>One gate for every transaction path.</small></div><span className="status-chip">{status}</span></div><div className="pipeline">{[['01','UNDERSTAND','Intent + assets'],['02','VERIFY','Chain + targets'],['03','SIMULATE','Gas + revert'],['04','APPROVE','Wallet signature'],['05','CONFIRM','Receipt + block']].map(([n,a,d],i)=><div key={n} className={status!=='READY'&&i<4?'stage-live':''}><span>{n}</span><section><b>{a}</b><small>{d}</small></section><i>{status!=='READY'&&i<4?'✓':'·'}</i></div>)}</div><div className="safety"><Icon name="shield"/><div><b>{sponsorship?'ERC-4337 sponsorship configured':'Non-custodial execution'}</b><small>{sponsorship?'Bundler + paymaster endpoints detected.':'No private keys or seed phrases ever enter KitAgent.'}</small></div></div></div></section>
 <div className="action-strip">{ACTIONS.map(([id,title,sub,g])=><button key={id} className={action===id?'selected':''} onClick={()=>setAction(id)}><span className="action-glyph">{g}</span><span><b>{title}</b><small>{sub}</small></span><span>›</span></button>)}</div>
 <section className="glow-card workbench">{action==='send'&&<><div className="workbench-head"><div><div className="eyebrow">TRANSFER ENGINE</div><small>ETH and ERC-20 transfers with balance + gas preflight.</small></div><span className="chain-pill">{chain.name}</span></div><div className="form-grid"><label>ETH RECIPIENT<input value={sendTo} onChange={e=>setSendTo(e.target.value)} placeholder="0x…"/></label><label>ETH AMOUNT<input value={sendAmount} onChange={e=>setSendAmount(e.target.value)} placeholder="0.01"/></label><label>TOKEN CONTRACT<input value={tokenAddress} onChange={e=>setTokenAddress(e.target.value)} placeholder="0x…"/></label><label>TOKEN DECIMALS<input value={tokenDecimals} onChange={e=>setTokenDecimals(e.target.value)} placeholder="18"/></label><label>TOKEN RECIPIENT<input value={tokenRecipient} onChange={e=>setTokenRecipient(e.target.value)} placeholder="0x…"/></label><label>TOKEN AMOUNT<input value={tokenAmount} onChange={e=>setTokenAmount(e.target.value)} placeholder="25"/></label></div><div className="button-row"><button onClick={readToken}>READ TOKEN</button><button onClick={()=>preflightTx({from:account,to:sendTo,value:toHex(sendAmount||'0')},'ETH transfer').catch(e=>setNotice(e.message))}>SIMULATE ETH</button><button className="primary" onClick={sendNative}>SEND ETH</button><button className="primary" onClick={sendToken}>SEND TOKEN</button></div></>}
 {action==='swap'&&<><div className="workbench-head"><div><div className="eyebrow">REAL ROUTE ENGINE</div><small>LI.FI route discovery returns the exact transaction to simulate and sign. No placeholder pair.</small></div><span className="chain-pill">QUOTE → SIMULATE → SIGN</span></div><label className="form-span">SWAP INTENT<input value={command} onChange={e=>setCommand(e.target.value)} placeholder="Swap 25 USDC for ETH"/></label>{route&&<div className="feature-card"><div className="feature-icon">⇄</div><div><h3>{route.toolDetails?.name||route.tool||'Verified route'}</h3><p>{route.action?.fromAmount||'?'} → {route.action?.toAmount||'?'} · slippage {route.action?.slippage??'provider'} · {route.includedSteps?.length||0} step(s)</p></div></div>}<div className="button-row"><button onClick={findSwap}>{routeBusy?'ROUTING…':'FIND ROUTE'}</button><button className="primary" disabled={!route} onClick={executeRoute}>SIMULATE + EXECUTE ROUTE</button></div></>}
 {action==='bridge'&&<><div className="workbench-head"><div><div className="eyebrow">BRIDGE ENGINE</div><small>Cross-chain execution is route-driven; destination IDs are never guessed.</small></div><span className="chain-pill">NO BLIND SIGNING</span></div><label className="form-span">BRIDGE INTENT<input value={command} onChange={e=>setCommand(e.target.value)} placeholder="Bridge 100 USDC to Robinhood Chain"/></label><div className="feature-card"><div className="feature-icon">◈</div><div><h3>Destination-aware routing</h3><p>For a live bridge, KitAgent requires a supported destination chain ID and verified asset. Once supplied by the route provider, the returned transaction goes through the same preflight, simulation, risk and receipt tracker.</p></div></div><div className="button-row"><button onClick={bridgeRoute}>VALIDATE BRIDGE INTENT</button></div></>}
 {action==='defi'&&<><div className="workbench-head"><div><div className="eyebrow">DEFI ADAPTER LAYER</div><small>Protocol calls are executed only from explicit verified calldata.</small></div><span className="chain-pill">NO GUESSED ADDRESSES</span></div><label className="form-span">PROTOCOL INTENT<input value={command} onChange={e=>setCommand(e.target.value)} placeholder="Supply 100 USDC to Morpho"/></label><div className="feature-card"><div className="feature-icon">◌</div><div><h3>Adapter-ready execution</h3><p>Supply, withdraw, borrow, repay, stake, claim, deposit and vault actions are supported through the Universal EVM Executor. Protocol-specific adapters can be enabled by supplying verified contract addresses and ABI calldata; KitAgent refuses to invent a protocol target.</p><div className="route-tags"><span>SUPPLY</span><span>WITHDRAW</span><span>BORROW</span><span>REPAY</span><span>STAKE</span><span>CLAIM</span></div></div></div></>}
 {action==='nft'&&<><div className="workbench-head"><div><div className="eyebrow">NFT ENGINE</div><small>ERC-721 / ERC-1155 safe transfers and operator approvals.</small></div><span className="chain-pill">SAFE TRANSFER</span></div><div className="form-grid"><label>STANDARD<select value={nftStandard} onChange={e=>setNftStandard(e.target.value)}><option value="721">ERC-721</option><option value="1155">ERC-1155</option></select></label><label>CONTRACT<input value={nftContract} onChange={e=>setNftContract(e.target.value)}/></label><label>RECIPIENT<input value={nftRecipient} onChange={e=>setNftRecipient(e.target.value)}/></label><label>TOKEN ID<input value={nftTokenId} onChange={e=>setNftTokenId(e.target.value)}/></label><label>OPERATOR<input value={nftOperator} onChange={e=>setNftOperator(e.target.value)}/></label></div><div className="button-row"><button onClick={()=>nft('operator')}>APPROVE OPERATOR</button><button className="primary" onClick={()=>nft('transfer')}>TRANSFER NFT</button></div></>}
 {action==='contract'&&<><div className="workbench-head"><div><div className="eyebrow">UNIVERSAL EVM EXECUTOR</div><small>Any target, calldata and native value — decoded, simulated and wallet-gated.</small></div><span className="chain-pill">RISK DECODER</span></div><div className="form-grid"><label>TARGET<input value={contractTo} onChange={e=>setContractTo(e.target.value)} placeholder="0x…"/></label><label>VALUE · ETH<input value={contractValue} onChange={e=>setContractValue(e.target.value)} placeholder="0"/></label><label className="form-span">CALLDATA<textarea value={contractData} onChange={e=>setContractData(e.target.value)} placeholder="0x…"/></label></div><div className="route-tags">{(plan?.risks||risk({to:contractTo,data:contractData,value:contractValue?toHex(contractValue):'0x0'},'Contract call')).map(x=><span key={x}>⚠ {x}</span>)}</div><div className="button-row"><button onClick={contractSim}>SIMULATE</button><button className="primary" onClick={contractExec}>EXECUTE</button></div></>}
 {action==='batch'&&<><div className="workbench-head"><div><div className="eyebrow">BATCH PLANNER</div><small>Plan up to 20 explicit calls. Atomic multicall is never fabricated.</small></div><span className="chain-pill">REVIEW EACH TARGET</span></div><label className="form-span">CALLS · JSON<textarea value={batchText} onChange={e=>setBatchText(e.target.value)} placeholder={'[{"to":"0x…","data":"0x","value":"0x0"},{"to":"0x…","data":"0x","value":"0x0"}]'}/></label><div className="button-row"><button onClick={runBatch}>BUILD BATCH PLAN</button></div></>}
 </section>{plan&&<section className="glow-card plan-card"><div className="workbench-head"><div><div className="eyebrow">TRANSACTION PLAN</div><small>{plan.label}</small></div><span className="chain-pill">{plan.tx?.to?shorten(plan.tx.to):`${plan.batch?.length||0} CALLS`}</span></div>{plan.decoded&&<div className="plan-grid"><span>TARGET<b>{shorten(plan.decoded.target,12,8)}</b></span><span>METHOD<b>{plan.decoded.method}</b></span><span>VALUE<b>{fmtFee(BigInt(plan.tx.value||'0x0'))} ETH</b></span><span>CALLDATA<b>{plan.decoded.calldataBytes} bytes</b></span></div>}{gas&&<div className="plan-grid"><span>GAS<b>{gas.units}</b></span><span>GAS PRICE<b>{gas.price} ETH/gas</b></span><span>EST. FEE<b>{gas.fee} ETH</b></span><span>STATUS<b>{status}</b></span></div>}<div className="route-tags">{(plan.risks||[]).map(x=><span key={x}>⚠ {x}</span>)}</div></section>}{gas&&<div className="fee-box"><span>ESTIMATED GAS</span><b>{gas.fee} ETH</b><small>{gas.units} units · {gas.price} ETH/gas</small></div>}{notice&&<div className="bottom-console"><span>{notice}</span><b>{status}</b></div>}</>}
 {mode==='portfolio'&&<section className="glow-card data-page"><div className="page-head"><div><div className="eyebrow">PORTFOLIO INTELLIGENCE</div><h2>Wallet overview</h2><p>{account?shorten(account,10,8):'Connect a wallet'}</p></div><button onClick={()=>refresh()}>REFRESH</button></div><div className="portfolio-total"><span>NATIVE BALANCE</span><strong>{native} <small>ETH</small></strong><i>{chain.name}</i></div>{summary&&<div className="plan-grid"><span>TRANSACTIONS<b>{summary.count}</b></span><span>SUCCESSFUL<b>{summary.successful}</b></span><span>FAILED<b>{summary.failed}</b></span><span>METHODS<b>{Object.keys(summary.methods).length}</b></span></div>}<div className="table-head"><span>ASSET</span><span>BALANCE</span><span>CONTRACT</span></div>{tokens.length?tokens.map((t,i)=><div className="token-row" key={i}><b>{t.token?.symbol||'TOKEN'}</b><span>{t.value||'0'}</span><small>{shorten(t.token?.address||t.token?.contract_address||'')}</small></div>):<div className="empty">No indexed token balances.</div>}</section>}
 {mode==='activity'&&<section className="glow-card data-page"><div className="page-head"><div><div className="eyebrow">ACTIVITY</div><h2>Transaction stream</h2><p>Receipts and explorer indexing are separated from signing.</p></div><button onClick={()=>refresh()}>SYNC</button></div><div className="activity-list">{activity.length?activity.map((x,i)=><a key={i} href={`${chain.explorer}/tx/${x.hash}`} target="_blank" rel="noreferrer"><span className="tx-index">{String(i+1).padStart(2,'0')}</span><div><b>{x.method||x.decoded_input?.method_call||'Transaction'}</b><small>{shorten(x.from?.hash||x.from||'')} → {shorten(x.to?.hash||x.to||'')}</small></div><strong>{x.status||'validated'}</strong></a>):<div className="empty">Connect and sync the wallet.</div>}</div></section>}
 {mode==='faucet'&&<section className="glow-card data-page faucet-page"><div className="page-head"><div><div className="eyebrow">GAS STATION</div><h2>Testnet gas, without guessing.</h2><p>RPC health, native balance and gas estimation work for any EVM testnet you configure. Faucet links are only shown when explicitly configured.</p></div><span className="big-orb">ϟ</span></div><div className="faucet-grid">{TESTNETS.map((n,i)=><div key={n.name}><span>NETWORK {i+1}</span><b>{n.name}</b><small>{n.chainId?`Chain ID ${n.chainId}`:'Bring any EVM testnet RPC'}</small>{n.faucet?<a className="button-link" href={n.faucet} target="_blank" rel="noreferrer">OPEN FAUCET ↗</a>:<button className="button-link" onClick={()=>{setCustomRpc('');setCustomChainId('');setCustomFaucet('')}}>CONFIGURE</button>}</div>)}</div><div className="feature-card"><div className="feature-icon">ϟ</div><div><h3>Universal testnet layer</h3><p>Configure RPC + chain ID below, then KitAgent can verify the network, read native balance and estimate gas. It cannot magically fund arbitrary networks.</p><div className="form-grid"><label>RPC<input value={customRpc} onChange={e=>setCustomRpc(e.target.value)} placeholder="https://…"/></label><label>CHAIN ID<input value={customChainId} onChange={e=>setCustomChainId(e.target.value)} placeholder="12345"/></label><label>FAUCET URL<input value={customFaucet} onChange={e=>setCustomFaucet(e.target.value)} placeholder="https://…"/></label></div></div></div><div className="faucet-note"><Icon name="shield"/><span><b>{sponsorship?'ERC-4337 sponsorship is configured.':'ERC-4337 sponsorship is capability-aware.'}</b> {sponsorship?'Bundler/paymaster environment endpoints were detected.':'The UI will never claim gas sponsorship until VITE_BUNDLER_URL and VITE_PAYMASTER_URL are actually configured.'}</span></div></section>}
 </main></div>}
createRoot(document.getElementById('root')).render(<App/>);
