import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const nav=[['terminal','Terminal','⌘'],['trading','Trading','◈'],['history','History','↗'],['signals','Signals','◆'],['track','Track record','✓'],['profile','Profile','●']];
const pairs=['BTC/USDT','ETH/USDT','SOL/USDT','BNB/USDT','XRP/USDT','EUR/USD','GBP/USD','USD/JPY','USD/CAD','AUD/USD','USD/CHF','NZD/USD'];
const sample=[{pair:'BTC/USDT',bias:'LONG',entry:109420,sl:108650,tp:111180,score:88,reason:'External sell-side sweep + bullish CHOCH + displacement'},{pair:'EUR/USD',bias:'SHORT',entry:1.1712,sl:1.1731,tp:1.1674,score:84,reason:'Buy-side liquidity raid + bearish BOS + delivery shift'},{pair:'ETH/USDT',bias:'LONG',entry:4358,sl:4318,tp:4448,score:82,reason:'Internal liquidity reclaim + structure confirmation'}];
function money(n){return typeof n==='number'?(n>10?n.toLocaleString():n.toFixed(4)):n}
function Icon({children}){return <span className="ico">{children}</span>}
function Layout({page,setPage,children}){return <div className="app"><aside className="rail"><div className="brand">K<span>+</span></div>{nav.map(([id,label,icon])=><button key={id} className={page===id?'nav active':'nav'} onClick={()=>setPage(id)} title={label}><Icon>{icon}</Icon><small>{label}</small></button>)}</aside><main className="main"><header><div><div className="eyebrow">KITAGENT / {page.toUpperCase()}</div><h1>{page==='terminal'?'Web3, in plain English.':page==='trading'?'Market intelligence.':page==='history'?'Transaction history.':page==='signals'?'Live signal desk.':page==='track'?'Performance ledger.':'Your KitAgent.'}</h1></div><div className="status"><i/>SYSTEM ONLINE</div></header>{children}</main></div>}
function Terminal(){const [messages,setMessages]=useState([{role:'agent',text:'Welcome. Tell me what you want to do. I will explain each step before anything touches your wallet.'}]);const [input,setInput]=useState('');const suggestions=['Swap ETH to USDC','Send 0.1 ETH','Bridge to Base','Get testnet faucet','Send my NFT'];const run=()=>{if(!input.trim())return;const q=input.trim();let text='I can prepare that action. I’ll identify the network, asset and recipient, show the estimated gas and risk, then wait for your confirmation and wallet approval before execution.';if(/faucet/i.test(q))text='I’ll identify the requested testnet and route you to its verified faucet. No invented faucet links or contracts.';if(/nft/i.test(q))text='NFT transfer flow ready: recipient → collection/token → network → fee preview → terminal confirmation → wallet approval.';if(/swap|buy|sell/i.test(q))text='Trade flow ready: asset pair → route/quote → price impact → gas → minimum received → confirmation → wallet approval.';if(/bridge/i.test(q))text='Bridge flow ready: source chain → destination chain → asset → route → fees → expected time → confirmation → wallet approval.';setMessages(m=>[...m,{role:'user',text:q},{role:'agent',text}]);setInput('')};return <section className="terminal-page"><div className="terminal-shell"><div className="terminal-top"><span>AGENT CONSOLE</span><span>SAFE MODE · WALLET ACTIONS REQUIRE APPROVAL</span></div><div className="messages">{messages.map((m,i)=><div className={'msg '+m.role} key={i}><b>{m.role==='agent'?'KITAGENT':'YOU'}</b><p>{m.text}</p></div>)}</div><div className="suggestions">{suggestions.map(x=><button onClick={()=>setInput(x)} key={x}>{x}</button>)}</div><div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();run()}}} placeholder="Ask KitAgent to do something…"/><button onClick={run}>EXECUTE <span>↵</span></button></div></div><div className="terminal-grid">{[['Swap','Exchange one asset for another with route + slippage controls.'],['Bridge','Move supported assets across networks with fee visibility.'],['Transfer','Send tokens or NFTs with address validation.'],['Faucet','Find verified testnet faucets for supported networks.']].map(([a,b])=><div className="mini" key={a}><span>{a}</span><p>{b}</p></div>)}</div></section>}
function Trading(){const [pair,setPair]=useState('BTC/USDT');const signal=useMemo(()=>sample.find(x=>x.pair===pair)||sample[0],[pair]);return <section className="page"><div className="toolbar"><select value={pair} onChange={e=>setPair(e.target.value)}>{pairs.map(p=><option key={p}>{p}</option>)}</select><select><option>1H structure</option><option>15m execution</option><option>4H bias</option></select><button className="ghost">REFRESH ANALYSIS</button></div><div className="market-head"><div><span className="muted">STRUCTURE SCORE</span><strong>{signal.score}/100</strong></div><div><span className="muted">BIAS</span><strong className={signal.bias==='LONG'?'up':'down'}>{signal.bias}</strong></div><div><span className="muted">RISK MODEL</span><strong>CONTROLLED</strong></div></div><div className="trade-card"><div className="card-title"><div><span className="pill">HIGH-CONFLUENCE SETUP</span><h2>{signal.pair} <em>{signal.bias}</em></h2></div><span className="score">{signal.score}</span></div><div className="levels"><div><span>ENTRY</span><b>{money(signal.entry)}</b></div><div><span>STOP</span><b>{money(signal.sl)}</b></div><div><span>TARGET</span><b>{money(signal.tp)}</b></div><div><span>R:R</span><b>1 : 2.3</b></div></div><div className="logic"><b>WHY THIS SETUP</b><p>{signal.reason}. No signal is issued when structure, liquidity and delivery do not align.</p></div><div className="structure"><span>EXTERNAL LIQUIDITY</span><i/><span>SWEEP</span><i/><span>CHOCH / BOS</span><i/><span>DISPLACEMENT</span><i/><span>ENTRY</span></div></div><div className="rules"><h3>Decision engine</h3><div>{['External + internal liquidity mapping','Market structure: BOS / CHOCH','Change in state of delivery','Displacement and reclaim confirmation','Volatility-aware stop placement','Minimum 1:2 risk/reward gate','No-trade state when confluence is weak'].map((x,i)=><span key={i}>✓ {x}</span>)}</div></div></section>}
function History(){const rows=[['Swap','ETH → USDC','0x8f…21a','Completed'],['Bridge','USDC · Base → Arbitrum','0x2c…9aa','Completed'],['Transfer','NFT #1842','0x71…4bd','Pending']];return <section className="page"><div className="stats"><div><span>TRANSACTIONS</span><b>24</b></div><div><span>SUCCESS RATE</span><b>100%</b></div><div><span>NETWORKS</span><b>8</b></div></div><div className="table"><div className="tr th"><span>TYPE</span><span>DETAIL</span><span>HASH</span><span>STATUS</span></div>{rows.map((r,i)=><div className="tr" key={i}><span>{r[0]}</span><span>{r[1]}</span><span className="mono">{r[2]}</span><span className="ok">{r[3]}</span></div>)}</div></section>}
function Signals(){return <section className="page"><div className="signal-lock"><span className="lock">◆</span><h2>Premium signal desk</h2><p>Your free trial includes the introductory signal. Premium unlocks the full signal feed, deeper analysis and alerts.</p><div className="blurred">BTC/USDT · LONG · 109,420 → 111,180<br/>ETH/USDT · LONG · 4,358 → 4,448<br/>EUR/USD · SHORT · 1.1712 → 1.1674</div><button className="primary">UNLOCK PREMIUM</button></div></section>}
function Track(){return <section className="page"><div className="stats"><div><span>TOTAL SIGNALS</span><b>126</b></div><div><span>TP HIT</span><b>82</b></div><div><span>SL HIT</span><b>44</b></div><div><span>WIN RATE</span><b>65.1%</b></div></div><div className="track-list">{sample.map((x,i)=><div className="track-row" key={i}><div><b>{x.pair}</b><span>{x.bias} · score {x.score}</span></div><span className="badge">TP HIT</span><span>1 : 2.3</span><span>Recorded</span></div>)}</div><p className="disclaimer">Track record is immutable once a signal is logged. Results are historical and do not guarantee future performance.</p></section>}
function Profile(){const [days,setDays]=useState(3);const [premium,setPremium]=useState(false);const used=premium?30:days;return <section className="page profile"><div className="profile-hero"><div className="avatar">K</div><div><span className="muted">KITAGENT MEMBER</span><h2>Workspace profile</h2><p>One clean account layer for your terminal, trading and history.</p></div><button className="primary" onClick={()=>setPremium(true)}>{premium?'PREMIUM ACTIVE':'UPGRADE'}</button></div><div className="lifetime"><h3>Lifetime map</h3><div className="map-grid">{Array.from({length:60},(_,i)=><i key={i} className={i%7===0?'hot':''}/>)}</div><div className="stats"><div><span>TODAY USERS</span><b>—</b></div><div><span>TRIAL LENGTH</span><b>3 DAYS</b></div><div><span>PREMIUM</span><b>30 DAYS</b></div></div></div><div className="trial"><div><span className="pill">{premium?'PREMIUM':'FREE TRIAL'}</span><h3>{premium?'Premium access active':'Trial access'}</h3><p>{premium?'Your premium window is active for 30 days.':'Your free trial runs for 3 days. When it expires, the signal desk is locked until you subscribe.'}</p></div><div className="counter"><b>{used}</b><span>DAYS ACCESS</span></div></div></section>}
function App(){const [page,setPage]=useState('terminal');const content={terminal:<Terminal/>,trading:<Trading/>,history:<History/>,signals:<Signals/>,track:<Track/>,profile:<Profile/>}[page];return <Layout page={page} setPage={setPage}>{content}</Layout>}

createRoot(document.getElementById('root')).render(<App/>);
