import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const CHAINS = {
  robinhood: { id: 4663, hex: '0x1237', name: 'Robinhood Chain', rpc: 'https://rpc.mainnet.chain.robinhood.com', explorer: 'https://robinhoodchain.blockscout.com', testnet: false },
  robinhoodTestnet: { id: 46630, hex: '0xb5c6', name: 'Robinhood Chain Testnet', rpc: 'https://rpc.testnet.chain.robinhood.com', explorer: 'https://explorer.testnet.chain.robinhood.com', testnet: true, faucet: 'https://faucet.testnet.chain.robinhood.com' },
};
const EXAMPLES=['Send 0.01 ETH to 0x…','Send 25 tokens to 0x…','Swap 25 USDC for ETH','Bridge 100 USDC to Robinhood Chain','Show my portfolio','Estimate gas','Get test ETH','Approve a spender','Transfer my NFT','Call this contract'];
const ACTIONS=[['send','Send','ETH / ERC-20','↗'],['swap','Swap','DEX route','⇄'],['bridge','Bridge','Cross-chain','◈'],['defi','DeFi','Lend / borrow / stake','◌'],['nft','NFT','ERC-721 / 1155','◇'],['contract','Contract','Any EVM call','⌁']];
const TESTNETS=[{name:'Robinhood Chain Testnet',chainId:46630,rpc:'https://rpc.testnet.chain.robinhood.com',faucet:'https://faucet.testnet.chain.robinhood.com',explorer:'https://explorer.testnet.chain.robinhood.com'},{name:'Custom EVM Testnet',chainId:'',rpc:'',faucet:'',explorer:''}];
const ERC20={transfer:'0xa9059cbb',approve:'0x095ea7b3',allowance:'0xdd62ed3e',decimals:'0x313ce567',symbol:'0x95d89b41',name:'0x06fdde03'};
const ERC721={safeTransfer:'0x42842e0e',approve:'0x095ea7b3',setApproval:'0xa22cb465'};
const ERC1155={safeTransfer:'0xf242432a',setApproval:'0xa22cb465'};
const ADDRESS_RE=/^0x[a-fA-F0-9]{40}$/;
function padWord(hex){return String(hex).replace(/^0x/,'').padStart(64,'0');} function addressWord(a){return padWord(a)} function uintWord(n){return padWord(BigInt(n).toString(16));}
function toBase(value,decimals=18){const[w='0',f='']=String(value||'0').trim().split('.');return BigInt(`${w.replace(/\D/g,'')||'0'}${f.replace(/\D/g,'').padEnd(decimals,'0').slice(0,decimals)}`)}
function toHex(value,decimals=18){return `0x${toBase(value,decimals).toString(16)}`}
function fromHex(hex,decimals=18){try{const n=BigInt(hex||'0'),b=10n**BigInt(decimals),w=n/b,f=(n%b).toString().padStart(decimals,'0').slice(0,6).replace(/0+$/,'');return f?`${w}.${f}`:w.toString()}catch{return'0'}}
function shorten(v,l=8,r=6){return v&&v.length>l+r+1?`${v.slice(0,l)}…${v.slice(-r)}`:v||''} function parseAddress(s){return String(s||'').match(/0x[a-fA-F0-9]{40}/)?.[0]||''} function parseAmount(s){return String(s||'').match(/\b\d+(?:\.\d+)?\b/)?.[0]||''}
function erc20Transfer(to,a,d){return `${ERC20.transfer}${addressWord(to)}${uintWord(toBase(a,d))}`} function erc20Approve(s,a,d){return `${ERC20.approve}${addressWord(s)}${uintWord(toBase(a,d))}`} function erc721Transfer(f,t,id){return `${ERC721.safeTransfer}${addressWord(f)}${addressWord(t)}${uintWord(id)}`} function er1155Transfer(f,t,id,a){return `${ERC1155.safeTransfer}${addressWord(f)}${addressWord(t)}${uintWord(id)}${uintWord(a)}${uintWord(0xa0)}${uintWord(0)}`} function setApprovalForAll(op,on){return `${ERC721.setApproval}${addressWord(op)}${padWord(on?'1':'0')}`}
async function rpc(chain,method,params=[]){const r=await fetch(chain.rpc,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method,params})});const d=await r.json();if(d.error)throw new Error(d.error.message||'RPC request failed');return d.result}
async function estimate(chain,tx){const gas=await rpc(chain,'eth_estimateGas',[tx]),price=await rpc(chain,'eth_gasPrice');return{gas:BigInt(gas),gasPrice:BigInt(price),fee:BigInt(gas)*BigInt(price)}}
async function readAllowance(chain,token,owner,spender){return BigInt(await rpc(chain,'eth_call',[{to:token,data:`${ERC20.allowance}${addressWord(owner)}${addressWord(spender)}`},'latest'])||'0x0')}
async function tokenMeta(chain,token){const[d,s,n]=await Promise.all([rpc(chain,'eth_call',[{to:token,data:ERC20.decimals},'latest']),rpc(chain,'eth_call',[{to:token,data:ERC20.symbol},'latest']).catch(()=>null),rpc(chain,'eth_call',[{to:token,data:ERC20.name},'latest']).catch(()=>null)]);const decode=x=>{try{if(!x)return'';const h=x.replace(/^0x/,'');if(h.length>=128){const off=Number(BigInt('0x'+h.slice(0,64))),len=Number(BigInt('0x'+h.slice(64,128)));if(off===32)return new TextDecoder().decode(Uint8Array.from(h.slice(128,128+len).match(/.{1,2}/g)||[],x=>parseInt(x,16))).replace(/[\0]/g,'').trim()}return new TextDecoder().decode(Uint8Array.from(h.match(/.{1,2}/g)||[],x=>parseInt(x,16))).replace(/[\0]/g,'').trim()}catch{return''}};return{decimals:Number(BigInt(d||'0x12')),symbol:decode(s),name:decode(n)}}
function classify(text){const t=text.toLowerCase();if(/portfolio|balance|holdings|what do i own/.test(t))return'portfolio';if(/faucet|test eth|testnet gas|get me gas/.test(t))return'faucet';if(/gas|fee estimate|estimate/.test(t))return'gas';if(/bridge|cross.?chain|move .* to .*chain/.test(t))return'bridge';if(/swap|exchange|trade .* for/.test(t))return'swap';if(/stake|lend|borrow|supply|repay|claim|deposit|withdraw/.test(t))return'defi';if(/nft|erc.?721|erc.?1155|collectible/.test(t))return'nft';if(/approve|allowance|contract|call|mint|wrap|unwrap|deploy/.test(t))return'contract';if(/send|transfer|pay|give/.test(t))return'send';return'command'}
function riskFor(tx,label){const w=[],data=tx.data||'0x';if(tx.value&&BigInt(tx.value)>0n)w.push(`Sends ${fromHex(tx.value)} ETH as native value`);if(data.startsWith(ERC20.approve)){const amount=BigInt('0x'+data.slice(74,138));w.push(amount===2n**256n-1n?'Unlimited ERC-20 approval':'ERC-20 allowance changes')}if(label.toLowerCase().includes('contract'))w.push('Arbitrary contract calldata — verify target and parameters');if(!w.length)w.push('No high-risk pattern detected by the local decoder');return w}
function Icon({name}){const m={bolt:'ϟ',wallet:'▣',activity:'⌁',command:'⌘',faucet:'♢',settings:'⚙',shield:'◇'};return <span className="icon-glyph">{m[name]||'•'}</span>}
function App(){
 const[chainKey,setChainKey]=useState('robinhood'),chain=CHAINS[chainKey];const[account,setAccount]=useState('');const[command,setCommand]=useState('');const[mode,setMode]=useState('command');const[action,setAction]=useState('send');const[status,setStatus]=useState('READY');const[notice,setNotice]=useState('');const[nativeBalance,setNativeBalance]=useState('—');const[tokens,setTokens]=useState([]);const[activity,setActivity]=useState([]);const[gas,setGas]=useState(null);const[loading,setLoading]=useState(false);const[sendTo,setSendTo]=useState('');const[sendAmount,setSendAmount]=useState('');const[tokenAddress,setTokenAddress]=useState('');const[tokenDecimals,setTokenDecimals]=useState('18');const[tokenAmount,setTokenAmount]=useState('');const[tokenRecipient,setTokenRecipient]=useState('');const[spender,setSpender]=useState('');const[allowance,setAllowance]=useState('');const[contractTo,setContractTo]=useState('');const[contractData,setContractData]=useState('0x');const[customValue,setCustomValue]=useState('');const[nftStandard,setNftStandard]=useState('721');const[nftContract,setNftContract]=useState('');const[nftRecipient,setNftRecipient]=useState('');const[nftTokenId,setNftTokenId]=useState('');const[nftOperator,setNftOperator]=useState('');const[quote,setQuote]=useState(null);const[quoteLoading,setQuoteLoading]=useState(false);const[customRpc,setCustomRpc]=useState('');const[customChainId,setCustomChainId]=useState('');const[customFaucet,setCustomFaucet]=useState('');const intent=useMemo(()=>classify(command),[command]);
 useEffect(()=>{if(window.ethereum)window.ethereum.request({method:'eth_accounts'}).then(a=>a?.[0]&&setAccount(a[0])).catch(()=>{})},[]);useEffect(()=>{if(account)refresh()},[account,chainKey]);
 async function connect(){if(!window.ethereum){setNotice('Install an EVM wallet to continue.');return}try{const a=await window.ethereum.request({method:'eth_requestAccounts'});if(a?.[0]){setAccount(a[0]);await switchNetwork()}}catch(e){setNotice(e.message||'Wallet connection cancelled.')}}
 async function switchNetwork(){try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:chain.hex}]})}catch(e){if(e.code!==4902)throw e;await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:chain.hex,chainName:chain.name,nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:[chain.rpc],blockExplorerUrls:[chain.explorer]}]})}}
 async function refresh(){try{setNativeBalance(fromHex(await rpc(chain,'eth_getBalance',[account,'latest'])));const base=chain.explorer+'/api/v2/addresses/'+account;const[tx,tb]=await Promise.all([fetch(base+'/transactions?filter=validated').then(r=>r.ok?r.json():{items:[]}),fetch(base+'/token-balances').then(r=>r.ok?r.json():[])]);setActivity((tx.items||[]).slice(0,12));setTokens((tb||[]).filter(x=>Number(x.value||0)>0).slice(0,16))}catch{setNotice('Public indexing is temporarily unavailable. RPC actions can still work.')}}
 async function simulate(tx,label='Transaction'){if(!account){setNotice('Connect your wallet first.');return null}try{setLoading(true);setStatus('UNDERSTANDING');await new Promise(r=>setTimeout(r,160));setStatus('VERIFYING');if(!ADDRESS_RE.test(tx.to))throw new Error('Invalid transaction target');const r=await estimate(chain,tx);setGas({units:r.gas.toString(),price:fromHex('0x'+r.gasPrice.toString(16)),fee:fromHex('0x'+r.fee.toString(16))});setStatus('SIMULATION PASSED');setNotice(`${label} · ${r.gas} gas · ~${fromHex('0x'+r.fee.toString(16))} ETH`);return r}catch(e){setStatus('SIMULATION FAILED');setNotice(e.message||'Simulation failed.');return null}finally{setLoading(false)}}
 async function sendTx(tx,label='Transaction'){if(!window.ethereum||!account){await connect();return}const r=await simulate(tx,label);if(!r)return;setNotice(riskFor(tx,label)[0]);setStatus('APPROVE');try{const hash=await window.ethereum.request({method:'eth_sendTransaction',params:[{...tx,gas:'0x'+r.gas.toString(16)}]});setStatus('BROADCAST');setNotice(`${label} broadcast · ${shorten(hash,12,8)}`);setActivity(p=>[{hash,to:tx.to,status:'pending',method:label},...p].slice(0,12));return hash}catch(e){setStatus('READY');setNotice(e.message||'Transaction rejected.')}}
 async function sendNative(){if(!ADDRESS_RE.test(sendTo)||!sendAmount){setNotice('Enter a valid recipient and amount.');return}await sendTx({from:account,to:sendTo,value:toHex(sendAmount)},'ETH transfer')}
 async function loadToken(){if(!ADDRESS_RE.test(tokenAddress)){setNotice('Enter a valid token contract.');return}try{const m=await tokenMeta(chain,tokenAddress);setTokenDecimals(String(m.decimals));setNotice(`${m.symbol||'Token'} · ${m.name||'ERC-20'} · ${m.decimals} decimals`)}catch(e){setNotice(e.message||'Token metadata unavailable.')}}
 async function sendToken(){if(!ADDRESS_RE.test(tokenAddress)||!ADDRESS_RE.test(tokenRecipient)||!tokenAmount){setNotice('Enter token, recipient and amount.');return}await sendTx({from:account,to:tokenAddress,data:erc20Transfer(tokenRecipient,tokenAmount,Number(tokenDecimals)),value:'0x0'},'ERC-20 transfer')}
 async function approve(){if(!ADDRESS_RE.test(tokenAddress)||!ADDRESS_RE.test(spender)||!tokenAmount){setNotice('Enter token, spender and amount.');return}await sendTx({from:account,to:tokenAddress,data:erc20Approve(spender,tokenAmount,Number(tokenDecimals)),value:'0x0'},'ERC-20 approval')}
 async function checkAllowance(){if(!ADDRESS_RE.test(tokenAddress)||!ADDRESS_RE.test(spender)||!account){setNotice('Connect wallet and enter token + spender.');return}try{const a=await readAllowance(chain,tokenAddress,account,spender);setAllowance(fromHex('0x'+a.toString(16),Number(tokenDecimals)))}catch(e){setNotice(e.message||'Allowance read failed.')}}
 async function simulateContract(){if(!ADDRESS_RE.test(contractTo)||!/^(0x[0-9a-fA-F]*)$/.test(contractData)){setNotice('Enter a valid contract address and calldata.');return}await simulate({from:account,to:contractTo,data:contractData,value:customValue?toHex(customValue):'0x0'},'Contract call')}
 async function executeContract(){if(!ADDRESS_RE.test(contractTo)||!/^(0x[0-9a-fA-F]*)$/.test(contractData)){setNotice('Enter a valid contract address and calldata.');return}await sendTx({from:account,to:contractTo,data:contractData,value:customValue?toHex(customValue):'0x0'},'Contract call')}
 async function nftAction(kind='transfer'){if(!ADDRESS_RE.test(nftContract)){setNotice('Enter NFT contract.');return}if(kind==='operator'){if(!ADDRESS_RE.test(nftOperator)){setNotice('Enter operator.');return}await sendTx({from:account,to:nftContract,data:setApprovalForAll(nftOperator,true),value:'0x0'},'NFT operator approval');return}if(!ADDRESS_RE.test(nftRecipient)||!nftTokenId){setNotice('Enter recipient and token ID.');return}const data=nftStandard==='721'?erc721Transfer(account,nftRecipient,nftTokenId):er1155Transfer(account,nftRecipient,nftTokenId,1);await sendTx({from:account,to:nftContract,data,value:'0x0'},`ERC-${nftStandard} transfer`)}
 async function getRoute(){if(!account){setNotice('Connect wallet before requesting a route.');return}setQuoteLoading(true);setQuote(null);try{const amount=parseAmount(command)||'1';const q=await fetch(`/api/quote?fromChain=${chain.id}&toChain=${chain.id}&fromToken=0x0000000000000000000000000000000000000000&toToken=0x0000000000000000000000000000000000000000&fromAmount=${toBase(amount).toString()}&fromAddress=${account}`).then(async r=>{if(!r.ok)throw new Error('No verified route is available for this asset pair.');return r.json()});setQuote(q);setNotice(`Verified route candidate: ${q.toolDetails?.name||q.tool||'aggregator'}`)}catch(e){setNotice(e.message||'Route service unavailable. Use Contract mode with verified router calldata.')}finally{setQuoteLoading(false)}}
 function executeIntent(){if(intent==='portfolio'){setMode('portfolio');return}if(intent==='faucet'){setMode('faucet');return}if(intent==='gas'){setAction('contract');return}if(intent==='send'){const a=parseAddress(command),amount=parseAmount(command);if(a){setSendTo(a);setSendAmount(amount);setAction(/usdc|usdt|token/.test(command.toLowerCase())?'contract':'send')}return}if(['swap','bridge','defi','nft','contract'].includes(intent))setAction(intent)}
 const risk=useMemo(()=>riskFor({to:contractTo,data:contractData,value:customValue?toHex(customValue):'0x0'},'Contract call'),[contractTo,contractData,customValue]);
 return <div className="app-shell"><aside className="rail"><div className="brand-mini"><div className="brand-mark"><i/><i/><i/></div><span>KIT<span>AGENT</span></span></div><nav>{[['command','command','Command'],['portfolio','wallet','Portfolio'],['activity','activity','Activity'],['faucet','faucet','Gas Station']].map(([m,i,l])=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}><Icon name={i}/><span>{l}</span></button>)}</nav><div className="rail-bottom"><button onClick={connect}><Icon name="wallet"/></button><button><Icon name="settings"/></button></div></aside><main className="main-shell"><header className="topbar"><div className="top-status"><span className="pulse-dot"/> KITAGENT <b>•</b> NON-CUSTODIAL</div><div className="top-controls"><select className="chain-picker" value={chainKey} onChange={e=>setChainKey(e.target.value)}><option value="robinhood">Robinhood Chain</option><option value="robinhoodTestnet">Robinhood Testnet</option></select><button className="wallet-button" onClick={connect}><span className="wallet-dot"/>{account?shorten(account):'Connect wallet'}</button></div></header>
 {mode==='command'&&<><section className="hero-row"><div><div className="eyebrow">ONCHAIN INTENT ENGINE</div><h1>Tell it what<br/><em>you want done.</em></h1><p>KitAgent converts intent into a transaction plan, verifies targets, estimates gas, simulates the call and asks your wallet to approve only after the route is understood.</p></div><div className="agent-core"><div className="core-orbit one"/><div className="core-orbit two"/><div className="core-dot"/><span>AGENT ONLINE</span></div></section><section className="command-grid"><div className="glow-card command-panel"><div className="panel-top"><div><div className="eyebrow">COMMAND</div><small>Describe an outcome, not a function call.</small></div><span className="guard"><Icon name="shield"/> NO KEYS STORED</span></div><textarea value={command} onChange={e=>setCommand(e.target.value)} placeholder="e.g. Swap 100 USDC for ETH and leave enough ETH for gas…"/><div className="command-footer"><div className="quick-row">{EXAMPLES.slice(0,5).map(x=><button key={x} onClick={()=>setCommand(x)}>{x}</button>)}</div><button className="execute-intent" disabled={!command.trim()||loading} onClick={executeIntent}>BUILD PLAN ↗</button></div><div className="intent-reading"><b>{intent.toUpperCase()}</b><i/>UNDERSTAND <i/>VERIFY <i/>SIMULATE <i/>APPROVE</div></div><div className="glow-card agent-panel"><div className="workbench-head"><div><div className="eyebrow">EXECUTION GUARD</div><small>Every signed action passes the same gate.</small></div><span className="status-chip">{status}</span></div><div className="pipeline">{[['01','UNDERSTAND','Parse user intent'],['02','VERIFY','Target + permissions'],['03','SIMULATE','Gas + revert check'],['04','APPROVE','Wallet signature']].map(([n,a,d],i)=><div key={n} className={i<2?'stage-live':''}><span>{n}</span><section><b>{a}</b><small>{d}</small></section><i>{i<2?'✓':'·'}</i></div>)}</div><div className="safety"><Icon name="shield"/><div><b>Non-custodial by design</b><small>KitAgent never receives or stores your seed phrase or private key.</small></div></div></div></section><div className="action-strip">{ACTIONS.map(([id,title,sub,g])=><button key={id} className={action===id?'selected':''} onClick={()=>setAction(id)}><span className="action-glyph">{g}</span><span><b>{title}</b><small>{sub}</small></span><span>›</span></button>)}</div><section className="glow-card workbench">
 {action==='send'&&<><div className="workbench-head"><div><div className="eyebrow">TRANSFER ENGINE</div><small>Native ETH or ERC-20 value transfer</small></div><span className="chain-pill">{chain.name}</span></div><div className="form-grid"><label>RECIPIENT<input value={sendTo} onChange={e=>setSendTo(e.target.value)} placeholder="0x…"/></label><label>ETH AMOUNT<input value={sendAmount} onChange={e=>setSendAmount(e.target.value)} placeholder="0.01"/></label></div><div className="button-row"><button onClick={()=>simulate({from:account,to:sendTo,value:toHex(sendAmount||'0')},'ETH transfer')}>SIMULATE</button><button className="primary" onClick={sendNative}>SEND ETH</button></div></>}
 {action==='contract'&&<><div className="workbench-head"><div><div className="eyebrow">UNIVERSAL EVM EXECUTOR</div><small>Any verified contract, calldata, value or approval flow.</small></div><span className="chain-pill">RISK DECODER ACTIVE</span></div><div className="form-grid"><label>CONTRACT<input value={contractTo} onChange={e=>setContractTo(e.target.value)} placeholder="0x…"/></label><label>VALUE · ETH<input value={customValue} onChange={e=>setCustomValue(e.target.value)} placeholder="0"/></label><label className="form-span">CALLDATA<textarea value={contractData} onChange={e=>setContractData(e.target.value)} placeholder="0x…"/></label></div><div className="route-tags">{risk.map(x=><span key={x}>⚠ {x}</span>)}</div><div className="button-row"><button onClick={simulateContract}>SIMULATE</button><button className="primary" onClick={executeContract}>EXECUTE</button></div></>}
 {action==='swap'&&<><div className="workbench-head"><div><div className="eyebrow">SWAP ROUTER</div><small>Route discovery is separated from signing. No fabricated quote is shown.</small></div><span className="chain-pill">ROUTE-FIRST</span></div><div className="form-grid"><label className="form-span">INTENT<input value={command} onChange={e=>setCommand(e.target.value)} placeholder="Swap 25 USDC for ETH"/></label></div>{quote&&<div className="feature-card"><div className="feature-icon">⇄</div><div><h3>{quote.toolDetails?.name||quote.tool||'Verified route'}</h3><p>Quote received. Review the exact transaction target and calldata before wallet approval.</p></div></div>}<div className="button-row"><button onClick={getRoute}>{quoteLoading?'FINDING…':'FIND VERIFIED ROUTE'}</button></div></>}
 {action==='bridge'&&<><div className="workbench-head"><div><div className="eyebrow">CROSS-CHAIN ROUTER</div><small>Bridge planning with explicit destination and asset checks.</small></div><span className="chain-pill">NO AUTO-SIGN</span></div><div className="form-grid"><label className="form-span">BRIDGE INTENT<input value={command} onChange={e=>setCommand(e.target.value)} placeholder="Bridge 100 USDC to Robinhood Chain"/></label></div><div className="feature-card"><div className="feature-icon">◈</div><div><h3>Route before signature</h3><p>KitAgent only presents a route when an aggregator returns a concrete transaction. Otherwise use a verified bridge contract in Contract mode.</p></div></div><div className="button-row"><button onClick={getRoute}>{quoteLoading?'CHECKING…':'CHECK ROUTE'}</button></div></>}
 {action==='defi'&&<><div className="workbench-head"><div><div className="eyebrow">DEFI ADAPTER LAYER</div><small>Protocol actions are adapter-driven, not guessed from names.</small></div><span className="chain-pill">VERIFIED CALLS ONLY</span></div><div className="form-grid"><label className="form-span">ACTION<input value={command} onChange={e=>setCommand(e.target.value)} placeholder="Supply 100 USDC to Morpho"/></label></div><div className="feature-card"><div className="feature-icon">◌</div><div><h3>Protocol guard</h3><p>Adapters must provide verified contract addresses, ABI-calldata and simulation before signing. Generic Contract mode remains available for custom protocols.</p><div className="route-tags"><span>SUPPLY</span><span>WITHDRAW</span><span>BORROW</span><span>REPAY</span><span>STAKE</span><span>CLAIM</span></div></div></div></>}
 {action==='nft'&&<><div className="workbench-head"><div><div className="eyebrow">NFT ENGINE</div><small>ERC-721 and ERC-1155 transfer + operator approval.</small></div><span className="chain-pill">SAFE TRANSFER</span></div><div className="form-grid"><label>STANDARD<select value={nftStandard} onChange={e=>setNftStandard(e.target.value)}><option value="721">ERC-721</option><option value="1155">ERC-1155</option></select></label><label>CONTRACT<input value={nftContract} onChange={e=>setNftContract(e.target.value)} placeholder="0x…"/></label><label>RECIPIENT<input value={nftRecipient} onChange={e=>setNftRecipient(e.target.value)} placeholder="0x…"/></label><label>TOKEN ID<input value={nftTokenId} onChange={e=>setNftTokenId(e.target.value)} placeholder="1"/></label><label>OPERATOR<input value={nftOperator} onChange={e=>setNftOperator(e.target.value)} placeholder="0x…"/></label></div><div className="button-row"><button onClick={()=>nftAction('operator')}>APPROVE OPERATOR</button><button className="primary" onClick={()=>nftAction('transfer')}>TRANSFER NFT</button></div></>}
 </section>{gas&&<div className="fee-box"><span>ESTIMATED GAS</span><b>{gas.fee} ETH</b><small>{gas.units} units · {gas.price} ETH/gas</small></div>}{notice&&<div className="bottom-console"><span>{notice}</span><b>{status}</b></div>}</>}
 {mode==='portfolio'&&<section className="glow-card data-page"><div className="page-head"><div><div className="eyebrow">PORTFOLIO</div><h2>Wallet overview</h2><p>{account?shorten(account,10,8):'Connect a wallet to inspect holdings.'}</p></div><button onClick={refresh}>REFRESH</button></div><div className="portfolio-total"><span>NATIVE BALANCE</span><strong>{nativeBalance} <small>ETH</small></strong><i>{chain.name}</i></div><div className="table-head"><span>ASSET</span><span>BALANCE</span><span>CONTRACT</span></div>{tokens.length?tokens.map((t,i)=><div className="token-row" key={i}><b>{t.token?.symbol||'TOKEN'}</b><span>{t.value||'0'}</span><small>{shorten(t.token?.address||t.token?.contract_address||'')}</small></div>):<div className="empty">No indexed token balances found.</div>}</section>}
 {mode==='activity'&&<section className="glow-card data-page"><div className="page-head"><div><div className="eyebrow">ACTIVITY</div><h2>Transaction stream</h2><p>Indexed directly from the active chain explorer.</p></div><button onClick={refresh}>SYNC</button></div><div className="activity-list">{activity.length?activity.map((x,i)=><a key={i} href={`${chain.explorer}/tx/${x.hash}`} target="_blank" rel="noreferrer"><span className="tx-index">{String(i+1).padStart(2,'0')}</span><div><b>{x.method||x.decoded_input?.method_call||'Transaction'}</b><small>{shorten(x.from?.hash||x.from||'')} → {shorten(x.to?.hash||x.to||'')}</small></div><strong>{x.status||'validated'}</strong></a>):<div className="empty">Connect and sync the wallet.</div>}</div></section>}
 {mode==='faucet'&&<section className="glow-card data-page faucet-page"><div className="page-head"><div><div className="eyebrow">GAS STATION</div><h2>Fund testnet gas.</h2><p>KitAgent never invents faucet availability. It links only to a configured official faucet.</p></div><span className="big-orb">ϟ</span></div><div className="faucet-grid">{TESTNETS.map((n,i)=><div key={n.name}><span>NETWORK {i+1}</span><b>{n.name}</b><small>{n.chainId?`Chain ID ${n.chainId}`:'Bring any EVM testnet RPC'}</small><div className="faucet-actions">{n.faucet?<a className="button-link" href={n.faucet} target="_blank" rel="noreferrer">OPEN FAUCET ↗</a>:<button className="button-link" onClick={()=>{setCustomRpc(n.rpc);setCustomChainId(n.chainId);setCustomFaucet(n.faucet)}}>CONFIGURE</button>}</div></div>)}</div><div className="feature-card"><div className="feature-icon">ϟ</div><div><h3>Universal testnet gas checker</h3><p>Configure any EVM testnet RPC and KitAgent can read native balance and estimate gas. Faucet funding is linked only when an official URL is supplied.</p><div className="form-grid"><label>RPC<input value={customRpc} onChange={e=>setCustomRpc(e.target.value)} placeholder="https://…"/></label><label>CHAIN ID<input value={customChainId} onChange={e=>setCustomChainId(e.target.value)} placeholder="12345"/></label><label>OFFICIAL FAUCET<input value={customFaucet} onChange={e=>setCustomFaucet(e.target.value)} placeholder="https://…"/></label></div></div></div><div className="faucet-note"><Icon name="shield"/><span><b>Gas sponsorship:</b> Robinhood Chain supports ERC-4337 account abstraction and gas sponsorship infrastructure. KitAgent will only label sponsorship active when a real bundler/paymaster endpoint is configured.</span></div></section>}
 </main></div>}
createRoot(document.getElementById('root')).render(<App/>);
