import {useEffect,useMemo,useState} from 'react';
import './signal-history.css';
import {Activity,BarChart3,ChevronRight,RefreshCw,Target,TrendingDown,TrendingUp} from 'lucide-react';
import {auth} from './firebase.js';

function num(v){return v==null||Number.isNaN(Number(v))?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:Number(v)>=1000?2:Number(v)>=1?5:8});}
function when(v){if(!v)return '—';const d=v?.toDate?v.toDate():new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});}

export default function SignalHistory({activity=[]}){
 const [signals,setSignals]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[view,setView]=useState('signals');
 const load=async()=>{const user=auth?.currentUser;if(!user){setSignals([]);setLoading(false);return}setLoading(true);setError('');try{const token=await user.getIdToken();const r=await fetch('/api/signals',{headers:{Authorization:`Bearer ${token}`}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Signal history could not be loaded.');setSignals(Array.isArray(body.signals)?body.signals:[]);}catch(e){setError(e.message||'Signal history could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{load();const onSignal=()=>load();window.addEventListener('kitagent-signal-recorded',onSignal);return()=>window.removeEventListener('kitagent-signal-recorded',onSignal)},[]);
 const visible=useMemo(()=>signals.filter(s=>filter==='all'||filter==='open'&&s.status==='open'||filter==='watching'&&s.status==='watching'||filter==='closed'&&['target_hit','stop_hit','expired','closed'].includes(s.status)),[signals,filter]);
 const stats=useMemo(()=>{const closed=signals.filter(s=>['target_hit','stop_hit','expired','closed'].includes(s.status));const wins=closed.filter(s=>s.result==='win');const pnl=closed.map(s=>Number(s.pnlPercent)).filter(Number.isFinite);return {total:signals.length,open:signals.filter(s=>s.status==='open').length,winRate:closed.length?Math.round(wins.length/closed.length*100):null,avgPnl:pnl.length?(pnl.reduce((a,b)=>a+b,0)/pnl.length):null}},[signals]);
 return <section className="signal-history"><div className="signal-history-head"><div><span className="tiny-label">TRACK RECORD</span><h2>History</h2><p>Your preserved signal track record and workspace actions, with live account history kept separate from market analysis.</p></div><button className="signal-refresh" onClick={load} disabled={loading}><RefreshCw size={14} className={loading?'spin':''}/> Refresh</button></div><div className="history-view-tabs"><button className={view==='signals'?'active':''} onClick={()=>setView('signals')}><BarChart3 size={12}/> Signals</button><button className={view==='activity'?'active':''} onClick={()=>setView('activity')}><Activity size={12}/> Activity{activity.length?` (${activity.length})`:''}</button></div>{view==='signals'?<><div className="signal-stats"><Stat label="GENERATED" value={stats.total}/><Stat label="OPEN" value={stats.open}/><Stat label="WIN RATE" value={stats.winRate==null?'—':`${stats.winRate}%`}/><Stat label="AVG P&L" value={stats.avgPnl==null?'—':`${stats.avgPnl>=0?'+':''}${stats.avgPnl.toFixed(2)}%`}/></div><div className="signal-filters">{[['all','All'],['open','Open'],['watching','Watching'],['closed','Closed']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div>{loading?<div className="signal-empty"><RefreshCw className="spin"/><span>Loading your track record…</span></div>:error?<div className="signal-empty"><span>{error}</span><button onClick={load}>Retry</button></div>:visible.length===0?<div className="signal-empty"><BarChart3/><b>No signals in this view</b><span>Generate a market analysis and KitSetups will preserve the setup here.</span></div>:<div className="signal-list">{visible.map(signal=><SignalCard key={signal.id||signal.signalId} signal={signal}/>)}</div>}</>:<ActivityView activity={activity}/>}</section>
}
function Stat({label,value}){return <div><span>{label}</span><b>{value}</b></div>}
function ActivityView({activity}){return activity.length?<div className="activity-list">{activity.map((item,i)=><article className="activity-card" key={`${item.hash||item.label||'activity'}-${i}`}><span className="activity-icon"><Activity size={13}/></span><div><b>{item.label||item.type||'Workspace action'}</b><small>{item.type||'Action'} · {item.status||'Recorded'} · {item.time||'Recent'}</small>{item.hash&&<code>{item.hash}</code>}</div></article>)}</div>:<div className="signal-empty"><Activity/><b>No workspace activity yet</b><span>Approved actions and submitted transactions will appear here.</span></div>}
function SignalCard({signal:s}){const long=s.direction==='LONG',closed=['target_hit','stop_hit','expired','closed'].includes(s.status),win=s.result==='win';return <article className="signal-card"><div className="signal-card-top"><div className={`signal-direction ${long?'long':s.direction==='SHORT'?'short':'wait'}`}>{long?<TrendingUp size={14}/>:s.direction==='SHORT'?<TrendingDown size={14}/>:<Target size={14}/>} {s.direction}</div><div className="signal-card-meta"><span>{s.market?.toUpperCase()} · {s.timeframe}</span><b>{when(s.generatedAt)}</b></div></div><div className="signal-main"><div><span className="signal-symbol">{s.symbol}</span><small>{s.signalId}</small></div><strong className={closed?(win?'positive':'negative'):''}>{closed&&Number.isFinite(Number(s.pnlPercent))?`${Number(s.pnlPercent)>=0?'+':''}${Number(s.pnlPercent).toFixed(2)}%`:s.confidence!=null?`${s.confidence}% confidence`:'Watching'}</strong></div><div className="signal-levels"><Level label="ENTRY" value={num(s.entry)}/><Level label="STOP" value={num(s.stopLoss)}/><Level label="TP1" value={num(s.takeProfit1)}/><Level label="TP2" value={num(s.takeProfit2)}/><Level label="R:R" value={s.riskReward||'—'}/></div><div className="signal-card-foot"><span className={`signal-status ${closed?(win?'won':'lost'):s.status}`}>{closed?(win?'TARGET HIT':'CLOSED'):s.status?.replace('_',' ')}</span><button type="button">View setup <ChevronRight size={13}/></button></div></article>}
function Level({label,value}){return <div><span>{label}</span><b>{value}</b></div>}
