import { createAppKit } from '@reown/appkit';
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi';
import { getAccount, watchAccount } from '@wagmi/core';
import { defineChain } from '@reown/appkit/networks';
const PROJECT_ID=import.meta.env.VITE_REOWN_PROJECT_ID||'94314a4ef9da3dd09a3b858adef781e9';
const ROBINHOOD_RPC='https://rpc.mainnet.chain.robinhood.com';const ROBINHOOD_CHAIN_ID='0x1237';
const ROBINHOOD_CHAIN_PARAMS={chainId:ROBINHOOD_CHAIN_ID,chainName:'Robinhood Chain',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:[ROBINHOOD_RPC],blockExplorerUrls:['https://robinhoodchain.blockscout.com']};
export const ROBINHOOD_CHAIN=defineChain({id:4663,caipNetworkId:'eip155:4663',chainNamespace:'eip155',name:'Robinhood Chain',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:{default:{http:[ROBINHOOD_RPC]},public:{http:[ROBINHOOD_RPC]}},blockExplorers:{default:{name:'Robinhood Chain Explorer',url:'https://robinhoodchain.blockscout.com'}}});
const metadata={name:'KitSetups',description:'AI command center for the onchain markets',url:window.location.origin,icons:[`${window.location.origin}/kitagent-logo.svg`]};
const networks=[ROBINHOOD_CHAIN];const customRpcUrls={'eip155:4663':[{url:ROBINHOOD_RPC}]};
const wagmiAdapter=new WagmiAdapter({networks,projectId:PROJECT_ID,ssr:false,customRpcUrls});const wagmiConfig=wagmiAdapter.wagmiConfig;
export const appKit=createAppKit({adapters:[wagmiAdapter],networks,defaultNetwork:ROBINHOOD_CHAIN,projectId:PROJECT_ID,metadata,customRpcUrls,experimental_preferUniversalLinks:true,allWallets:'ONLY_MOBILE',enableWallets:true,enableReconnect:true,enableNetworkSwitch:true,enableMobileFullScreen:true,features:{analytics:false,email:false,socials:[]},themeMode:'dark',themeVariables:{'--w3m-accent':'#00C7FE','--w3m-color-mix':'#00C7FE','--w3m-color-mix-strength':18}});
if(typeof window!=='undefined')window.__kitagentAppKit=appKit;
function accountState(){const account=getAccount(wagmiConfig);return{isConnected:Boolean(account.isConnected&&account.address),address:account.address||''}}
let providerPromise=null;
async function connectInjectedWallet(){const ethereum=typeof window!=='undefined'?window.ethereum:null;if(!ethereum?.request)return null;const accounts=await ethereum.request({method:'eth_requestAccounts'});const address=accounts?.[0];if(!address)throw new Error('No wallet account was returned.');try{await ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:ROBINHOOD_CHAIN_ID}]})}catch(error){if(error?.code!==4902)throw error;await ethereum.request({method:'wallet_addEthereumChain',params:[ROBINHOOD_CHAIN_PARAMS]});await ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:ROBINHOOD_CHAIN_ID}]})}return{address,provider:ethereum}}
function waitForConnection(timeoutMs=20000){const current=accountState();if(current.isConnected)return Promise.resolve({address:current.address,provider:appKit.getWalletProvider?.()||null});if(providerPromise)return providerPromise;providerPromise=new Promise((resolve,reject)=>{let timer;let unsubscribe;const finish=(result,error)=>{if(timer)clearTimeout(timer);if(typeof unsubscribe==='function')unsubscribe();providerPromise=null;error?reject(error):resolve(result)};try{unsubscribe=watchAccount(wagmiConfig,{onChange(account){if(account.isConnected&&account.address)finish({address:account.address,provider:appKit.getWalletProvider?.()||null})}})}catch(error){finish(null,error);return}timer=setTimeout(()=>finish(null,new Error('Wallet connection timed out. Open KitSetups inside your wallet app or try the wallet browser.')),timeoutMs)});return providerPromise}
export async function connectWallet(){try{const injected=await connectInjectedWallet();if(injected)return injected;const current=accountState();if(!current.isConnected)await appKit.open({view:'Connect',namespace:'eip155'});const result=await waitForConnection();return{address:result.address,provider:appKit.getWalletProvider?.()||result.provider||null}}catch(error){providerPromise=null;try{if(typeof appKit.close==='function')await appKit.close()}catch(_){}throw error}}
export async function resumePendingWalletConnection(){const ethereum=typeof window!=='undefined'?window.ethereum:null;if(ethereum?.request){try{const accounts=await ethereum.request({method:'eth_accounts'});if(accounts?.[0])return{address:accounts[0],provider:ethereum}}catch{}}const current=accountState();if(!current.isConnected)return null;return{address:current.address,provider:appKit.getWalletProvider?.()||null}}
export function getActiveProvider(){return appKit.getWalletProvider?.()||(typeof window!=='undefined'?window.ethereum||null:null)}
export function getConnectedAddress(){return accountState().address||(typeof window!=='undefined'?window.ethereum?.selectedAddress||'':'')}
export function isWalletConnected(){return accountState().isConnected||Boolean(typeof window!=='undefined'&&window.ethereum?.selectedAddress)}
export async function disconnectWallet(){if(typeof appKit.disconnect==='function')await appKit.disconnect()}
