import {ADDRESS_RE,HEX_RE,fromBase,erc20Allowance,ERC20} from './abi.js';
const ERC721_TRANSFER='0x42842e0e',ERC1155_TRANSFER='0xf242432a',SET_APPROVAL='0xa22cb465';
export async function rpc(chain,method,params=[]){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(chain.rpc,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method,params}),signal:controller.signal});if(!r.ok)throw new Error(`RPC HTTP ${r.status}`);const d=await r.json();if(d.error)throw new Error(d.error.message||'RPC request failed');return d.result}finally{clearTimeout(timer)}}
export async function networkHealth(chain){const [id,block,price]=await Promise.all([rpc(chain,'eth_chainId'),rpc(chain,'eth_blockNumber'),rpc(chain,'eth_gasPrice')]);return{chainId:Number(BigInt(id)),block:Number(BigInt(block)),gasPrice:BigInt(price)}}
export async function estimate(chain,tx){const gas=await rpc(chain,'eth_estimateGas',[tx]);const gasPrice=tx.maxFeePerGas?BigInt(tx.maxFeePerGas):BigInt(await rpc(chain,'eth_gasPrice'));const units=BigInt(gas);return{gas:units,gasPrice,fee:units*gasPrice}}
export async function balance(chain,address){return BigInt(await rpc(chain,'eth_getBalance',[address,'latest']))}
export async function erc20Balance(chain,token,address,decimals=18){const raw=await rpc(chain,'eth_call',[{to:token,data:`${ERC20.balanceOf}${address.slice(2).padStart(64,'0')}`},'latest']);return fromBase(BigInt(raw||'0x0'),decimals)}
export async function allowance(chain,token,owner,spender,decimals=18){const raw=await rpc(chain,'eth_call',[{to:token,data:erc20Allowance(owner,spender)},'latest']);return fromBase(BigInt(raw||'0x0'),decimals)}
export async function receipt(chain,hash){return rpc(chain,'eth_getTransactionReceipt',[hash])}
export async function waitForReceipt(chain,hash,timeout=180000){const started=Date.now();while(Date.now()-started<timeout){const r=await receipt(chain,hash);if(r)return r;await new Promise(x=>setTimeout(x,1800))}throw new Error('Confirmation timed out; transaction may still be pending')}
export function validateTx(tx){if(!tx||!ADDRESS_RE.test(tx.to))throw new Error('Invalid transaction target');if(tx.data&&!HEX_RE.test(tx.data))throw new Error('Invalid calldata');if(tx.value&&BigInt(tx.value)<0n)throw new Error('Invalid value');return true}
export async function preflight(chain,tx,{account,requiredToken,requiredAmount,requiredDecimals=18,spender}={}){validateTx(tx);if(!account)throw new Error('Connect a wallet first');const [net,native]=await Promise.all([networkHealth(chain),balance(chain,account)]);if(net.chainId!==chain.id)throw new Error(`RPC returned chain ${net.chainId}, expected ${chain.id}`);const estimateResult=await estimate(chain,tx);const total=estimateResult.fee+BigInt(tx.value||'0');if(native<total)throw new Error(`Insufficient ETH for value + gas. Need at least ${fromBase(total)} ETH`);let tokenAllowance=null;if(requiredToken&&requiredAmount!==undefined&&spender&&spender.toLowerCase()!==requiredToken.toLowerCase()){const raw=await rpc(chain,'eth_call',[{to:requiredToken,data:erc20Allowance(account,spender)},'latest']);tokenAllowance=BigInt(raw||'0x0');if(tokenAllowance<BigInt(requiredAmount))throw new Error('Token allowance is below the requested amount')}return{...estimateResult,nativeBalance:native,tokenAllowance}}
export function decode(tx,label='Transaction'){const data=tx.data||'0x',selector=data.slice(0,10).toLowerCase();const known={ [ERC20.transfer]:'ERC-20 transfer',[ERC20.approve]:'ERC-20 approval',[ERC20.allowance]:'ERC-20 allowance read',[ERC20.balanceOf]:'ERC-20 balance read',[ERC721_TRANSFER]:'ERC-721 safe transfer',[ERC1155_TRANSFER]:'ERC-1155 safe transfer',[SET_APPROVAL]:'NFT operator approval'};return{label,selector,method:known[selector]||'Contract call',target:tx.to,value:tx.value||'0x0',calldataBytes:Math.max(0,(data.length-2)/2)}}
export function risk(tx,label='Transaction'){const data=(tx.data||'').toLowerCase(),warnings=[];if(tx.value&&BigInt(tx.value)>0n)warnings.push('Native ETH value is attached');if(data.startsWith(ERC20.approve)){const amount=BigInt(`0x${data.slice(74,138)}`);warnings.push(amount===2n**256n-1n?'Unlimited token approval':'Token allowance change')}if(data.length>10&&!([ERC20.transfer,ERC20.approve,ERC20.allowance,ERC20.balanceOf,ERC721_TRANSFER,ERC1155_TRANSFER,SET_APPROVAL].includes(data.slice(0,10))))warnings.push('Contract calldata is not fully decoded locally; verify target and parameters');if(/deploy/i.test(label))warnings.push('Contract deployment creates a new on-chain contract');return warnings.length?warnings:['No local high-risk pattern detected']}
