import {ADDRESS_RE,HEX_RE,fromBase,erc20Allowance,ERC20} from './abi.js';
const SELECTORS={transfer:ERC20.transfer,approve:ERC20.approve,allowance:ERC20.allowance,balanceOf:ERC20.balanceOf,permit:'0xd505accf',permit2:'0x2b67b570',erc721:'0x42842e0e',erc1155:'0xf242432a',approvalForAll:'0xa22cb465'};
export async function rpc(chain,method,params=[]){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(chain.rpc,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method,params}),signal:controller.signal});if(!r.ok)throw new Error(`RPC HTTP ${r.status}`);const d=await r.json();if(d.error)throw new Error(d.error.message||'RPC request failed');return d.result}finally{clearTimeout(timer)}}
export async function networkHealth(chain){const [id,block,price]=await Promise.all([rpc(chain,'eth_chainId'),rpc(chain,'eth_blockNumber'),rpc(chain,'eth_gasPrice')]);return{chainId:Number(BigInt(id)),block:Number(BigInt(block)),gasPrice:BigInt(price)}}
export async function feeData(chain){const price=BigInt(await rpc(chain,'eth_gasPrice'));let priority=0n;try{priority=BigInt(await rpc(chain,'eth_maxPriorityFeePerGas'))}catch{}return{gasPrice:price,maxPriorityFeePerGas:priority,maxFeePerGas:price+priority}}
export async function estimate(chain,tx){const gas=await rpc(chain,'eth_estimateGas',[tx]);const fd=await feeData(chain);const units=BigInt(gas);return{gas:units,gasPrice:fd.gasPrice,maxFeePerGas:fd.maxFeePerGas,maxPriorityFeePerGas:fd.maxPriorityFeePerGas,fee:units*fd.gasPrice}}
export async function balance(chain,address){return BigInt(await rpc(chain,'eth_getBalance',[address,'latest']))}
export async function erc20Balance(chain,token,address,decimals=18){const raw=await rpc(chain,'eth_call',[{to:token,data:`${ERC20.balanceOf}${address.slice(2).padStart(64,'0')}`},'latest']);return fromBase(BigInt(raw||'0x0'),decimals)}
export async function allowance(chain,token,owner,spender,decimals=18){const raw=await rpc(chain,'eth_call',[{to:token,data:erc20Allowance(owner,spender)},'latest']);return fromBase(BigInt(raw||'0x0'),decimals)}
export async function receipt(chain,hash){return rpc(chain,'eth_getTransactionReceipt',[hash])}
export async function waitForReceipt(chain,hash,timeout=180000){const started=Date.now();while(Date.now()-started<timeout){const r=await receipt(chain,hash);if(r)return r;await new Promise(x=>setTimeout(x,1800))}throw new Error('Confirmation timed out; transaction may still be pending')}
export async function simulate(chain,tx){return rpc(chain,'eth_call',[{from:tx.from,to:tx.to,data:tx.data||'0x',value:tx.value||'0x0'},'latest'])}
export function validateTx(tx){if(!tx||!ADDRESS_RE.test(tx.to))throw new Error('Invalid transaction target');if(tx.data&&!HEX_RE.test(tx.data))throw new Error('Invalid calldata');if(tx.value&&BigInt(tx.value)<0n)throw new Error('Invalid value');return true}
export async function preflight(chain,tx,{account,requiredToken,requiredAmount,requiredDecimals=18,spender}={}){validateTx(tx);if(!account)throw new Error('Connect a wallet first');const [net,native]=await Promise.all([networkHealth(chain),balance(chain,account)]);if(net.chainId!==chain.id)throw new Error(`RPC returned chain ${net.chainId}, expected ${chain.id}`);const estimateResult=await estimate(chain,tx);const total=estimateResult.fee+BigInt(tx.value||'0');if(native<total)throw new Error(`Insufficient ETH for value + gas. Need at least ${fromBase(total)} ETH`);let tokenAllowance=null;if(requiredToken&&requiredAmount!==undefined&&spender&&spender.toLowerCase()!==requiredToken.toLowerCase()){const raw=await rpc(chain,'eth_call',[{to:requiredToken,data:erc20Allowance(account,spender)},'latest']);tokenAllowance=BigInt(raw||'0x0');if(tokenAllowance<BigInt(requiredAmount))throw new Error('Token allowance is below the requested amount')}let simulation='skipped';try{await simulate(chain,tx);simulation='passed'}catch(e){throw new Error(`Simulation reverted: ${e.message}`)}return{...estimateResult,nativeBalance:native,tokenAllowance,simulation}}
export function decode(tx,label='Transaction'){const data=tx.data||'0x',selector=data.slice(0,10).toLowerCase();const known=Object.fromEntries(Object.entries(SELECTORS).map(([k,v])=>[v,k]));return{label,selector,method:known[selector]||'Contract call',target:tx.to,value:tx.value||'0x0',calldataBytes:Math.max(0,(data.length-2)/2),decoded:known[selector]?`Known ${known[selector]} selector`:'Unknown calldata'}}
export function risk(tx,label='Transaction'){const data=(tx.data||'').toLowerCase(),warnings=[];if(tx.value&&BigInt(tx.value)>0n)warnings.push('Native ETH value is attached');if(data.startsWith(ERC20.approve)){const amount=BigInt(`0x${data.slice(74,138)}`);warnings.push(amount===2n**256n-1n?'Unlimited token approval':'Token allowance change')}if(data.startsWith(SELECTORS.permit)||data.startsWith(SELECTORS.permit2))warnings.push('Signature-based token permission flow');if(data.length>10&&!Object.values(SELECTORS).includes(data.slice(0,10)))warnings.push('Contract calldata is not fully decoded locally; verify target and parameters');if(/deploy/i.test(label))warnings.push('Contract deployment creates a new on-chain contract');return warnings.length?warnings:['No local high-risk pattern detected']}
export function transactionSummary(tx,preflightResult){return{target:tx.to,value:tx.value||'0x0',gasUnits:preflightResult?.gas?.toString()||null,estimatedFee:preflightResult?.fee?fromBase(preflightResult.fee,18):null,simulation:preflightResult?.simulation||'unknown'}}