const ADDRESS=/^0x[a-fA-F0-9]{40}$/;
const HEX=/^0x[0-9a-fA-F]*$/;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
export const TERMINAL_STATES=new Set(['confirmed','failed','reverted','dropped','replaced','expired']);
export function lifecycleRecord(input={}){return{hash:input.hash||null,state:input.state||'pending',submittedAt:input.submittedAt||Date.now(),updatedAt:Date.now(),blockNumber:input.blockNumber||null,receiptStatus:input.receiptStatus??null,replacementHash:input.replacementHash||null,error:input.error||null,confirmations:Number(input.confirmations||0),routeId:input.routeId||null,stepIndex:Number(input.stepIndex||0),stepCount:Number(input.stepCount||1)}}
export async function txStatus(rpc,hash){if(!hash)throw new Error('Missing transaction hash');const tx=await rpc('eth_getTransactionByHash',[hash]);const receipt=await rpc('eth_getTransactionReceipt',[hash]);if(receipt)return{state:receipt.status==='0x1'?'confirmed':'reverted',tx,receipt};if(tx)return{state:'pending',tx,receipt:null};return{state:'dropped',tx:null,receipt:null}}
export async function waitLifecycle(rpc,hash,{timeout=180000,poll=1800,confirmations=1,onUpdate}={}){const started=Date.now();let last=null;while(Date.now()-started<timeout){const s=await txStatus(rpc,hash);let next=s.state;if(s.receipt&&confirmations>1){const latest=BigInt(await rpc('eth_blockNumber'));const mined=BigInt(s.receipt.blockNumber);next=latest-mined+1n>=BigInt(confirmations)?s.state:'confirming'}const record=lifecycleRecord({hash,state:next,blockNumber:s.receipt?.blockNumber||null,receiptStatus:s.receipt?.status??null,confirmations:s.receipt?Number(BigInt(await rpc('eth_blockNumber'))-BigInt(s.receipt.blockNumber)+1n):0});if(record.state!==last?.state||record.blockNumber!==last?.blockNumber){onUpdate?.(record);last=record}if(['confirmed','reverted','dropped'].includes(record.state))return record;await sleep(poll)}return lifecycleRecord({hash,state:'expired',error:'Confirmation timeout'})}
export function replacementStatus(originalHash,replacementHash){if(!replacementHash||!HEX.test(replacementHash))return lifecycleRecord({hash:originalHash,state:'pending'});return lifecycleRecord({hash:originalHash,state:'replaced',replacementHash})}
export function validateRouteStep(step){if(!step||!ADDRESS.test(step.to))throw new Error('Route step has invalid target');if(step.data&&!HEX.test(step.data))throw new Error('Route step has invalid calldata');if(step.value&&(!HEX.test(step.value)||BigInt(step.value)<0n))throw new Error('Route step has invalid value');return true}
export function routeLifecyclePlan(steps=[]){return steps.map((s,i)=>({index:i,label:s.label||s.tool||s.type||`Step ${i+1}`,kind:s.kind||s.type||'transaction',requiresApproval:Boolean(s.requiresApproval),status:'queued'}))}
