const jsonRpc=async(url,method,params=[])=>{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method,params})});const d=await r.json();if(d.error)throw new Error(d.error.message||'Bundler request failed');return d.result};
export const aaConfig=()=>({bundler:import.meta.env.VITE_BUNDLER_URL||'',paymaster:import.meta.env.VITE_PAYMASTER_URL||'',entryPoint:import.meta.env.VITE_ENTRYPOINT||''});
export const sponsorshipReady=()=>{const c=aaConfig();return Boolean(c.bundler&&c.paymaster&&c.entryPoint)};
export const aaReady=()=>Boolean(aaConfig().bundler&&aaConfig().entryPoint);
export async function bundlerRequest(method,params=[]){const {bundler}=aaConfig();if(!bundler)throw new Error('No ERC-4337 bundler configured');return jsonRpc(bundler,method,params)}
export async function supportedEntryPoints(){return bundlerRequest('eth_supportedEntryPoints',[])}
export async function estimateUserOperation(userOp,entryPoint=aaConfig().entryPoint){if(!entryPoint)throw new Error('Missing EntryPoint');return bundlerRequest('eth_estimateUserOperationGas',[userOp,entryPoint])}
export async function sendUserOperation(userOp,entryPoint=aaConfig().entryPoint){if(!entryPoint)throw new Error('Missing EntryPoint');return bundlerRequest('eth_sendUserOperation',[userOp,entryPoint])}
export async function getUserOperationReceipt(hash){return bundlerRequest('eth_getUserOperationReceipt',[hash])}
export async function waitForUserOperation(hash,timeout=180000){const started=Date.now();while(Date.now()-started<timeout){const r=await getUserOperationReceipt(hash);if(r)return r;await new Promise(x=>setTimeout(x,1800))}throw new Error('UserOperation confirmation timed out')}
export function sponsorshipMessage(){if(sponsorshipReady())return'ERC-4337 sponsorship infrastructure configured';if(aaReady())return'ERC-4337 bundler configured; paymaster sponsorship is not configured';return'ERC-4337 execution becomes available when a real bundler + EntryPoint are configured'}