import admin from 'firebase-admin';
const SYMBOLS=['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT'];
const INTERVAL='5m';
const NEWS_URL='https://nfs.faireconomy.media/ff_calendar_thisweek.json';
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store, max-age=0');res.end(JSON.stringify(body))}
function candles(rows){return Array.isArray(rows)?rows.map(x=>({time:Number(x[0]),open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4])})).filter(x=>[x.time,x.open,x.high,x.low,x.close].every(Number.isFinite)):[]}
function pivots(c){const highs=[],lows=[];for(let i=2;i<c.length-2;i++){const x=c[i];if(x.high>c[i-1].high&&x.high>=c[i+1].high&&x.high>c[i-2].high&&x.high>=c[i+2].high)highs.push({price:x.high,time:x.time,index:i});if(x.low<c[i-1].low&&x.low<=c[i+1].low&&x.low<c[i-2].low&&x.low<=c[i+2].low)lows.push({price:x.low,time:x.time,index:i})}return{highs,lows}}
function structure(c){if(c.length<30)return{state:'UNKNOWN',event:null};const{highs,lows}=pivots(c),hs=highs.slice(-3),ls=lows.slice(-3);if(hs.length<2||ls.length<2)return{state:'UNKNOWN',event:null};const bullish=hs.at(-1).price>hs.at(-2).price&&ls.at(-1).price>ls.at(-2).price,bearish=hs.at(-1).price<hs.at(-2).price&&ls.at(-1).price<ls.at(-2).price,last=c.at(-1),prev=c.at(-2),prevHigh=hs.at(-1),prevLow=ls.at(-1);let event=null;if(last.close>prevHigh.price&&prev.close<=prevHigh.price)event={direction:'bullish',type:'BOS',level:prevHigh.price,time:last.time};if(last.close<prevLow.price&&prev.close>=prevLow.price)event={direction:'bearish',type:'BOS',level:prevLow.price,time:last.time};return{state:bullish?'uptrend':bearish?'downtrend':'range',event,high:prevHigh.price,low:prevLow.price}}
async function market(symbol){const r=await fetch(`https://fapi.binance.com/fapi/v1/klines?symbol=${symbol}&interval=${INTERVAL}&limit=150`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Binance returned ${r.status}`);const rows=await r.json();return candles(rows.slice(0,-1))}
function getAdmin(){if(admin.apps.length)return admin;const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('FIREBASE_ADMIN_CREDENTIALS_MISSING');admin.initializeApp({credential:admin.credential.cert(JSON.parse(raw.trim().replace(/^['\"]|['\"]$/g,'')))});return admin}
function parseNewsTime(item){if(Number.isFinite(Number(item?.timestamp)))return Number(item.timestamp)*1000;if(item?.date&&item?.time){const d=String(item.date).trim(),t=String(item.time).trim(),iso=/^\d{4}-\d{2}-\d{2}$/.test(d)?`${d} ${t}`:null;if(iso){const n=Date.parse(iso);if(Number.isFinite(n))return n}const m=d.match(/^(\d{1,2})-(\d{1,2})-(\d{4})$/);if(m){const n=Date.parse(`${m[3]}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')} ${t} UTC`);if(Number.isFinite(n))return n}}return null}
async function news(){const r=await fetch(NEWS_URL,{headers:{Accept:'application/json','User-Agent':'KitAgent/1.0'}});if(!r.ok)throw new Error(`Economic calendar returned ${r.status}`);const data=await r.json(),now=Date.now();return(Array.isArray(data)?data:[]).map((x,i)=>({...x,id:String(x.id||`${x.date||''}-${x.time||''}-${x.title||''}-${i}`),when:parseNewsTime(x)})).filter(x=>String(x.impact||'').toLowerCase()==='high'&&x.when&&x.when>now-300000&&x.when<now+7*86400000).sort((a,b)=>a.when-b.when)}
async function tokens(a){const snap=await a.firestore().collection('users').where('notificationSettings.enabled','==',true).get(),out=[];snap.forEach(doc=>{const map=doc.data()?.pushTokens||{};for(const token of Object.keys(map))if(token&&!out.includes(token))out.push(token)});return out}
async function send(a,list,title,body,data){if(!list.length)return{sent:0};let sent=0;for(let i=0;i<list.length;i+=500){const batch=list.slice(i,i+500),r=await a.messaging().sendEachForMulticast({tokens:batch,notification:{title,body},data:Object.fromEntries(Object.entries(data||{}).map(([k,v])=>[k,String(v)])),webpush:{fcmOptions:{link:'/'}}});sent+=r.successCount}return{sent}}
async function runCron(){const a=getAdmin(),db=a.firestore(),deviceTokens=await tokens(a),result={structure:0,news:0,errors:[]};if(!deviceTokens.length)return{...result,tokens:0};for(const symbol of SYMBOLS){try{const c=await market(symbol),event=structure(c).event;if(!event)continue;const id=`structure-${symbol}-${INTERVAL}-${event.direction}-${event.time}`,ref=db.collection('marketAlertEvents').doc(id),seen=await ref.get();if(seen.exists)continue;await send(a,deviceTokens,`${symbol.replace('USDT','')} ${event.direction==='bullish'?'bullish':'bearish'} structure`,`${event.type}: ${symbol} ${INTERVAL} broke a confirmed swing level.`,{alertId:id,type:'structure',symbol,direction:event.direction,time:event.time});await ref.set({type:'structure',symbol,interval:INTERVAL,direction:event.direction,time:event.time,createdAt:admin.firestore.FieldValue.serverTimestamp()});result.structure++}catch(e){result.errors.push(`${symbol}: ${e?.message||e}`)}}try{const events=await news(),now=Date.now();for(const e of events){const mins=Math.round((e.when-now)/60000);if(mins<10||mins>30)continue;const id=`news-${e.id}-${Math.floor(e.when/600000)}`,ref=db.collection('marketAlertEvents').doc(id),seen=await ref.get();if(seen.exists)continue;const country=e.country||'Market';await send(a,deviceTokens,`HIGH IMPACT — ${country}`,`${e.title||'Major economic release'} in about ${mins} min. Expect elevated volatility.`,{alertId:id,type:'news',eventId:e.id,when:e.when});await ref.set({type:'news',eventId:e.id,title:e.title||'',country,when:e.when,createdAt:admin.firestore.FieldValue.serverTimestamp()});result.news++}}catch(e){result.errors.push(`news: ${e?.message||e}`)}return{...result,tokens:deviceTokens.length}}
export default async function handler(req,res){if(req.method==='POST'){const secret=process.env.CRON_SECRET||'',supplied=req.headers['x-cron-secret']||req.headers.authorization?.replace(/^Bearer\s+/i,'');if(!secret||supplied!==secret)return json(res,401,{error:'Unauthorized'});try{return json(res,200,{ok:true,...await runCron()})}catch(e){return json(res,500,{ok:false,error:e?.message||'Alert job failed'})}}if(req.method==='GET'){try{const symbol=String(req.query?.symbol||'BTCUSDT').toUpperCase();if(!SYMBOLS.includes(symbol))return json(res,400,{error:'Unsupported symbol'});const c=await market(symbol),s=structure(c),events=await news().catch(()=>[]);return json(res,200,{ok:true,symbol,interval:INTERVAL,structure:s,news:events.slice(0,12).map(e=>({id:e.id,title:e.title,country:e.country,impact:e.impact,when:e.when,forecast:e.forecast,previous:e.previous}))})}catch(e){return json(res,500,{ok:false,error:e?.message||'Market alerts unavailable'})}}return json(res,405,{error:'Method not allowed'})}
