const INTERVALS={
  '15m':'15m','30m':'30m','1H':'1H','4H':'4H','1D':'1D','1W':'1W'
};
const BYBIT_INTERVAL={'15m':'15','30m':'30','1H':'60','4H':'240','1D':'D','1W':'W'};
const BINANCE_INTERVAL={'15m':'15m','30m':'30m','1H':'1h','4H':'4h','1D':'1d','1W':'1w'};
function json(res,status,payload){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(payload));}
function normalize(rows){return rows.map(r=>({time:Number(r[0]),open:Number(r[1]),high:Number(r[2]),low:Number(r[3]),close:Number(r[4]),volume:Number(r[5]||0)})).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time)}
function sma(v,n){if(v.length<n)return null;return v.slice(-n).reduce((a,b)=>a+b,0)/n}
function ema(v,n){if(v.length<n)return null;let e=sma(v.slice(0,n),n),k=2/(n+1);for(let i=n;i<v.length;i++)e=v[i]*k+e*(1-k);return e}
function rsi(v,n=14){if(v.length<n+1)return 50;let g=0,l=0;for(let i=1;i<=n;i++){const d=v[i]-v[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/n,al=l/n;for(let i=n+1;i<v.length;i++){const d=v[i]-v[i-1];ag=(ag*(n-1)+Math.max(d,0))/n;al=(al*(n-1)+Math.max(-d,0))/n}if(al===0)return 100;return 100-(100/(1+ag/al))}
function atr(c,n=14){if(c.length<n+1)return null;const t=[];for(let i=1;i<c.length;i++){const x=c[i],p=c[i-1];t.push(Math.max(x.high-x.low,Math.abs(x.high-p.close),Math.abs(x.low-p.close)))}return sma(t.slice(-n),n)}
function roundPrice(v){if(v>=1000)return Number(v.toFixed(2));if(v>=100)return Number(v.toFixed(3));if(v>=1)return Number(v.toFixed(5));if(v>=.1)return Number(v.toFixed(6));return Number(v.toPrecision(7))}
function analyze(c){if(c.length<60)throw new Error(`Not enough candles (${c.length} received)`);const closes=c.map(x=>x.close),last=c.at(-1),e20=ema(closes,20),e50=ema(closes,50),r=rsi(closes),a=atr(c);if(![e20,e50,a].every(Number.isFinite))throw new Error('Indicators could not be calculated');const recent=c.slice(-30),hi=Math.max(...recent.map(x=>x.high)),lo=Math.min(...recent.map(x=>x.low)),score=(last.close>e20?1:-1)+(e20>e50?1:-1)+(r>52?1:r<48?-1:0);let bias=score>=2?'LONG':score<=-2?'SHORT':'WAIT',d=Math.max(a,last.close*.001),entry=last.close,stop,target1,target2;if(bias==='LONG'){stop=Math.min(lo,last.close-d*1.15);if(stop>=entry)stop=entry-d;target1=entry+(entry-stop)*1.5;target2=entry+(entry-stop)*2.5}else if(bias==='SHORT'){stop=Math.max(hi,last.close+d*1.15);if(stop<=entry)stop=entry+d;target1=entry-(stop-entry)*1.5;target2=entry-(stop-entry)*2.5}else{stop=entry+d;target1=entry;target2=entry}const risk=Math.abs(entry-stop),confidence=Math.min(92,Math.max(42,Math.round(50+Math.abs(score)*7+(r>55||r<45?5:0)+(last.close>e20&&e20>e50||last.close<e20&&e20<e50?5:0))));return{bias,confidence,entry:roundPrice(entry),stopLoss:roundPrice(stop),takeProfit1:roundPrice(target1),takeProfit2:roundPrice(target2),riskReward:risk>0&&bias!=='WAIT'?'1:2.5':'—',rsi:Number(r.toFixed(2)),ema20:roundPrice(e20),ema50:roundPrice(e50),atr:roundPrice(a),price:roundPrice(last.close),swingHigh:roundPrice(hi),swingLow:roundPrice(lo),timestamp:last.time}}
async function fetchWithTimeout(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);try{return await fetch(url,{headers:{Accept:'application/json','User-Agent':'KitAgent/1.0'},signal:controller.signal})}finally{clearTimeout(timer)}}
async function fetchOKX(symbol,timeframe){const instId=`${symbol.replace(/[^A-Z0-9]/gi,'').replace(/USDT$/,'')}-USDT-SWAP`,bar=INTERVALS[timeframe],url=`https://www.okx.com/api/v5/market/candles?instId=${encodeURIComponent(instId)}&bar=${encodeURIComponent(bar)}&limit=300`;const r=await fetchWithTimeout(url);if(!r.ok)throw new Error(`OKX returned ${r.status}`);const body=await r.json();if(body?.code!=='0'||!Array.isArray(body?.data)||!body.data.length)throw new Error(body?.msg||'OKX returned no perpetual candles');return normalize(body.data.map(x=>[x[0],x[1],x[2],x[3],x[4],x[5]]))}
async function fetchBybit(symbol,timeframe){const clean=symbol.replace(/[^A-Z0-9]/gi,'');const url=`https://api.bybit.com/v5/market/kline?category=linear&symbol=${encodeURIComponent(clean)}&interval=${BYBIT_INTERVAL[timeframe]}&limit=300`;const r=await fetchWithTimeout(url);if(!r.ok)throw new Error(`Bybit returned ${r.status}`);const body=await r.json();if(body?.retCode!==0||!Array.isArray(body?.result?.list)||!body.result.list.length)throw new Error(body?.retMsg||'Bybit returned no perpetual candles');return normalize(body.result.list.map(x=>[x[0],x[1],x[2],x[3],x[4],x[5]]))}
async function fetchBinance(symbol,timeframe){const clean=symbol.replace(/[^A-Z0-9]/gi,'');const interval=BINANCE_INTERVAL[timeframe],bases=['https://fapi.binance.com/fapi/v1/klines','https://fstream.binance.com/fapi/v1/klines','https://www.binance.com/fapi/v1/klines'];let last='Binance unavailable';for(const base of bases)try{const r=await fetchWithTimeout(`${base}?symbol=${encodeURIComponent(clean)}&interval=${interval}&limit=300`);if(!r.ok){last=`Binance returned ${r.status}`;continue}const rows=await r.json();if(!Array.isArray(rows)||!rows.length){last='Binance returned no candles';continue}return normalize(rows)}catch(e){last=e?.name==='AbortError'?'Binance request timed out':e?.message||last}throw new Error(last)}
async function candles(symbol,timeframe){const errors=[];for(const provider of [fetchOKX,fetchBybit,fetchBinance])try{return{candles:await provider(symbol,timeframe),provider:provider===fetchOKX?'OKX Swap':provider===fetchBybit?'Bybit Linear':'Binance USD-M'}}catch(e){errors.push(e?.message||'provider failed')}throw new Error(`All perpetual providers failed: ${errors.join(' | ')}`)}
export default async function handler(req,res){if(req.method!=='GET')return json(res,405,{ok:false,error:'Method not allowed'});const symbol=String(req.query?.symbol||'BTCUSDT').trim().toUpperCase(),timeframe=String(req.query?.timeframe||'1H');if(!INTERVALS[timeframe])return json(res,400,{ok:false,error:'Unsupported timeframe'});try{const current=await candles(symbol,timeframe),setup=analyze(current.candles),confluence=await Promise.all(['1H','4H','1D'].map(async tf=>{try{const x=await candles(symbol,tf),a=analyze(x.candles);return{timeframe:tf,bias:a.bias,confidence:a.confidence,provider:x.provider}}catch(e){return{timeframe:tf,bias:'UNAVAILABLE',confidence:0,error:e?.message||'Unavailable'}}})),directional=confluence.filter(x=>x.bias==='LONG'||x.bias==='SHORT'),longVotes=directional.filter(x=>x.bias==='LONG').length,shortVotes=directional.filter(x=>x.bias==='SHORT').length,inferred=longVotes>shortVotes?'LONG':shortVotes>longVotes?'SHORT':'WAIT',finalBias=setup.bias!=='WAIT'?setup.bias:inferred,aligned=confluence.filter(x=>x.bias===finalBias&&finalBias!=='WAIT').length,finalConfidence=Math.min(95,Math.max(35,Math.round(setup.confidence+aligned*4-(setup.bias==='WAIT'?4:0)))),finalSetup=finalBias===setup.bias?setup:{...setup,bias:finalBias,confidence:finalConfidence};return json(res,200,{ok:true,market:'perpetual',symbol,timeframe,setup:{...finalSetup,confidence:finalConfidence},confluence,aligned,totalTimeframes:4,source:`${current.provider} with multi-provider fallback`,generatedAt:new Date().toISOString()})}catch(e){return json(res,502,{ok:false,error:e?.message||'Perpetual market analysis failed'})}}