import admin from 'firebase-admin';
import fs from 'node:fs';
import crypto from 'node:crypto';

function getAdmin(){if(admin.apps.length)return admin;const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;const credentialPath=process.env.GOOGLE_APPLICATION_CREDENTIALS;if(raw){admin.initializeApp({credential:admin.credential.cert(JSON.parse(raw.trim().replace(/^['\"]|['\"]$/g,'')))});return admin}if(credentialPath&&fs.existsSync(credentialPath)){admin.initializeApp({credential:admin.credential.cert(JSON.parse(fs.readFileSync(credentialPath,'utf8')))});return admin}const e=new Error('FIREBASE_ADMIN_CREDENTIALS_MISSING');e.code=e.message;throw e}
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(body))}
function canonicalEmail(value){const email=String(value||'').trim().toLowerCase();const [local,domain]=email.split('@');if(!local||!domain)return email;if(domain==='gmail.com'||domain==='googlemail.com')return `${local.split('+')[0].replace(/\./g,'')}@gmail.com`;return email}
function requestIp(req){const forwarded=String(req.headers['x-forwarded-for']||'').split(',')[0].trim();return forwarded||String(req.headers['x-real-ip']||'').trim()||''}
function networkKey(ip){return crypto.createHash('sha256').update(`kitsetups-signup-v2:${ip}`).digest('hex')}
function cleanReferralCode(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,24)}
async function verifyAppCheck(a,req){const token=String(req.headers['x-firebase-appcheck']||'').trim();if(!token)return false;try{await a.appCheck().verifyToken(token);return true}catch(error){console.warn('Firebase App Check verification failed:',error?.message||error);return false}}

export default async function handler(req,res){
 if(req.method!=='POST')return json(res,405,{error:'Method not allowed.'});
 try{
  const a=getAdmin();
  const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const email=String(body.email||'').trim().toLowerCase();const password=String(body.password||'');const ip=requestIp(req);const deviceId=String(body.deviceId||'').trim().toLowerCase();const referralCode=cleanReferralCode(body.referralCode);const deviceFingerprint=String(body.deviceFingerprint||'').trim().toLowerCase();const deviceProfile=body.deviceProfile&&typeof body.deviceProfile==='object'?body.deviceProfile:{};
  if(req.headers['x-firebase-appcheck'])await verifyAppCheck(a,req);
  if(!/^\S+@\S+\.\S+$/.test(email))return json(res,400,{error:'Enter a valid email address.',code:'INVALID_EMAIL'});if(password.length<6)return json(res,400,{error:'Use a stronger password (at least 6 characters).',code:'WEAK_PASSWORD'});if(!/^[a-f0-9]{64}$/.test(deviceId)||!/^[a-f0-9]{64}$/.test(deviceFingerprint))return json(res,400,{error:'Invalid device binding.',code:'DEVICE_ID_INVALID'});
  const db=a.firestore();let affiliateRef=null;if(referralCode){const affiliateQuery=await db.collection('affiliates').where('referralCode','==',referralCode).limit(1).get();if(!affiliateQuery.empty){const candidate=affiliateQuery.docs[0];if(candidate.data()?.status==='active')affiliateRef={id:candidate.id,referralCode}}}
  const deviceRef=db.collection('deviceBindings').doc(deviceId);const existingDevice=await deviceRef.get();const fingerprintQuery=await db.collection('deviceBindings').where('deviceFingerprint','==',deviceFingerprint).limit(1).get();if(!fingerprintQuery.empty){const fingerprintDoc=fingerprintQuery.docs[0];const boundUid=String(fingerprintDoc.data()?.uid||'');if(boundUid){let boundUserExists=true;try{await a.auth().getUser(boundUid)}catch(error){if(error?.code==='auth/user-not-found')boundUserExists=false;else throw error}if(boundUserExists)return json(res,409,{error:'This device is already registered to another KitSetups account. Sign in instead.',code:'DEVICE_ALREADY_REGISTERED'});}}}
  const profile={osFamily:String(deviceProfile.osFamily||''),language:String(deviceProfile.language||''),timezone:String(deviceProfile.timezone||''),hardwareConcurrency:Number(deviceProfile.hardwareConcurrency)||0,deviceMemory:Number(deviceProfile.deviceMemory)||0,screenWidth:Number(deviceProfile.screenWidth)||0,screenHeight:Number(deviceProfile.screenHeight)||0,availWidth:Number(deviceProfile.availWidth)||0,availHeight:Number(deviceProfile.availHeight)||0,colorDepth:Number(deviceProfile.colorDepth)||0,pixelRatio:Number(deviceProfile.pixelRatio)||0,maxTouchPoints:Number(deviceProfile.maxTouchPoints)||0};
  const candidateQuery=profile.osFamily?await db.collection('deviceBindings').where('osFamily','==',profile.osFamily).limit(100).get():{empty:true,docs:[]};
  for(const candidate of candidateQuery.docs){const data=candidate.data()||{};const uid=String(data.uid||'');if(!uid||uid===String(existingDevice.data()?.uid||''))continue;const score=(data.osFamily===profile.osFamily?3:0)+(data.timezone&&data.timezone===profile.timezone?2:0)+(Number(data.hardwareConcurrency)===profile.hardwareConcurrency&&profile.hardwareConcurrency?2:0)+(Number(data.maxTouchPoints)===profile.maxTouchPoints?2:0)+(((Number(data.screenWidth)===profile.screenWidth&&Number(data.screenHeight)===profile.screenHeight)||(Number(data.screenWidth)===profile.screenHeight&&Number(data.screenHeight)===profile.screenWidth))?3:0)+(Number(data.availWidth)===profile.availWidth&&Number(data.availHeight)===profile.availHeight&&profile.availWidth?1:0)+(Math.abs(Number(data.pixelRatio)-profile.pixelRatio)<0.01&&profile.pixelRatio?2:0)+(Number(data.colorDepth)===profile.colorDepth&&profile.colorDepth?1:0)+(Number(data.deviceMemory)===profile.deviceMemory&&profile.deviceMemory?1:0);if(score>=13){try{await a.auth().getUser(uid);return json(res,409,{error:'This device is already registered to another KitSetups account. Sign in instead.',code:'DEVICE_ALREADY_REGISTERED'})}catch(error){if(error?.code!=='auth/user-not-found')throw error;}}}
  if(existingDevice.exists&&existingDevice.data()?.uid){const boundUid=String(existingDevice.data().uid);let boundUserExists=true;try{await a.auth().getUser(boundUid)}catch(error){if(error?.code==='auth/user-not-found')boundUserExists=false;else throw error}if(boundUserExists)return json(res,409,{error:'This device is already registered to another KitSetups account. Sign in instead.',code:'DEVICE_ALREADY_REGISTERED'});await deviceRef.delete().catch(()=>{});}
  const canonical=canonicalEmail(email);const lockRef=db.collection('accountIdentityLocks').doc(encodeURIComponent(canonical));const networkRef=ip?db.collection('signupNetworkLocks').doc(networkKey(ip)):null;const existingLock=await lockRef.get();if(existingLock.exists){const lockedUid=String(existingLock.data()?.uid||'');let lockedUserExists=Boolean(lockedUid);if(lockedUid){try{await a.auth().getUser(lockedUid)}catch(error){if(error?.code==='auth/user-not-found')lockedUserExists=false;else throw error}}if(lockedUserExists)return json(res,409,{error:'An account already exists for this email identity. Sign in instead.',code:'ACCOUNT_ALREADY_EXISTS'});await lockRef.delete().catch(()=>{});}
  if(networkRef){const networkLock=await networkRef.get();if(networkLock.exists){const lockedUid=String(networkLock.data()?.uid||'');let lockedUserExists=Boolean(lockedUid);if(lockedUid){try{await a.auth().getUser(lockedUid)}catch(error){if(error?.code==='auth/user-not-found')lockedUserExists=false;else throw error}}if(lockedUserExists)return json(res,409,{error:'An account has already been created from this network. Sign in instead.',code:'NETWORK_ACCOUNT_EXISTS'});await networkRef.delete().catch(()=>{});}}
  try{const existingUser=await a.auth().getUserByEmail(email);if(existingUser)return json(res,409,{error:'An account already exists with this email. Sign in instead.',code:'ACCOUNT_ALREADY_EXISTS'})}catch(error){if(error?.code!=='auth/user-not-found')throw error}
  const reservation={email,canonicalEmail:canonical,createdAt:admin.firestore.FieldValue.serverTimestamp(),status:'reserved'};try{await db.runTransaction(async tx=>{const snap=await tx.get(lockRef);if(snap.exists){const e=new Error('ACCOUNT_ALREADY_EXISTS');e.code=e.message;throw e}if(networkRef){const networkSnap=await tx.get(networkRef);if(networkSnap.exists){const e=new Error('NETWORK_ACCOUNT_EXISTS');e.code=e.message;throw e}tx.create(networkRef,{email,canonicalEmail:canonical,status:'reserved',createdAt:admin.firestore.FieldValue.serverTimestamp()})}tx.create(lockRef,reservation)})}catch(error){if(error?.code==='ACCOUNT_ALREADY_EXISTS')return json(res,409,{error:'An account already exists for this email identity. Sign in instead.',code:error.code});if(error?.code==='NETWORK_ACCOUNT_EXISTS')return json(res,409,{error:'An account has already been created from this network. Sign in instead.',code:error.code});throw error}
  let userRecord;try{userRecord=await a.auth().createUser({email,password,emailVerified:false});const now=new Date();const trialEndsAt=new Date(now.getTime()+3*24*60*60*1000);const profile={uid:userRecord.uid,email,status:'active',plan:'free',trialStartedAt:now,trialEndsAt,createdAt:now,updatedAt:admin.firestore.FieldValue.serverTimestamp()};if(affiliateRef){profile.affiliate={affiliateId:affiliateRef.id,referralCode:affiliateRef.referralCode,attributedAt:now,status:'attributed'};await db.collection('referrals').doc(userRecord.uid).set({referredUserId:userRecord.uid,affiliateId:affiliateRef.id,referralCode:affiliateRef.referralCode,status:'attributed',signupAt:admin.firestore.FieldValue.serverTimestamp(),createdAt:admin.firestore.FieldValue.serverTimestamp()})}await db.collection('users').doc(userRecord.uid).set(profile,{merge:true});await deviceRef.set({uid:userRecord.uid,deviceFingerprint,...profile,lastSeenAt:admin.firestore.FieldValue.serverTimestamp(),createdAt:admin.firestore.FieldValue.serverTimestamp(),version:4},{merge:true});await lockRef.set({uid:userRecord.uid,status:'active',updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});if(networkRef)await networkRef.set({uid:userRecord.uid,email,canonicalEmail:canonical,status:'active',updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true})}catch(error){await lockRef.delete().catch(()=>{});if(networkRef)await networkRef.delete().catch(()=>{});await db.collection('users').doc(userRecord?.uid||'invalid').delete().catch(()=>{});await db.collection('referrals').doc(userRecord?.uid||'invalid').delete().catch(()=>{});if(error?.code==='auth/email-already-exists')return json(res,409,{error:'An account already exists with this email. Sign in instead.',code:'ACCOUNT_ALREADY_EXISTS'});throw error}
  const customToken=await a.auth().createCustomToken(userRecord.uid);return json(res,200,{customToken,uid:userRecord.uid});
 }catch(error){if(error?.code==='FIREBASE_ADMIN_CREDENTIALS_MISSING')return json(res,500,{error:'Firebase Admin credentials are missing.',code:error.code});console.error('register-account failed',error);return json(res,500,{error:'Account creation could not be completed.',code:'ACCOUNT_REGISTRATION_FAILED'})}
}
