import admin from 'firebase-admin';
import fs from 'node:fs';
import crypto from 'node:crypto';

function getAdmin(){if(admin.apps.length)return admin;const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;const credentialPath=process.env.GOOGLE_APPLICATION_CREDENTIALS;if(raw){admin.initializeApp({credential:admin.credential.cert(JSON.parse(raw.trim().replace(/^['\"]|['\"]$/g,'')))});return admin}if(credentialPath&&fs.existsSync(credentialPath)){admin.initializeApp({credential:admin.credential.cert(JSON.parse(fs.readFileSync(credentialPath,'utf8')))});return admin}const e=new Error('FIREBASE_ADMIN_CREDENTIALS_MISSING');e.code=e.message;throw e}
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(body))}
function canonicalEmail(value){const email=String(value||'').trim().toLowerCase();const [local,domain]=email.split('@');if(!local||!domain)return email;if(domain==='gmail.com'||domain==='googlemail.com')return `${local.split('+')[0].replace(/\./g,'')}@gmail.com`;return email}
function requestIp(req){const forwarded=String(req.headers['x-forwarded-for']||'').split(',')[0].trim();return forwarded||String(req.headers['x-real-ip']||'').trim()||''}
function networkKey(ip){return crypto.createHash('sha256').update(`kitsetups-signup-v2:${ip}`).digest('hex')}
function cleanReferralCode(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,24)}
async function verifyAppCheck(a,req){const token=String(req.headers['x-firebase-appcheck']||'').trim();if(!token)return false;try{await a.appCheck().verifyToken(token);return true}catch(error){console.warn('Firebase App Check verification failed:',error?.message||error);return false}}
async function verifyRecaptcha(token,ip){const secret=String(process.env.RECAPTCHA_SECRET_KEY||'').trim();if(!secret)return {ok:false,configured:false};if(!token)return {ok:false,configured:true};try{const body=new URLSearchParams({secret,response:token});if(ip)body.set('remoteip',ip);const response=await fetch('https://www.google.com/recaptcha/api/siteverify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const result=await response.json();return {ok:Boolean(response.ok&&result.success),configured:true}}catch(error){console.warn('reCAPTCHA verification request failed:',error?.message||error);return {ok:false,configured:true}}}

export default async function handler(req,res){
 if(req.method!=='POST')return json(res,405,{error:'Method not allowed.'});
 try{
  const a=getAdmin();
  const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const email=String(body.email||'').trim().toLowerCase();const password=String(body.password||'');const ip=requestIp(req);const deviceId=String(body.deviceId||'').trim().toLowerCase();const referralCode=cleanReferralCode(body.referralCode);
  const recaptcha=await verifyRecaptcha(String(body.recaptchaToken||'').trim(),ip);if(!recaptcha.configured)return json(res,500,{error:'reCAPTCHA is not configured.',code:'RECAPTCHA_NOT_CONFIGURED'});if(!recaptcha.ok)return json(res,403,{error:'Please complete the reCAPTCHA check and try again.',code:'RECAPTCHA_FAILED'});
  if(req.headers['x-firebase-appcheck'])await verifyAppCheck(a,req);
  if(!/^\S+@\S+\.\S+$/.test(email))return json(res,400,{error:'Enter a valid email address.',code:'INVALID_EMAIL'});if(password.length<6)return json(res,400,{error:'Use a stronger password (at least 6 characters).',code:'WEAK_PASSWORD'});if(!/^[a-f0-9]{64}$/.test(deviceId))return json(res,400,{error:'Invalid device binding.',code:'DEVICE_ID_INVALID'});
  const db=a.firestore();let affiliateRef=null;if(referralCode){const affiliateQuery=await db.collection('affiliates').where('referralCode','==',referralCode).limit(1).get();if(!affiliateQuery.empty){const candidate=affiliateQuery.docs[0];if(candidate.data()?.status==='active')affiliateRef={id:candidate.id,referralCode}}}
  const deviceRef=db.collection('deviceBindings').doc(deviceId);const existingDevice=await deviceRef.get();if(existingDevice.exists&&existingDevice.data()?.uid)return json(res,409,{error:'This device is already registered to another KitSetups account. Sign in instead.',code:'DEVICE_ALREADY_REGISTERED'});
  const canonical=canonicalEmail(email);const lockRef=db.collection('accountIdentityLocks').doc(encodeURIComponent(canonical));const networkRef=ip?db.collection('signupNetworkLocks').doc(networkKey(ip)):null;const existingLock=await lockRef.get();if(existingLock.exists)return json(res,409,{error:'An account already exists for this email identity. Sign in instead.',code:'ACCOUNT_ALREADY_EXISTS'});
  if(networkRef){const networkLock=await networkRef.get();if(networkLock.exists)return json(res,409,{error:'An account has already been created from this network. Sign in instead.',code:'NETWORK_ACCOUNT_EXISTS'})}
  try{const existingUser=await a.auth().getUserByEmail(email);if(existingUser)return json(res,409,{error:'An account already exists with this email. Sign in instead.',code:'ACCOUNT_ALREADY_EXISTS'})}catch(error){if(error?.code!=='auth/user-not-found')throw error}
  const reservation={email,canonicalEmail:canonical,createdAt:admin.firestore.FieldValue.serverTimestamp(),status:'reserved'};try{await db.runTransaction(async tx=>{const snap=await tx.get(lockRef);if(snap.exists){const e=new Error('ACCOUNT_ALREADY_EXISTS');e.code=e.message;throw e}if(networkRef){const networkSnap=await tx.get(networkRef);if(networkSnap.exists){const e=new Error('NETWORK_ACCOUNT_EXISTS');e.code=e.message;throw e}tx.create(networkRef,{email,canonicalEmail:canonical,status:'reserved',createdAt:admin.firestore.FieldValue.serverTimestamp()})}tx.create(lockRef,reservation)})}catch(error){if(error?.code==='ACCOUNT_ALREADY_EXISTS')return json(res,409,{error:'An account already exists for this email identity. Sign in instead.',code:error.code});if(error?.code==='NETWORK_ACCOUNT_EXISTS')return json(res,409,{error:'An account has already been created from this network. Sign in instead.',code:error.code});throw error}
  let userRecord;try{userRecord=await a.auth().createUser({email,password,emailVerified:false});const now=new Date();const trialEndsAt=new Date(now.getTime()+3*24*60*60*1000);const profile={uid:userRecord.uid,email,status:'active',plan:'free',trialStartedAt:now,trialEndsAt,createdAt:now,updatedAt:admin.firestore.FieldValue.serverTimestamp()};if(affiliateRef){profile.affiliate={affiliateId:affiliateRef.id,referralCode:affiliateRef.referralCode,attributedAt:now,status:'attributed'};await db.collection('referrals').doc(userRecord.uid).set({referredUserId:userRecord.uid,affiliateId:affiliateRef.id,referralCode:affiliateRef.referralCode,status:'attributed',signupAt:admin.firestore.FieldValue.serverTimestamp(),createdAt:admin.firestore.FieldValue.serverTimestamp()})}await db.collection('users').doc(userRecord.uid).set(profile,{merge:true});await lockRef.set({uid:userRecord.uid,status:'active',updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});if(networkRef)await networkRef.set({uid:userRecord.uid,email,canonicalEmail:canonical,status:'active',updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true})}catch(error){await lockRef.delete().catch(()=>{});if(networkRef)await networkRef.delete().catch(()=>{});await db.collection('users').doc(userRecord?.uid||'invalid').delete().catch(()=>{});await db.collection('referrals').doc(userRecord?.uid||'invalid').delete().catch(()=>{});if(error?.code==='auth/email-already-exists')return json(res,409,{error:'An account already exists with this email. Sign in instead.',code:'ACCOUNT_ALREADY_EXISTS'});throw error}
  const customToken=await a.auth().createCustomToken(userRecord.uid);return json(res,200,{customToken,uid:userRecord.uid});
 }catch(error){if(error?.code==='FIREBASE_ADMIN_CREDENTIALS_MISSING')return json(res,500,{error:'Firebase Admin credentials are missing.',code:error.code});console.error('register-account failed',error);return json(res,500,{error:'Account creation could not be completed.',code:'ACCOUNT_REGISTRATION_FAILED'})}
}
