const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const r=(n,d=5)=>Number(n.toFixed(d));
const EMA=(xs,p)=>{const k=2/(p+1);let e=xs[0];for(let i=1;i<xs.length;i++)e=xs[i]*k+e*(1-k);return e};
const RSI=(xs,p=14)=>{let gain=0,loss=0;for(let i=1;i<=p;i++){const d=xs[i]-xs[i-1];if(d>=0)gain+=d;else loss-=d}gain/=p;loss/=p;for(let i=p+1;i<xs.length;i++){const d=xs[i]-xs[i-1];gain=(gain*(p-1)+Math.max(d,0))/p;loss=(loss*(p-1)+Math.max(-d,0))/p}return loss===0?100:100-100/(1+gain/loss)};
const ATR=(bars,p=14)=>{let trs=[];for(let i=1;i<bars.length;i++){const b=bars[i],prev=bars[i-1];trs.push(Math.max(b.h-b.l,Math.abs(b.h-prev.c),Math.abs(b.l-prev.c)))}return trs.slice(-p).reduce((a,b)=>a+b,0)/Math.min(p,trs.length)};
function setup(bars,market,symbol,interval){const closes=bars.map(b=>b.c),last=bars.at(-1).c,ema20=EMA(closes.slice(-80),20),ema50=EMA(closes.slice(-120),50),rsi=RSI(closes.slice(-100)),atr=ATR(bars),high=Math.max(...bars.slice(-30).map(b=>b.h)),low=Math.min(...bars.slice(-30).map(b=>b.l));const bullish=last>ema20&&ema20>ema50&&rsi>=52;const bearish=last<ema20&&ema20<ema50&&rsi<=48;const direction=bullish?'LONG':bearish?'SHORT':'WAIT';const buffer=atr*(market==='perp'?1.35:1.15);let entry=last,sl,tp1,tp2;if(direction==='LONG'){entry=Math.max(last,ema20-atr*.15);sl=Math.min(low,entry-buffer);const risk=entry-sl;tp1=entry+risk*2;tp2=entry+risk*3;}else if(direction==='SHORT'){entry=Math.min(last,ema20+atr*.15);sl=Math.max(high,entry+buffer);const risk=sl-entry;tp1=entry-risk*2;tp2=entry-risk*3;}else{entry=last;sl=null;tp1=null;tp2=null}const risk=sl==null?null:Math.abs(entry-sl),rr=direction==='WAIT'?null:2;const trendScore=clamp(Math.round(50+Math.abs(ema20-ema50)/Math.max(atr,1e-12)*8+Math.abs(rsi-50)*.8),0,99);return{market,symbol,interval,price:r(last),direction,entry:r(entry),sl:sl==null?null:r(sl),tp1:tp1==null?null:r(tp1),tp2:tp2==null?null:r(tp2),rr:r(rr,2),risk:risk==null?null:r(risk),rsi:r(rsi,2),ema20:r(ema20),ema50:r(ema50),atr:r(atr),swingHigh:r(high),swingLow:r(low),confidence:direction==='WAIT'?Math.max(35,100-Math.abs(rsi-50)):clamp(trendScore,55,94),status:direction==='WAIT'?'NO TRADE':'SETUP READY',note:direction==='WAIT'?'Structure is mixed. Wait for trend alignment instead of forcing an entry.':`Trend + momentum alignment detected. Entry is anchored to price/EMA structure with an ATR-aware invalidation.`}}
async function getCrypto(symbol,interval,limit){const u=new URL('https://fapi.binance.com/fapi/v1/klines');u.searchParams.set('symbol',symbol.replace('/','').toUpperCase());u.searchParams.set('interval',interval);u.searchParams.set('limit',String(limit));const x=await fetch(u);if(!x.ok)throw new Error('Crypto perpetual market feed unavailable');const j=await x.json();return j.map(b=>({o:+b[1],h:+b[2],l:+b[3],c:+b[4]}))}
async function getFx(symbol,interval,limit){const pair=symbol.replace('/','').toUpperCase();const u=new URL('https://query1.finance.yahoo.com/v8/finance/chart/'+pair+'=X');u.searchParams.set('interval',interval==='1h'?'1h':interval);u.searchParams.set('range','3mo');const x=await fetch(u,{headers:{accept:'application/json'}});if(!x.ok)throw new Error('Forex market feed unavailable');const j=await x.json();const q=j.chart?.result?.[0];if(!q)throw new Error('Forex pair not found');const z=q.indicators.quote[0];return z.close.map((c,i)=>({o:z.open[i],h:z.high[i],l:z.low[i],c})).filter(b=>[b.o,b.h,b.l,b.c].every(Number.isFinite)).slice(-limit)}
export default async function handler(req,res){res.setHeader('cache-control','s-maxage=15, stale-while-revalidate=30');if(req.method!=='GET')return res.status(405).json({error:'GET only'});try{const p=req.query||{};const market=String(p.market||'forex').toLowerCase();const symbol=String(p.symbol||'EURUSD').toUpperCase();const interval=String(p.interval||'1h');if(!['forex','perp'].includes(market))return res.status(400).json({error:'market must be forex or perp'});if(!/^([A-Z0-9]{3,12})\/?([A-Z0-9]{3,12})$/.test(symbol.replace('/',''))&&market==='forex')return res.status(400).json({error:'Use forex symbols such as EURUSD or GBPUSD'});const bars=market==='perp'?await getCrypto(symbol,interval,150):await getFx(symbol,interval,150);if(bars.length<60)throw new Error('Not enough market history');return res.status(200).json({ok:true,setup:setup(bars,market,symbol,interval),generatedAt:new Date().toISOString()})}catch(e){return res.status(502).json({error:e.message||'Market analysis unavailable'})}}
