// KitAgent trading engine: multi-timeframe confluence with provider fallbacks.
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));const r=(n,d=5)=>Number.isFinite(n)?Number(n.toFixed(d)):null;
const EMA=(xs,p)=>{if(xs.length<p)return xs.at(-1);const k=2/(p+1);let e=xs[0];for(let i=1;i<xs.length;i++)e=xs[i]*k+e*(1-k);return e};
const RSI=(xs,p=14)=>{if(xs.length<=p)return 50;let g=0,l=0;for(let i=1;i<=p;i++){const d=xs[i]-xs[i-1];if(d>=0)g+=d;else l-=d}g/=p;l/=p;for(let i=p+1;i<xs.length;i++){const d=xs[i]-xs[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p}return l===0?100:100-100/(1+g/l)};
const ATR=(b,p=14)=>{if(b.length<2)return 0;const t=[];for(let i=1;i<b.length;i++){const x=b[i],q=b[i-1];t.push(Math.max(x.h-x.l,Math.abs(x.h-q.c),Math.abs(x.l-q.c)))}return t.slice(-p).reduce((a,x)=>a+x,0)/Math.min(p,t.length)};
function one(b,market,symbol,interval){const c=b.map(x=>x.c),last=c.at(-1),e20=EMA(c.slice(-100),20),e50=EMA(c.slice(-140),50),rsi=RSI(c.slice(-100)),atr=ATR(b),high=Math.max(...b.slice(-30).map(x=>x.h)),low=Math.min(...b.slice(-30).map(x=>x.l));const bull=last>e20&&e20>e50&&rsi>=52,bear=last<e20&&e20<e50&&rsi<=48,direction=bull?'LONG':bear?'SHORT':'WAIT',buffer=atr*(market==='perp'?1.35:1.15);let entry=last,sl=null,tp1=null,tp2=null,rr=null;if(direction==='LONG'){entry=Math.max(last,e20-atr*.15);sl=Math.min(low,entry-buffer);const risk=entry-sl;tp1=entry+risk*1.5;tp2=entry+risk*2.5;rr=2.5}else if(direction==='SHORT'){entry=Math.min(last,e20+atr*.15);sl=Math.max(high,entry+buffer);const risk=sl-entry;tp1=entry-risk*1.5;tp2=entry-risk*2.5;rr=2.5}const score=clamp(Math.round(50+Math.abs(e20-e50)/Math.max(atr,1e-12)*8+Math.abs(rsi-50)*.8),0,99);return{market,symbol,interval,price:r(last),direction,entry:r(entry),sl:r(sl),tp1:r(tp1),tp2:r(tp2),rr:r(rr||0,2),rsi:r(rsi,2),ema20:r(e20),ema50:r(e50),atr:r(atr),swingHigh:r(high),swingLow:r(low),confidence:direction==='WAIT'?Math.max(35,Math.round(100-Math.abs(rsi-50))):clamp(score,55,94),status:direction==='WAIT'?'NO TRADE':'SETUP READY',note:direction==='WAIT'?'Mixed structure. Wait for confirmation rather than force a trade.':'Trend, momentum and volatility align; levels are anchored to current price and market structure.'}}
function aggregate(b,size){const out=[];for(let i=0;i+size-1<b.length;i+=size){const x=b.slice(i,i+size);out.push({o:x[0].o,h:Math.max(...x.map(v=>v.h)),l:Math.min(...x.map(v=>v.l)),c:x.at(-1).c})}return out}
async function fetchJson(url,options={}){const x=await fetch(url,options);if(!x.ok)throw Error(`HTTP ${x.status}`);return x.json()}
async function yahoo(symbol,interval,range){const pair=symbol.replace('/','').toUpperCase();const urls=[`https://query1.finance.yahoo.com/v8/finance/chart/${pair}=X?interval=${interval}&range=${range}`,`https://query2.finance.yahoo.com/v8/finance/chart/${pair}=X?interval=${interval}&range=${range}`];let last;for(const url of urls){try{const q=await fetchJson(url,{headers:{accept:'application/json','user-agent':'KitAgent/1.0'}});const z=q.chart?.result?.[0]?.indicators?.quote?.[0];if(z){const rows=z.close.map((c,i)=>({o:z.open[i],h:z.high[i],l:z.low[i],c})).filter(b=>[b.o,b.h,b.l,b.c].every(Number.isFinite));if(rows.length>=60)return rows.slice(-240)}last=Error('Forex candles unavailable')}catch(e){last=e}}throw Error('Forex market feed unavailable: '+(last?.message||'provider rejected request'))}
async function fxProvider(symbol,interval){const pair=symbol.replace('/','').toUpperCase();const stooq=`https://stooq.com/q/d/l/?s=${pair.toLowerCase()}&i=d`;if(interval==='1d'){try{const text=await (await fetch(stooq)).text();const rows=text.trim().split(/\r?\n/).slice(1).map(line=>line.split(',')).filter(x=>x.length>=5).map(x=>({o:+x[1],h:+x[2],l:+x[3],c:+x[4]})).filter(b=>[b.o,b.h,b.l,b.c].every(Number.isFinite));if(rows.length>=60)return rows.slice(-240)}catch{} }return null}
async function forexCandles(symbol,interval){if(interval==='4h'){const hourly=await yahoo(symbol,'1h','30d');return aggregate(hourly,4).slice(-160)}if(interval==='15m'){return yahoo(symbol,'15m','5d')}if(interval==='1h'){return yahoo(symbol,'1h','30d')}if(interval==='1d'){const fallback=await fxProvider(symbol,interval);return fallback||yahoo(symbol,'1d','2y')}throw Error('Unsupported forex timeframe')}
async function candles(market,symbol,interval,limit=160){if(market==='perp'){const clean=symbol.replace('/','').toUpperCase();const urls=[`https://fapi.binance.com/fapi/v1/klines?symbol=${clean}&interval=${interval}&limit=${limit}`,`https://api.binance.com/api/v3/klines?symbol=${clean}&interval=${interval}&limit=${limit}`];let last;for(const url of urls){try{const rows=await fetchJson(url);if(Array.isArray(rows)&&rows.length>=60)return rows.map(b=>({o:+b[1],h:+b[2],l:+b[3],c:+b[4]}))}catch(e){last=e}}throw Error('Crypto perpetual market feed unavailable: '+(last?.message||'provider rejected request'))}return forexCandles(symbol,interval)}
export default async function handler(req,res){res.setHeader('cache-control','s-maxage=15, stale-while-revalidate=30');if(req.method!=='GET')return res.status(405).json({error:'GET only'});try{const p=req.query||{},market=String(p.market||'forex').toLowerCase(),symbol=String(p.symbol||'EURUSD').toUpperCase(),interval=String(p.interval||'1h').toLowerCase();if(!['forex','perp'].includes(market))return res.status(400).json({error:'market must be forex or perp'});if(!['15m','1h','4h','1d'].includes(interval))return res.status(400).json({error:'interval must be 15m, 1h, 4h or 1d'});if(market==='forex'&&!/^[A-Z]{6}$/.test(symbol.replace('/','')))return res.status(400).json({error:'Forex symbols must use six letters, e.g. EURUSD'});const frames=['1d','4h','1h','15m'];const results=await Promise.all(frames.map(async f=>[f,await candles(market,symbol,f)]));const multi=Object.fromEntries(results.map(([f,b])=>{if(b.length<60)throw Error(`Not enough ${f} market history`);return[f,one(b,market,symbol,f)]}));const base=multi[interval]||multi['1h'];const sides=Object.values(multi).map(x=>x.direction),long=sides.filter(x=>x==='LONG').length,short=sides.filter(x=>x==='SHORT').length;const consensus=long>=3?'LONG':short>=3?'SHORT':base.direction;const setup={...base,direction:consensus,confluence:long>=3||short>=3?`${Math.max(long,short)}/4 timeframes aligned`:'Mixed — wait for confirmation'};if(consensus!==base.direction&&consensus!=='WAIT'){const e=base.price,a=base.atr;if(consensus==='LONG'){setup.entry=e;setup.sl=r(e-a*1.2);setup.tp1=r(e+(e-setup.sl)*1.5);setup.tp2=r(e+(e-setup.sl)*2.5)}else{setup.entry=e;setup.sl=r(e+a*1.2);setup.tp1=r(e-(setup.sl-e)*1.5);setup.tp2=r(e-(setup.sl-e)*2.5)}setup.rr=2.5;setup.status='CONFLUENCE SETUP'}return res.status(200).json({ok:true,setup,multi,generatedAt:new Date().toISOString()})}catch(e){return res.status(502).json({error:e.message||'Market analysis unavailable'})}}
